'\" t
.\"     Title: neo4j-backup
.\"    Author: The Neo4j Team
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 10/19/2016
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "NEO4J\-BACKUP" "1" "10/19/2016" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------


.SH "NAME"
neo4j-backup \- Neo4j Backup Tool
.SH "SYNOPSIS"
.sp
\fBneo4j\-backup\fR \-host <host> [\-port <port>] \-to target_directory

.SH "DESCRIPTION"

.sp
A tool to perform live backups over the network from a running Neo4j graph database onto a local filesystem\&. Backups can be either full or incremental\&. The first backup must be a full backup, after that incremental backups can be performed\&.
.sp
The source(s) are given as host:port pairs, the target is a filesystem location\&.
.sp
For help regarding Windows, see the reference in \m[blue]\fBhttps://neo4j\&.com/docs/operations\-manual/current/deployment/single\-instance/windows/\fR\m[]\&.

.SH "BACKUP TYPE"



.PP
\fB\-full\fR
.RS 4



copies the entire database to a directory\&.

.RE
.PP
\fB\-incremental\fR
.RS 4



copies the changes that have taken place since the last full or incremental backup to an existing backup store\&.

.RE
.sp
The backup tool will automatically detect whether it needs to do a full or an incremental backup\&.

.SH "SOURCE ADDRESS"

.sp
Backup sources are given in the following format:
.sp
\fB\-host <host> [\-port <port>]\fR


.PP
\fBhost\fR
.RS 4



In single mode, the host of a source database; in HA mode, the cluster address of a cluster member\&.

.RE
.PP
\fBport\fR
.RS 4



In single mode, the port of a source database backup service; in HA mode, the port of a cluster instance\&. If not given, the default value
6362
will be used for single mode,
5001
for HA\&.

.RE

.SH "IMPORTANT"

.sp
Backups can only be performed on databases which have the configuration parameter \fBenable_online_backup=true\fR set\&. That will make the backup service available on the default port (6362)\&. To enable the backup service on a different port use for example \fBenable_online_backup=port=9999\fR instead\&.

.SH "EXAMPLES"


.sp
.if n \{\
.RS 4
.\}
.nf
# Performing a backup the first time: create a blank directory and run the backup tool
mkdir /mnt/backup/neo4j\-backup
neo4j\-backup \-host 192\&.168\&.1\&.34 \-to /mnt/backup/neo4j\-backup

# Subsequent backups using the same _target_\-directory will be incremental and therefore quick
neo4j\-backup \-host freja \-to /mnt/backup/neo4j\-backup

# Performing a backup where the service is registered on a custom port
neo4j\-backup \-host freja \-port 9999 \-to /mnt/backup/neo4j\-backup

# Performing a backup from HA cluster, specifying a cluster member
\&./neo4j\-backup \-host oden \-to /mnt/backup/neo4j\-backup

# Performing a backup from HA cluster, specifying a cluster member registered on custom port
\&./neo4j\-backup \-host oden \-port 9191 \-to /mnt/backup/neo4j\-backup
.fi
.if n \{\
.RE
.\}
.sp

.SH "RESTORE FROM BACKUP"

.sp
The Neo4j backups are fully functional databases\&. To use a backup, replace your database directory with the backup\&.

.SH "AUTHOR"
.PP
\fBThe Neo4j Team\fR
.RS 4
Author.
.RE
