[[cypher]]
= Cypher

ifndef::asciidoctor[]
[partintro]
--
The Cypher part is the authoritative source for details on the Cypher Query Language.
For a short introduction, see <<cypher-introduction>>.
To take your first steps with Cypher, see <<cypher-getting-started>>.
For the terminology used, see <<terminology>>.
--
endif::[]

ifdef::asciidoctor[]
[abstract]
--
This chapter contains the complete and authoritative documentation for the Cypher query language.
--
endif::[]


ifndef::asciidoctor[:leveloffset: 1]

include::general/index.asciidoc[leveloffset=+1]

ifndef::asciidoctor[:leveloffset: 1]

include::syntax/index.asciidoc[leveloffset=+1]

ifndef::asciidoctor[:leveloffset: 1]

//xxinclude::general.asciidoc[leveloffset=+1]

//:leveloffset: 1

//xxinclude::read.asciidoc[leveloffset=+1]

ifndef::asciidoctor[:leveloffset: 1]

//xxinclude::write.asciidoc[leveloffset=+1]

include::clause.asciidoc[leveloffset=+1]

ifndef::asciidoctor[:leveloffset: 1]

include::ql/functions/index.asciidoc[leveloffset=+1]

ifndef::asciidoctor[:leveloffset: 1]

include::schema.asciidoc[leveloffset=+1]

ifndef::asciidoctor[:leveloffset: 1]

include::query-tuning.asciidoc[leveloffset=+1]

ifndef::asciidoctor[:leveloffset: 1]

include::execution-plans.asciidoc[leveloffset=+1]
