[[query-operators]]
Operators
=========

[[query-operators-mathematical]]
== Mathematical operators ==

The mathematical operators are `+`, `-`, `*`, `/` and `%`, `^`.

[[query-operators-comparison]]
== Comparison operators ==

The comparison operators are `=`, `<>`, `<`, `>`, `<=`, `>=`, `IS NULL`, and `IS NOT NULL`.
See <<cypher-comparison>> on how they behave.

The operators `STARTS WITH`, `ENDS WITH` and `CONTAINS` can be used to search for a string value by its content.

[[query-operators-boolean]]
== Boolean operators ==
The boolean operators are `AND`, `OR`, `XOR`, `NOT`.

[[query-operators-string]]
== String operators ==

Strings can be concatenated using the `+` operator.
For regular expression matching the `=~` operator is used.

[[query-operators-collection]]
== Collection operators ==

Collections can be concatenated using the `+` operator.
To check if an element exists in a collection, you can use the +IN+ operator.

[[query-operators-property]]
== Property operators ==

[NOTE]
Since version 2.0, the previously existing property operators `?` and `!` have been removed.
This syntax is no longer supported.
Missing properties are now returned as +NULL+.
Please use `(NOT(has(<ident>.prop)) OR <ident>.prop=<value>)` if you really need the old behavior of the `?` operator.
-- Also, the use of `?` for optional relationships has been removed in favor of the newly introduced `OPTIONAL MATCH` clause.

