# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "ubuntu-11.04-amd64"
  
  config.vm.network :hostonly, "33.33.33.13"

  config.vm.provision :shell, :path => "share/ubuntu-provision.sh"
end
