[[community-contributing]]
Contributing to Neo4j
=====================

The Neo4j project is an Open Source effort to bring fast complex data storage and processing to life. Every form of help is highly appreciated by the community - and you are not alone, see <<contributors>>!

One crucial aspect of contributing to the Neo4j project is the <<cla>>.

In short: make sure to sign the CLA and send in the email, or the Neo4j project won't be able to accept your contribution.

Note that you can contribute to Neo4j also by contributing documentation or giving feedback on the current documentation.
Basically, at all the places where you can get help, there's also room for contributions.

If you want to contribute, there are some good areas to start with, especially for getting in contact with the community, <<community-support>>.

To document your efforts, we highly recommend to read <<community-docs>>.

:leveloffset: 2

include::cla.asciidoc[]

:leveloffset: 2

include::contribution-areas.asciidoc[]

:leveloffset: 2

include::docs.asciidoc[]

:leveloffset: 2

include::contributing-code.asciidoc[]

:leveloffset: 2

include::contributors.asciidoc[]

:leveloffset: 1


