= Neo4j: Graphs for Everyone =

https://neo4j.com[Neo4j] is the world's leading Graph Database. It is a high performance graph store with all the features expected of a mature and robust database, like a friendly query language and ACID transactions. The programmer works with a flexible network structure of nodes and relationships rather than static tables -- yet enjoys all the benefits of enterprise-quality database. For many applications, Neo4j offers orders of magnitude performance benefits compared to relational DBs.

Learn more on the https://neo4j.com[Neo4j website].

== Using Neo4j ==

Neo4j is available both as a standalone server, or an embeddable component. You can https://neo4j.com/download/[download] or http://console.neo4j.org[try online].

== Extending Neo4j ==

We encourage experimentation with Neo4j. You can build extensions to Neo4j, develop library or drivers atop the product, or make contributions directly to the product core. You'll need to sign a Contributor License Agreement in order for us to accept your patches.

NOTE: This GitHub repository contains mixed GPL and AGPL code. Our Community edition (in the link:community/[community/] directory) is GPLv3. Our Enterprise edition (link:enterprise/[enterprise/]) is differently licensed under the AGPLv3.

== Dependencies ==

Neo4j is built using http://maven.apache.org/[Apache Maven] version 3.3 and a recent version of supported VM. Bash and Make are also required. Note that maven needs more memory than the standard configuration, this can be achieved with `export MAVEN_OPTS="-Xmx512m"`.

OS X users need to have http://brew.sh/[Homebrew] installed.

=== With brew on OS X ===

  brew install maven

Please note that we do not support building Debian packages on OS X.

=== With apt-get on Ubuntu ===

  apt install maven openjdk-8-jdk

On top of that, to build Debian packages and Neo4j Desktop:

  apt install debhelper devscripts dos2unix dpkg make xmlstarlet
  # You will need a license for install4j, which is only needed for Neo4j Desktop
  curl -O http://download-keycdn.ej-technologies.com/install4j/install4j_linux_6_1_4.deb
  dpkg -i install4j_linux_6_1_4.deb

== Building Neo4j ==

Before you start running the unit and integration tests in the Neo4j Maven project on a Linux-like system, you should ensure your limit on open files is set to a reasonable value. You can test it with `ulimit -n`. We recommend you have a limit of at least 40K.

* A plain `mvn clean install` will only build the individual jar files.
* Test execution is, of course, part of the build.
* In case you just want the jars, without running tests, this is for you: `mvn clean install -DskipTests`.
* To build product packages, do `export PATH="bin:$PATH" && make clean all` in the packaging directory after building artifacts with Maven.
* To build the documentation see the https://github.com/neo4j/neo4j-documentation/[Neo4j documentation].
* If you are running into problems building on Windows you can try building Neo4j in a Ubuntu virtual machine.
* You may need to increase the memory available to Maven: `export MAVEN_OPTS="-Xmx512m"`.

== Running Neo4j ==

After running a `mvn clean install` cd into `packaging/standalone/target` and extract the version you want, then

  bin/neo4j start

in the extracted folder to start Neo4j on `localhost:7474`. On Windows you want to run

  bin\neo4j start

instead.

Or, if you are not interested in the tarballs and just want to run Neo4j you can instead run a `mvn clean install -DminimalBuild` and then cd into `community/server` and run

  mvn clean compile exec:java

to start Neo4j.

== Licensing ==

Neo4j Community Edition is an open source product licensed under GPLv3.

Neo4j Enterprise Edition expands the functionality of Community Edition with Enterprise-grade features.

Neo4j Enterprise consists of modules from Neo4j Community Edition and modules licensed under the Neo4j Sweden Software Licence in this repository, and other closed source components not present in this repository.
Please note that the Neo4j Sweden Software License is not open source.

When packaged as a binary, Enterprise Edition includes additional closed-source components _not available in this repository_ and requires a commercial license from Neo4j Sweden AB or one of its affiliates.
