== Cypher Refcard ==

This project creates a reference card for the Cypher Query Language.

=== Building ===

.Requirements
* Apache Maven version 3,
* Make,
* Python.

To build, issue this from the command line:

[source]
----
mvn clean package
----

The result will be available in the 'target/html5' directory.

There's also an experimental version optimized for printing.
You can enable it by appending `-Dprint` to the command line.
The result will be available in the 'target/html5/print' directory.
In essence, it shuts off the dynamic layout magic.

Please create issues on GitHub for errors or to request additions.
Pull requests are very welcome.

[NOTE]
We need a http://docs.neo4j.org/chunked/milestone/cla.html[CLA] from you in order 
to process any pull requests!

=== How it works ===

The main file for the content is 'src/cypher-refcard.asciidoc'.
It loads include files created from executing tests against Neo4j.
That's done in the Scala project in the 'neo4j-cypher-refcard-tests' directory,
The tests are located in 'neo4j-cypher-refcard-tests/src/test/scala/org/neo4j/cypher/docgen/refcard'


