[[configuration-settings]]
= Configuration Settings Reference

On this page you'll find the main configuration settings you can use with Neo4j.
They can be set in <<file-locations, _neo4j.conf_>> (for configuring the embedded database see <<tutorials-java-embedded-setup-config>>).

include::{importdir}/neo4j-config-docs-docs-jar/ops/configuration-attributes.asciidoc[]

== Configuring Bolt Connectors

Bolt Connectors are ports that accept connections via the Bolt Database Protocol, which is the protocol used by official Neo4j Driver Libraries.
You can configure Neo4j with one or more Bolt connectors.
This allows you, for instance, to have separate connectors for remote and local connections, with different encryption requirements.

If you are using Neo4j Embedded, you need to include the Bolt extension on your class path to enable Bolt.
See <<tutorials-java-embedded-bolt>> for details on how to open a Bolt connector from Neo4j Embedded.

Each connector has a unique key to identify it, denoted `{key}` in the listing below.

include::{importdir}/neo4j-config-docs-docs-jar/ops/configuration-bolt-connector-attributes.asciidoc[]


== Configuring HTTP Connectors

HTTP Connectors expose the Neo4j REST API and related HTTP resources.
At this time, you can configure at most one HTTP connector and one HTTPS connector.

HTTPS connectors are configured by setting a connector to require encryption.

include::{importdir}/neo4j-config-docs-docs-jar/ops/configuration-http-connector-attributes.asciidoc[]
