[[configuration-settings]]
= Configuration Settings Reference

This page documents Neo4j's configuration settings.
They can be set in <<file-locations, _neo4j.conf_>>.

include::{importdir}/neo4j-config-docs-docs-jar/ops/configuration-attributes.asciidoc[]

== Configuring Bolt Connectors

Bolt Connectors are ports that accept connections via the Bolt Database Protocol, which is the protocol used by official Neo4j Driver Libraries.
Neo4j can be configured with one or more Bolt connectors.
This allows separate connectors to be configured for remote and local connections, with different encryption requirements.

Each connector has a unique key to identify it, denoted `(bolt-connector-key)` in the listing below.

include::{importdir}/neo4j-config-docs-docs-jar/ops/configuration-bolt-connector-attributes.asciidoc[]

[CAUTION]
Using auto-generation of self-signed SSL certificates will not work if the Neo4j server has been configured with multiple connectors that bind to different IP addresses.
If you need to use multiple IP addresses, please configure certificates manually and use multi-host or wildcard certificates instead.

== Configuring HTTP Connectors

HTTP Connectors expose Neo4j's HTTP endpoints.
HTTPS connectors are configured by setting a connector to require encryption.
There must be exactly one HTTP connector and zero or one HTTPS connectors configured.

Each connector has a unique key to identify it, denoted `(http-connector-key)` in the listing below.

include::{importdir}/neo4j-config-docs-docs-jar/ops/configuration-http-connector-attributes.asciidoc[]

[CAUTION]
Using auto-generation of self-signed SSL certificates will not work if the Neo4j server has been configured with multiple connectors that bind to different IP addresses.
If you need to use multiple IP addresses, please configure certificates manually and use multi-host or wildcard certificates instead.
