/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [https://neo4j.com]
 *
 * This file is part of Neo4j.
 *
 * Neo4j is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.neo4j.gqlstatus;

import java.io.Serializable;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

/** Entries/fields in this "map" must be serializable* (Bolt must be able to parse them).
 * They must either be primitive types like int, or String
 * or collections that consists of such types (like _position)
 */
public class DiagnosticRecord implements Serializable {

    static final Map<String, Object> DEFAULT_DIAGNOSTIC_RECORD = new DiagnosticRecord().asMap();
    /**
     * Use by Bolt and Fabric/Composite for transfer the legacy message in
     * the inter cluster communication for being able to serve old clients
     * which relies on the legacy message.
     */
    public static final String LEGACY_MESSAGE_KEY = "__legacy_message";

    private final Map<String, Object> innerDiagnosticRecord;

    public static Builder from() {
        return new Builder();
    }

    public DiagnosticRecord(
            String severity,
            GqlClassification classification,
            int offset,
            int line,
            int column,
            Map<String, Object> statusParameters) {
        innerDiagnosticRecord = GqlStandardDiagnosticRecordProperty.asMap();
        withProperty(Neo4jDiagnosticRecordProperty.SEVERITY, severity);
        withProperty(
                Neo4jDiagnosticRecordProperty.POSITION,
                new Neo4jDiagnosticRecordProperty.Position(offset, line, column));
        withProperty(Neo4jDiagnosticRecordProperty.STATUS_PARAMETERS, statusParameters);
        withProperty(Neo4jDiagnosticRecordProperty.CLASSIFICATION, classification);
        withProperty(Neo4jDiagnosticRecordProperty.STATUS_PARAMETERS, statusParameters);
    }

    public DiagnosticRecord(String severity, GqlClassification classification, int offset, int line, int column) {
        innerDiagnosticRecord = GqlStandardDiagnosticRecordProperty.asMap();
        withProperty(Neo4jDiagnosticRecordProperty.SEVERITY, severity);
        withProperty(Neo4jDiagnosticRecordProperty.CLASSIFICATION, classification);
        withProperty(
                Neo4jDiagnosticRecordProperty.POSITION,
                new Neo4jDiagnosticRecordProperty.Position(offset, line, column));
    }

    public DiagnosticRecord() {
        innerDiagnosticRecord = GqlStandardDiagnosticRecordProperty.asMap();
    }

    /**
     * This method is only used by the {@link Builder} so the JsonMap is
     * sanitized.
     *
     * @param jsonMap The map generated by the Builder.
     */
    private DiagnosticRecord(Map<String, Object> jsonMap) {
        innerDiagnosticRecord = new HashMap<>(jsonMap);

        setDefaults(jsonMap, GqlStandardDiagnosticRecordProperty.asSet());
        setDefaults(jsonMap, Neo4jDiagnosticRecordProperty.asSet());
    }

    private void setDefaults(Map<String, Object> jsonMap, Set<DiagnosticRecordProperty<?>> properties) {
        for (var property : properties) {
            if (!jsonMap.containsKey(property.key())
                    && !property.disabled()
                    && property.defaultValue().isPresent()) {
                innerDiagnosticRecord.put(
                        property.key(),
                        property.serializeValue(property.defaultValue().get()));
            }
        }
    }

    public void setStatusParameters(Map<String, Object> statusParameters) {
        withProperty(Neo4jDiagnosticRecordProperty.STATUS_PARAMETERS, statusParameters);
    }

    boolean hasPosition() {
        return innerDiagnosticRecord.containsKey(Neo4jDiagnosticRecordProperty.POSITION.key());
    }

    Map<String, Integer> getPositionMap() {
        return (Map<String, Integer>) innerDiagnosticRecord.get(Neo4jDiagnosticRecordProperty.POSITION.key());
    }

    public Optional<String> getPosition() {
        var positionMap = innerDiagnosticRecord.getOrDefault(Neo4jDiagnosticRecordProperty.POSITION.key(), Map.of());
        if (positionMap instanceof Map<?, ?> position) {
            var entries = position.entrySet().stream()
                    .map(k -> "%s: %s".formatted(k.getKey(), k.getValue()))
                    .collect(Collectors.joining(" "));
            return Optional.of(entries);
        }
        return Optional.empty();
    }

    public void updatePosition(int offset, int line, int column) {
        withProperty(
                Neo4jDiagnosticRecordProperty.POSITION,
                new Neo4jDiagnosticRecordProperty.Position(offset, line, column));
    }

    @Override
    public int hashCode() {
        return innerDiagnosticRecord.hashCode();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DiagnosticRecord that = (DiagnosticRecord) o;
        return innerDiagnosticRecord.equals(that.innerDiagnosticRecord);
    }

    public Map<String, Object> asMap() {
        return Collections.unmodifiableMap(innerDiagnosticRecord);
    }

    public <T> DiagnosticRecord withProperty(DiagnosticRecordProperty<T> property, T value) {
        withProperty(innerDiagnosticRecord, property, value);
        return this;
    }

    public static <T> Map<String, Object> withProperty(
            Map<String, Object> map, DiagnosticRecordProperty<T> property, T value) {
        if (property.disabled() || property.isValueOmitted(value)) {
            return map;
        }

        Optional.ofNullable(value)
                .or(property::defaultValue)
                .ifPresent(dv -> map.put(property.key(), property.serializeValue(dv)));
        return map;
    }

    public static class Builder {
        private final Map<String, Object> innerDiagnosticRecord;

        private Builder() {
            innerDiagnosticRecord = GqlStandardDiagnosticRecordProperty.asMap();
        }

        public Builder atPosition(int offset, int line, int column) {
            return withProperty(
                    Neo4jDiagnosticRecordProperty.POSITION,
                    new Neo4jDiagnosticRecordProperty.Position(offset, line, column));
        }

        public Builder withClassification(GqlClassification classification) {
            return withProperty(Neo4jDiagnosticRecordProperty.CLASSIFICATION, classification);
        }

        public Builder withSeverity(String severity) {
            return withProperty(Neo4jDiagnosticRecordProperty.SEVERITY, severity);
        }

        public <T> Builder withProperty(DiagnosticRecordProperty<T> property, T value) {
            DiagnosticRecord.withProperty(innerDiagnosticRecord, property, value);
            return this;
        }

        public DiagnosticRecord build() {
            return new DiagnosticRecord(innerDiagnosticRecord);
        }
    }
}
