<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-front-end-parent</artifactId>
    <version>2026.07.0</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>neo4j-front-end-inspector</artifactId>
  <packaging>jar</packaging>
  <name>openCypher Front End Inspector</name>

  <description>Inspection tools for the openCypher front end</description>
  <url>http://components.neo4j.org/${project.artifactId}/${project.version}</url>

  <scm>
    <connection>scm:git:git://github.com/neo4j/neo4j.git</connection>
    <developerConnection>scm:git:git@github.com:neo4j/neo4j.git</developerConnection>
    <url>https://github.com/neo4j/neo4j</url>
  </scm>

  <properties>
    <dependency.analyse.strict>true</dependency.analyse.strict>
    <dependency.analyze.failOnWarning>true</dependency.analyze.failOnWarning>
    <moduleName>org.neo4j.cypher.internal.frontend.inspector</moduleName>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.lihaoyi</groupId>
      <artifactId>cask-util_${scala.binary.version}</artifactId>
      <version>0.11.3</version>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>com.lihaoyi</groupId>
          <artifactId>geny_${scala.binary.version}</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.lihaoyi</groupId>
      <artifactId>cask_${scala.binary.version}</artifactId>
      <version>0.11.3</version>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>com.lihaoyi</groupId>
          <artifactId>geny_${scala.binary.version}</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.undertow</groupId>
          <artifactId>undertow-core</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.lihaoyi</groupId>
      <artifactId>castor_${scala.binary.version}</artifactId>
      <version>0.3.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.lihaoyi</groupId>
      <artifactId>geny_${scala.binary.version}</artifactId>
      <version>1.1.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.lihaoyi</groupId>
      <artifactId>pprint_${scala.binary.version}</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.lihaoyi</groupId>
      <artifactId>scalatags_${scala.binary.version}</artifactId>
      <version>0.13.1</version>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>com.lihaoyi</groupId>
          <artifactId>geny_${scala.binary.version}</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>io.undertow</groupId>
      <artifactId>undertow-core</artifactId>
      <version>2.4.1.Final</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>neo4j-ast</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>neo4j-common</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>neo4j-expressions</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>neo4j-front-end</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>neo4j-gql-status</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>neo4j-internal-notifications</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>neo4j-util</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
