#!/bin/sh

### BEGIN INIT INFO
# Provides:          neo4j
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Neo4j Graph Database server
# Description:       Neo4j is a Graph Database, which is a compelling
#                    alternative to an RDBMS. http://www.neo4j.org
### END INIT INFO

# Author: Julian Simpson <julian.simpson@neotechnology.com>
#
# Copyright (c) 2002-2018 "Neo Technology,"

# Network Engine for Objects in Lund AB [http://neotechnology.com]
#
# This file is part of Neo4j.
#
# Neo4j is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME=neo4j
DAEMON=/usr/bin/$NAME
PIDDIR=/var/run/${NAME}
PIDFILE=${PIDDIR}/neo4j.pid
SCRIPTNAME=/etc/init.d/${NAME}

[ -x "$DAEMON" ] || exit 0
[ -r /etc/default/$NAME ] && . /etc/default/$NAME
[ -n "${NEO_USER}" ] || NEO_USER=$NAME

. /lib/lsb/init-functions

do_start()
{
  do_ulimit
  [ -d "${PIDDIR}" ] || mkdir -p "${PIDDIR}"
  chown "${NEO_USER}:" "${PIDDIR}"

  start-stop-daemon --chuid ${NEO_USER} --start --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON -- start
}

do_stop()
{
  $DAEMON stop
}

do_ulimit()
{
  if [ -n "${NEO4J_ULIMIT_NOFILE}" ]; then
    ulimit -n "${NEO4J_ULIMIT_NOFILE}"
  fi
}

case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  status)
    status_of_proc -p $PIDFILE "$DAEMON" "$NAME"
    ;;
  restart|force-reload)
    do_stop && do_start
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
    exit 3
    ;;
esac
