[[tutorials-java-embedded-logging]]
= Controlling logging

:javadoc-graphdatabasefactory: javadocs/org/neo4j/graphdb/factory/GraphDatabaseFactory.html
:javadoc-slf4jlogprovider: javadocs/org/neo4j/logging/slf4j/Slf4jLogProvider.html
:javadoc-neo4jlogging: javadocs/org/neo4j/logging

[abstract]
--
To control logging in Neo4j embedded, use the Neo4j embedded logging framework.
--

Neo4j embedded provides logging via its own +link:{javadoc-neo4jlogging}/Log.html[org.neo4j.logging.Log]+ layer, and does not natively use any existing Java logging framework.
All logging events produced by Neo4j have a name, a level and a message.
The name is a FQCN (fully qualified class name).

[[log-levels]]
Neo4j uses the following log levels:
[cols='1m,5']
|===
|ERROR | For serious errors that are almost always fatal
|WARN  | For events that are serious, but not fatal
|INFO  | Informational events
|DEBUG | Debugging events
|===

[[enable-embedded-logging]]
To enable logging, an implementation of +link:{javadoc-neo4jlogging}/LogProvider.html[org.neo4j.logging.LogProvider]+
must be provided to the +link:{javadoc-graphdatabasefactory}[GraphDatabaseFactory]+,
as follows:

[snippet,java]
----
component=neo4j-examples
source=org/neo4j/examples/EmbeddedNeo4jWithCustomLogging.java
classifier=sources
tag=startDbWithLogProvider
----

Neo4j also includes a binding for SLF4J, which is available in the `neo4j-slf4j` library jar.
This can be obtained via Maven:

["source","xml","unnumbered","2",presubs="attributes"]
--------------------------------------------
<project>
...
 <dependencies>
  <dependency>
   <groupId>org.neo4j</groupId>
   <artifactId>neo4j-slf4j</artifactId>
   <version>{neo4j-version}</version>
  </dependency>
  <dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>{slf4j-version}</version>
  </dependency>
  ...
 </dependencies>
...
</project>
--------------------------------------------

To use this binding, simply pass an instance of +link:{javadoc-slf4jlogprovider}[org.neo4j.logging.slf4j.Slf4jLogProvider]+
to the +link:{javadoc-graphdatabasefactory}[GraphDatabaseFactory]+,
as follows:

[snippet,java]
----
component=neo4j-examples
source=org/neo4j/examples/EmbeddedNeo4jWithSLF4JLogging.java
classifier=sources
tag=startDbWithSlf4jLogProvider
----

All log output can then be controlled via SLF4J configuration.
