[[tutorials-java-embedded-new-index]]
User database with indexes
==========================

You have a user database, and want to retrieve users by name using indexes.

[TIP]
The source code used in this example is found here:
https://github.com/neo4j/neo4j/blob/{neo4j-git-tag}/community/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4jWithNewIndexing.java[EmbeddedNeo4jWithNewIndexing.java]

To begin with, we start the database server:

[snippet,java]
----
component=neo4j-examples
source=org/neo4j/examples/EmbeddedNeo4jWithNewIndexing.java
classifier=sources
tag=startDb
----

Then we have to configure the database to index users by name.
This only needs to be done once.

NOTE: Schema changes and data changes are not allowed in the same transaction. Each transaction must either change the schema or the data, but not both.

[snippet,java]
----
component=neo4j-examples
source=org/neo4j/examples/EmbeddedNeo4jWithNewIndexing.java
classifier=sources
tag=createIndex
----

Indexes are populated asynchronously when they are first created.
It is possible to use the core API to wait for index population to complete:

[snippet,java]
----
component=neo4j-examples
source=org/neo4j/examples/EmbeddedNeo4jWithNewIndexing.java
classifier=sources
tag=wait
----

It's time to add the users:

[snippet,java]
----
component=neo4j-examples
source=org/neo4j/examples/EmbeddedNeo4jWithNewIndexing.java
classifier=sources
tag=addUsers
----

NOTE: Please read <<tutorials-java-embedded-resource-iteration>> on how to properly close `ResourceIterators` returned from index lookups.

And here's how to find a user by id:

[snippet,java]
----
component=neo4j-examples
source=org/neo4j/examples/EmbeddedNeo4jWithNewIndexing.java
classifier=sources
tag=findUsers
----

When updating the name of a user, the index is updated as well:

[snippet,java]
----
component=neo4j-examples
source=org/neo4j/examples/EmbeddedNeo4jWithNewIndexing.java
classifier=sources
tag=updateUsers
----

When deleting a user, it is automatically removed from the index:

[snippet,java]
----
component=neo4j-examples
source=org/neo4j/examples/EmbeddedNeo4jWithNewIndexing.java
classifier=sources
tag=deleteUsers
----

In case we change our data model, we can drop the index as well:

[snippet,java]
----
component=neo4j-examples
source=org/neo4j/examples/EmbeddedNeo4jWithNewIndexing.java
classifier=sources
tag=dropIndex
----

