[[tutorial-traversal]]
The Traversal Framework
=======================


The link:javadocs/org/neo4j/graphdb/traversal/package-summary.html[Neo4j Traversal API] is a callback based, lazily executed way of specifying desired movements through a graph in Java.
Some traversal examples are collected under <<tutorials-java-embedded-traversal>>. 

You can also use <<cypher-query-lang, The Cypher Query Language>> as a powerful declarative way to query the graph.

[[tutorial-traversal-concepts]]
== Main concepts ==

Here follows a short explanation of all different methods that can modify or add to a traversal description.

* _Pathexpanders_ -- define what to traverse, typically in terms of relationship direction and type.
* _Order_ -- for example depth-first or breadth-first.
* _Uniqueness_ -- visit nodes (relationships, paths) only once.
* _Evaluator_ -- decide what to return and whether to stop or continue traversal beyond the current position. 
* _Starting nodes_ where the traversal will begin.

["dot", "graphdb-traversal-description.svg", "meta"]
----
"Traversal Description" [fillcolor="NODEHIGHLIGHT"]
Uniqueness -> "Traversal Description" [label="avoid duplicates"]
Evaluator -> "Traversal Description" [label="return and prune policy"]
Order -> "Traversal Description" [label="where to go next"]
PathExpander -> "Traversal Description" [label="what to traverse"]

"Depth First" [TEXTNODE]
"Breadth First" [TEXTNODE]
"Relationship Type" [TEXTNODE]
"Direction" [TEXTNODE]
"Unique Nodes" [TEXTNODE]
"Unique Relationships" [TEXTNODE]
"Unique Paths" [TEXTNODE]
"None" [TEXTNODE]
"Include/Exclude" [TEXTNODE]
"Prune/Continue" [TEXTNODE]

"Depth First" -> Order [dir="back"]
"Breadth First" -> Order [dir="back"]

PathExpander -> "Relationship Type"
"Direction" -> PathExpander [dir="back"]

"Unique Nodes" -> Uniqueness [dir="back"]
"Unique Relationships" -> Uniqueness [dir="back"]
"Unique Paths" -> Uniqueness [dir="back"]
"None" -> Uniqueness [dir="back"]

"Include/Exclude" -> Evaluator [dir="back"]
Evaluator -> "Prune/Continue"

Traverser [fillcolor="NODE2HIGHLIGHT"]
"A Node" [fillcolor="NODEHIGHLIGHT"]
"Traversal Description" -> Traverser [dir="back" label="applies" weight=3.0]
"A Node" -> Traverser [label="starting point of"]
Traverser -> Paths [label="result as"]
Traverser -> Nodes [label="result as"]
Traverser -> Relationships [label="result as"]

{ rank="same"; Traverser; "A Node" }
----

See <<tutorial-traversal-java-api>> for more details.

[[tutorial-traversal-java-api]]
== Traversal Framework Java API ==

The traversal framework consists of a few main interfaces in addition to +Node+ and +Relationship+: +TraversalDescription+, +Evaluator+, +Traverser+ and +Uniqueness+ are the main ones.
The +Path+ interface also has a special purpose in traversals, since it is used to represent a position in the graph when evaluating that position.
Furthermore the +PathExpander+ (replacing +RelationshipExpander+ and +Expander+) interface is central to traversals, but users of the API rarely need to implement it.
There are also a set of interfaces for advanced use, when explicit control over the traversal order is required: +BranchSelector+, +BranchOrderingPolicy+ and +TraversalBranch+.

=== TraversalDescription ===

The link:javadocs/org/neo4j/graphdb/traversal/TraversalDescription.html[+TraversalDescription+] is the main interface used for defining and initializing traversals.
It is not meant to be implemented by users of the traversal framework, but rather to be provided by the implementation of the traversal framework as a way for the user to describe traversals.
+TraversalDescription+ instances are immutable and its methods returns a new +TraversalDescription+ that is modified compared to the object the method was invoked on with the arguments of the method.

==== Relationships ====

Adds a relationship type to the list of relationship types to traverse.
By default that list is empty and it means that it will traverse _all relationships_, regardless of type.
If one or more relationships are added to this list _only the added_ types will be traversed.
There are two methods, one link:javadocs/org/neo4j/graphdb/traversal/TraversalDescription.html#relationships[including direction] and another one link:javadocs/org/neo4j/graphdb/traversal/TraversalDescription.html#relationships[excluding direction], where the latter traverses relationships in link:javadocs/org/neo4j/graphdb/Direction.html#BOTH[both directions].


=== Evaluator ===

link:javadocs/org/neo4j/graphdb/traversal/Evaluator.html[+Evaluator+]s are used for deciding, at each position (represented as a +Path+): should the traversal continue, and/or should the node be included in the result.
Given a +Path+, it asks for one of four actions for that branch of the traversal:

* +Evaluation.INCLUDE_AND_CONTINUE+: Include this node in the result and continue the traversal
* +Evaluation.INCLUDE_AND_PRUNE+: Include this node in the result, but don't continue the traversal
* +Evaluation.EXCLUDE_AND_CONTINUE+: Exclude this node from the result, but continue the traversal
* +Evaluation.EXCLUDE_AND_PRUNE+: Exclude this node from the result and don't continue the traversal

More than one evaluator can be added. Note that evaluators will be called for all positions the traverser encounters, even for the start node.

=== Traverser ===

The link:javadocs/org/neo4j/graphdb/traversal/Traverser.html[+Traverser+] object is the result of invoking link:javadocs/org/neo4j/graphdb/traversal/TraversalDescription.html#traverse(org.neo4j.graphdb.Node)[+traverse()+] of a TraversalDescription object.
It represents a traversal positioned in the graph, and a specification of the format of the result.
The actual traversal is performed lazily each time the +next()+-method of the iterator of the +Traverser+ is invoked.

=== Uniqueness ===

Sets the rules for how positions can be revisited during a traversal as stated in link:javadocs/org/neo4j/graphdb/traversal/Uniqueness.html[+Uniqueness+].
Default if not set is link:javadocs/org/neo4j/graphdb/traversal/Uniqueness.html#NODE_GLOBAL[+NODE_GLOBAL+].

A Uniqueness can be supplied to the TraversalDescription to dictate under what circumstances a traversal may revisit the same position in the graph. The various uniqueness levels that can be used in Neo4j are:

* +NONE+: Any position in the graph may be revisited.
* +NODE_GLOBAL+ uniqueness: No node in the entire graph may be visited more than once. This could potentially consume a lot of memory since it requires keeping an in-memory data structure remembering all the visited nodes.
* +RELATIONSHIP_GLOBAL+ uniqueness: no relationship in the entire graph may be visited more than once. For the same reasons as +NODE_GLOBAL+ uniqueness, this could use up a lot of memory. But since graphs typically have a larger number of relationships than nodes, the memory overhead of this uniqueness level could grow even quicker.
* +NODE_PATH+ uniqueness: A node may not occur previously in the path reaching up to it.
* +RELATIONSHIP_PATH+ uniqueness: A relationship may not occur previously in the path reaching up to it.
* +NODE_RECENT+ uniqueness: Similar to +NODE_GLOBAL+ uniqueness in that there is a global collection of visited nodes each position is checked against. This uniqueness level does however have a cap on how much memory it may consume in the form of a collection that only contains the most recently visited nodes. The size of this collection can be specified by providing a number as the second argument to the TraversalDescription.uniqueness()-method along with the uniqueness level.
* +RELATIONSHIP_RECENT+ uniqueness: Works like +NODE_RECENT+ uniqueness, but with relationships instead of nodes.


==== Depth First / Breadth First ====

These are convenience methods for setting preorder http://en.wikipedia.org/wiki/Depth-first_search[depth-first]/ http://en.wikipedia.org/wiki/Breadth-first_search[breadth-first] +BranchSelector+|+ordering+ policies.
The same result can be achieved by calling the link:javadocs/org/neo4j/graphdb/traversal/TraversalDescription.html#order[+order+] method with ordering policies from link:javadocs/org/neo4j/graphdb/traversal/BranchOrderingPolicies.html[+BranchOrderingPolicies+], or to write your own +BranchSelector+/+BranchOrderingPolicy+ and pass in.

=== Order -- How to move through branches? ===

A more generic version of depthFirst/breadthFirst methods in that it allows an arbitrary link:javadocs/org/neo4j/graphdb/traversal/BranchOrderingPolicy.html[+BranchOrderingPolicy+] to be injected into the description.


=== BranchSelector ===

A +BranchSelector+/+BranchOrderingPolicy+ is used for selecting which branch of the traversal to attempt next.
This is used for implementing traversal orderings.
The traversal framework provides a few basic ordering implementations:

* +BranchOrderingPolicies.PREORDER_DEPTH_FIRST+: Traversing depth first, visiting each node before visiting its child nodes.
* +BranchOrderingPolicies.POSTORDER_DEPTH_FIRST+: Traversing depth first, visiting each node after visiting its child nodes.
* +BranchOrderingPolicies.PREORDER_BREADTH_FIRST+: Traversing breadth first, visiting each node before visiting its child nodes.
* +BranchOrderingPolicies.POSTORDER_BREADTH_FIRST+: Traversing breadth first, visiting each node after visiting its child nodes.

NOTE: Please note that breadth first traversals have a higher memory overhead than depth first traversals.

++BranchSelector++s carries state and hence needs to be uniquely instantiated for each traversal.
Therefore it is supplied to the +TraversalDescription+ through a +BranchOrderingPolicy+ interface, which is a factory of +BranchSelector+ instances.

A user of the Traversal framework rarely needs to implement his own +BranchSelector+ or +BranchOrderingPolicy+, it is provided to let graph algorithm implementors provide their own traversal orders.
The Neo4j Graph Algorithms package contains for example a +BestFirst+ order +BranchSelector+/+BranchOrderingPolicy+ that is used in BestFirst search algorithms such as A* and Dijkstra.

==== BranchOrderingPolicy ====

A factory for creating ++BranchSelector++s to decide in what order branches are returned (where a branch's position is represented as a link:javadocs/org/neo4j/graphdb/Path.html[+Path+] from the start node to the current node).
Common policies are link:javadocs/org/neo4j/graphdb/traversal/TraversalDescription.html#depthFirst()[+depth-first+] and link:javadocs/org/neo4j/graphdb/traversal/TraversalDescription.html#breadthFirst()[+breadth-first+] and that's why there are convenience methods for those.
For example, calling link:javadocs/org/neo4j/graphdb/traversal/TraversalDescription.html#depthFirst()[+TraversalDescription#depthFirst()+] is equivalent to:

[source,java]
----
description.order( BranchOrderingPolicies.PREORDER_DEPTH_FIRST );
----

==== TraversalBranch ====

An object used by the BranchSelector to get more branches from a certain branch. In essence these are a composite of a Path and a RelationshipExpander that can be used to get new link:javadocs/org/neo4j/graphdb/traversal/TraversalBranch.html[+TraversalBranch+]es from the current one.

=== Path ===

A link:javadocs/org/neo4j/graphdb/Path.html[+Path+] is a general interface that is part of the Neo4j API.
In the traversal API of Neo4j the use of Paths are twofold.
Traversers can return their results in the form of the Paths of the visited positions in the graph that are marked for being returned.
Path objects are also used in the evaluation of positions in the graph, for determining if the traversal should continue from a certain point or not, and whether a certain position should be included in the result set or not.

=== PathExpander/RelationshipExpander ===

The traversal framework use ++PathExpander++s (replacing +RelationshipExpander+) to discover the relationships that should be followed from a particular path to further branches in the traversal.

=== Expander ===

A more generic version of relationships where a +RelationshipExpander+ is injected, defining all relationships to be traversed for any given node.

The +Expander+ interface is an extension of the +RelationshipExpander+ interface that makes it possible to build customized versions of an +Expander+.
The implementation of +TraversalDescription+ uses this to provide methods for defining which relationship types to traverse, this is the usual way a user of the API would define a +RelationshipExpander+ -- by building it internally in the +TraversalDescription+.

All the RelationshipExpanders provided by the Neo4j traversal framework also implement the Expander interface.
For a user of the traversal API it is easier to implement the PathExpander/RelationshipExpander interface, since it only contains one method -- the method for getting the relationships from a path/node, the methods that the Expander interface adds are just for building new Expanders.

:leveloffset: 3

include::{importdir}/neo4j-examples-docs-jar/dev/examples/how-to-use-the-traversal-framework.asciidoc[]

