[[tutorials-java-unit-testing]]
Basic unit testing
==================

The basic pattern of unit testing with Neo4j is illustrated by the following example.

To access the Neo4j testing facilities you should have the `neo4j-kernel` 'tests.jar' together with the `neo4j-io` 'tests.jar' on the classpath during tests.
You can download them from Maven Central: http://search.maven.org/#search|ga|1|g%3A%22org.neo4j%22%20AND%20a%3A%22neo4j-kernel%22[org.neo4j:neo4j-kernel] and http://search.maven.org/#search|ga|1|g%3A%22org.neo4j%22%20AND%20a%3A%22neo4j-io%22[org.neo4j:neo4j-io].

Using Maven as a dependency manager you would typically add this dependency together with JUnit and Hamcrest like so:

.Maven dependency
["source","xml","unnumbered","2",presubs="attributes"]
--------------------------------------------
<project>
...
 <dependencies>
  <dependency>
   <groupId>org.neo4j</groupId>
   <artifactId>neo4j-kernel</artifactId>
   <version>{neo4j-version}</version>
   <type>test-jar</type>
   <scope>test</scope>
  </dependency>
  <dependency>
   <groupId>org.neo4j</groupId>
   <artifactId>neo4j-io</artifactId>
   <version>{neo4j-version}</version>
   <type>test-jar</type>
   <scope>test</scope>
  </dependency>
  <dependency>
   <groupId>junit</groupId>
   <artifactId>junit</artifactId>
   <version>4.12</version>
   <scope>test</scope>
  </dependency>
  <dependency>
   <groupId>org.hamcrest</groupId>
   <artifactId>hamcrest-all</artifactId>
   <version>1.3</version>
   <scope>test</scope>
  </dependency>
  ...
 </dependencies>
...
</project>
--------------------------------------------

Observe that the `<type>test-jar</type>` is crucial.
Without it you would get the common `neo4j-kernel` jar, not the one containing the testing facilities.

With that in place, we're ready to code our tests.

[TIP]
For the full source code of this example see:
https://github.com/neo4j/neo4j/blob/{neo4j-git-tag}/community/embedded-examples/src/test/java/org/neo4j/examples/Neo4jBasicDocTest.java[Neo4jBasicDocTest.java]


Before each test, create a fresh database:

[snippet,java]
----
component=neo4j-examples
source=org/neo4j/examples/Neo4jBasicDocTest.java
classifier=test-sources
tag=beforeTest
----

After the test has executed, the database should be shut down:

[snippet,java]
----
component=neo4j-examples
source=org/neo4j/examples/Neo4jBasicDocTest.java
classifier=test-sources
tag=afterTest
----

During a test, create nodes and check to see that they are there, while enclosing write operations in a transaction.

[snippet,java]
----
component=neo4j-examples
source=org/neo4j/examples/Neo4jBasicDocTest.java
classifier=test-sources
tag=unitTest
----

If you want to set configuration parameters at database creation, it's done like this:

[snippet,java]
----
component=neo4j-examples
source=org/neo4j/examples/Neo4jBasicDocTest.java
classifier=test-sources
tag=startDbWithConfig
----


