/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [https://neo4j.com]
 *
 * This file is part of Neo4j.
 *
 * Neo4j is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.neo4j.cypher.cucumber.synthesise.generator

import org.neo4j.cypher.cucumber.synthesise.CucumberSalad
import org.neo4j.cypher.cucumber.synthesise.generator.Filter.containsAst
import org.neo4j.cypher.cucumber.synthesise.generator.Filter.doNotContainAst
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.AssertResults
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.Comment
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.CreateCsvFile
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.HavingExecuted
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.QueryExecution
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.RecordedScenario
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.RecordedStep
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.SetupExecution
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.SideEffects
import org.neo4j.cypher.cucumber.synthesise.glue.scenario.TestExecution
import org.neo4j.cypher.internal.ast.Search
import org.neo4j.cypher.internal.ast.SubqueryCall.InTransactionsParameters
import org.neo4j.cypher.internal.expressions.PatternPart

import java.nio.file.Paths
import java.util.concurrent.atomic.AtomicLong

import scala.collection.View
import scala.util.Random

class CombineUncommitted(val args: CucumberSalad.Ingredients) extends ScenarioGenerator with ScenarioRenderer {
  override val name = "combine-uncommitted"
  private val counter = new AtomicLong(0)

  override def filter: Filter = super.filter
    .steps[RecordedStep](_.forall {
      case _: SideEffects | _: QueryExecution | _: AssertResults | _: CreateCsvFile => true
      case _                                                                        => false
    })
    .steps[RecordedStep](_.dropWhile(s => !s.isInstanceOf[TestExecution]).forall(s => !s.isInstanceOf[SetupExecution]))
    .testQueries(_.exists(containsAst[PatternPart]))
    // SEARCH hits eventually-consistent indexes that never see uncommitted writes.
    .testQueries(_.forall(doNotContainAst[Search]))
    .queries[QueryExecution](_.forall(doNotContainAst[InTransactionsParameters]))

  def generateScenarios(filteredScenarios: View[RecordedScenario]): IterableOnce[GeneratedScenario] = {
    filteredScenarios
      .groupBy(setupQueries)
      .toSeq
      .filter { case (_, scenarios) => scenarios.size > 1 }
      .sortBy { case (_, scenarios) => -scenarios.size }
      .map { case (setup, scenarios) => generateScenario(setup, scenarios.toSeq) }
  }

  private def setupQueries(scenario: RecordedScenario): Seq[String] = scenario.steps
    .collect { case setup: SetupExecution => setup.cypher }

  private def generateScenario(setup: Seq[String], scenarios: Seq[RecordedScenario]): GeneratedScenario = {
    val setupSteps = setup.map(query => HavingExecuted(query))
    val cleanupSteps = setupSteps
      .filter(e => Filter.isNotCommand(args.parser.parse(e.cypher)))
      .prepended(HavingExecuted("MATCH (n) DETACH DELETE n // Generated cleanup"))
    val testSteps = for {
      scenario <- new Random(args.rand.seed()).shuffle(scenarios)
      isRead = Filter(args.parser).testsReadQueries.build.apply(scenario)
      steps = scenario.steps.filterNot(_.isInstanceOf[SetupExecution])
      step <- Seq(Comment(s"From ${scenario.source}")) ++
        steps ++
        (if (!isRead) cleanupSteps else Seq.empty)
    } yield step
    val allSteps = Uncommitted.transformSteps(args.parser, setupSteps ++ testSteps)
    val count = counter.incrementAndGet()
    val name = s"Generated scenario $count"
    val featurePath = Paths.get(s"$GeneratedScenario$count.feature")
    val comment = "Generated by combining read scenarios with the same setup"
    val tags = scenarios.foldLeft(Set.empty[String]) { case (acc, s) => acc.concat(s.tags) }
    GeneratedScenario(name, allSteps, featurePath, comment, tags)
  }
}
