# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "windows-2008R2-amd64"
  
  config.vm.forward_port "neo4j-server", 7474, 27474

  #config.vm.provision :shell, :path => "install-java.sh"
end
