#!/bin/sh

### BEGIN INIT INFO
# Provides:          neo4j
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Neo4j Graph Database server
# Description:       Neo4j is a Graph Database, which is a compelling
#                    alternative to an RDBMS. http://www.neo4j.org
### END INIT INFO

# Author: Julian Simpson <julian.simpson@neotechnology.com>
#
# Copyright (c) 2002-2018 "Neo Technology,"

# Network Engine for Objects in Lund AB [http://neotechnology.com]
#
# This file is part of Neo4j.
#
# Neo4j is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Neo4j Graph Database"
NAME=neo4j
DAEMON=/var/lib/$NAME/bin/$NAME
DAEMON_ARGS="start"
PIDFILE=/var/lib/${NAME}/data/neo4j-service.pid
SCRIPTNAME=/etc/init.d/$NAME-service

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
. /lib/lsb/init-functions

do_start()
{
	do_ulimit
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	start-stop-daemon --chuid ${NEO_USER} --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
		|| return 1
	start-stop-daemon --chuid ${NEO_USER} --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
		$DAEMON_ARGS \
		|| return 2
}

do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	: ${NEO4J_SHUTDOWN_TIMEOUT:=30}
	: ${NEO4J_SHUTDOWN_KILL:="true"}
	shutdown_verb="KILL"
	[ "$NEO4J_SHUTDOWN_KILL" != "true" ] && shutdown_verb="TERM"

	start-stop-daemon --chuid ${NEO_USER} --stop --quiet --retry=TERM/${NEO4J_SHUTDOWN_TIMEOUT}/${shutdown_verb}/5 --pidfile $PIDFILE
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2

	start-stop-daemon --chuid ${NEO_USER} --stop --quiet --oknodo --retry=0/${NEO4J_SHUTDOWN_TIMEOUT}/${shutdown_verb}/5 --exec $DAEMON
	[ "$?" = 2 ] && return 2
	# Many daemons don't delete their pidfiles when they exit.
	rm -f $PIDFILE
	return "$RETVAL"
}

do_ulimit()
{
  if [ -n "${NEO4J_ULIMIT_NOFILE}" ]; then
    ulimit -n "${NEO4J_ULIMIT_NOFILE}"
  fi
}

# Ensure that the NEO_USER is set to a useful default.
[ -n "${NEO_USER}" ] || NEO_USER=$NAME

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  status)
       status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $?
       ;;
  restart|force-reload)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
	  # Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
