/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [https://neo4j.com]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.neo4j.cypher.internal.frontend.phases;

public enum SyntaxUsageMetricKey {
    GPM_SHORTEST("GPM_SHORTEST"),
    LEGACY_SHORTEST("LEGACY_SHORTEST"),
    COLLECT_SUBQUERY("COLLECT_SUBQUERY"),
    COUNT_SUBQUERY("COUNT_SUBQUERY"),
    EXISTS_SUBQUERY("EXISTS_SUBQUERY"),
    QUANTIFIED_PATH_PATTERN("QUANTIFIED_PATH_PATTERN"),
    REPEATABLE_ELEMENTS("REPEATABLE_ELEMENTS"),
    LET_CLAUSE("LET_CLAUSE"),
    FILTER_CLAUSE("FILTER_CLAUSE"),
    IMPORTING_WITH_SUBQUERY("IMPORTING_WITH_SUBQUERY"),
    IMPORTING_WITH_SUBQUERY_CORRELATED("IMPORTING_WITH_SUBQUERY_CORRELATED"),
    IMPORTING_WITH_SUBQUERY_UNCORRELATED("IMPORTING_WITH_SUBQUERY_UNCORRELATED"),
    SCOPE_CLAUSE_SUBQUERY("SCOPE_CLAUSE_SUBQUERY"),
    CONDITIONAL_QUERY("CONDITIONAL_QUERY"),
    NEXT_STATEMENT("NEXT_STATEMENT"),
    SEARCH_WITHOUT_FILTERS("SEARCH_WITHOUT_FILTERS"),
    SEARCH_WITH_FILTERS("SEARCH_WITH_FILTERS"),
    LOAD_CSV("LOAD_CSV"),
    LOAD_CSV_CALL_IN_TX("LOAD_CSV_CALL_IN_TX"),
    LOAD_CSV_CALL_IN_TX_CONCURRENT("LOAD_CSV_CALL_IN_TX_CONCURRENT"),
    ALTER_CURRENT_GRAPH_TYPE("ALTER_CURRENT_GRAPH_TYPE"),
    SHOW_CURRENT_GRAPH_TYPE("SHOW_CURRENT_GRAPH_TYPE"),
    CREATE_AUTH_RULE("CREATE_AUTH_RULE"),
    RENAME_AUTH_RULE("RENAME_AUTH_RULE"),
    ALTER_AUTH_RULE("ALTER_AUTH_RULE"),
    DROP_AUTH_RULE("DROP_AUTH_RULE"),
    SHOW_AUTH_RULES("SHOW_AUTH_RULES"),
    ACYCLIC_PATH_MODE("ACYCLIC_PATH_MODE"),
    GPM_SHORTEST_WITH_EXPLICIT_PATH_MODE("GPM_SHORTEST_WITH_EXPLICIT_PATH_MODE"),
    CREATE_USER_TAGS("CREATE_USER_TAGS"),
    ALTER_USER_TAGS("ALTER_USER_TAGS"),
    ALTER_USERS_TAGS("ALTER_USERS_TAGS"),
    GROUP_BY("GROUP_BY"),
    GROUP_BY_EXPLICIT("GROUP_BY_EXPLICIT"),
    GROUP_BY_ALL("GROUP_BY_ALL"),
    GROUP_BY_NONE("GROUP_BY_NONE");

    public final String key;

    SyntaxUsageMetricKey(String key) {
        this.key = key;
    }
}
