#!/usr/bin/env bash
set -eu

if [ "$1" == "-version" ]; then
  echo "java version \"1.8.0_51\"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)"
  exit 0
fi

if [[ "${HARNESS_JAVA_SLEEP:-}" ]]; then
  sleep "${HARNESS_JAVA_SLEEP}"
fi

echo -n "$@" >../java-args
