= NEO4J(1)
:author: The Neo4j Team

== NAME
neo4j - Neo4j Server control

[[neo4j-manpage]]
== SYNOPSIS

*neo4j* <command>

[[neo4j-manpage-description]]
== DESCRIPTION

Neo4j is a graph database, perfect for working with highly connected data.
The `neo4j` command is used to control the Neo4j Server.

The preferred way to install Neo4j on Linux systems is by using prebuilt installation packages.
For information regarding Windows, see http://neo4j.com/docs/stable/powershell.html.

[[neo4j-manpage-commands]]
== COMMANDS

*console*::
  Start the server as an application, running as a foreground process. Stop the server using `CTRL-C`.

*start*::
  Start server as daemon, running as a background process.

*stop*::
  Stops a running daemonized server.

*restart*::
  Restarts the server.

*status*::
  Current running state of the server.

*info*::
  Displays configuration information, such as the current NEO4J_HOME and CLASSPATH.

[[neo4j-manpage-files]]
== FILES

*conf/neo4j-server.properties*::
  Server configuration.

*conf/neo4j-wrapper.conf*::
  Configuration for service wrapper.

*conf/neo4j.properties*::
  Tuning configuration for the database.


