= NEO4J-INSTALLER(1)
:author: The Neo4j Team

== NAME
neo4j-installer - Neo4j Server installation and removal

[[neo4j-installer-manpage]]
== SYNOPSIS

*neo4j-installer* <command>

[[neo4j-installer-manpage-description]]
== DESCRIPTION

Neo4j is a graph database, perfect for working with highly connected data.

The preferred way to install Neo4j on Linux systems is by using prebuilt installation packages, but there's also the possibility to use the `neo4j-installer` command to install or remove it as a system service.
For information regarding Windows, see below.

Use the `neo4j` command to control the Neo4j Server.

For information regarding Windows, see http://neo4j.com/docs/stable/powershell.html.

[[neo4j-installer-manpage-commands]]
== COMMANDS

*install*::
  Installs the server as a platform-appropriate system service.

*remove*::
  Uninstalls the system service.

[[neo4j-installer-manpage-files]]
== FILES

*conf/neo4j-server.properties*::
  Server configuration.

*conf/neo4j-wrapper.conf*::
  Configuration for service wrapper.

*conf/neo4j.properties*::
  Tuning configuration for the database.


