<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.neo4j</groupId>
    <artifactId>parent</artifactId>
    <version>2026.07.0</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>
  <artifactId>neo4j-procedure-api</artifactId>

  <packaging>jar</packaging>
  <name>Neo4j - Procedure API</name>
  <description>Procedure API for Neo4j.</description>
  <url>http://components.neo4j.org/${project.artifactId}/${project.version}</url>

  <scm>
    <connection>scm:git:git://github.com/neo4j/neo4j.git</connection>
    <developerConnection>scm:git:git@github.com:neo4j/neo4j.git</developerConnection>
    <url>https://github.com/neo4j/neo4j</url>
  </scm>

  <properties>
    <moduleName>org.neo4j.procedure.api</moduleName>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>annotations</artifactId>
    </dependency>
    <dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>neo4j-collections</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>neo4j-graphdb-api</artifactId>
      <version>${project.version}</version>
      <optional>true</optional>
    </dependency>

    <!-- For javadoc references validation -->
    <dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>neo4j-logging</artifactId>
      <version>${project.version}</version>
      <optional>true</optional>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <!-- since we use test filtering based on tag we need to add junit to the classpath of modules where we do not have any tests -->
      <!-- when any test will be added to the module remove skipTests configuration -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <skipTests>true</skipTests>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <configuration>
          <skipTests>true</skipTests>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>analyze</id>
            <goals>
              <goal>analyze-only</goal>
            </goals>
            <configuration>
              <failOnWarning>true</failOnWarning>
              <ignoredDependencies>
                <!-- Ignore test dependencies to not risk tests stop running and for convenience. -->
                <ignoredDependency>org.junit.jupiter:*</ignoredDependency>
                <ignoredDependency>org.scalatest:*</ignoredDependency>
                <ignoredDependency>org.scalacheck:*</ignoredDependency>
                <ignoredDependency>co.helmethair:scalatest-junit-runner</ignoredDependency>
                <ignoredDependency>org.opentest4j:opentest4j</ignoredDependency>
                <ignoredDependency>org.assertj:*</ignoredDependency>

                <!-- For javadoc references validation -->
                <ignoredDependency>org.neo4j:neo4j-logging</ignoredDependency>
                <ignoredDependency>org.neo4j:neo4j-graphdb-api</ignoredDependency>
              </ignoredDependencies>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
