/* Generated by: ParserGeneratorCC: Do not edit this line. CypherConstants.java */
/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [https://neo4j.com]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.neo4j.cypher.internal.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by com.helger.pgcc.output.java.OtherFilesGenJava#start()
 */
public interface CypherConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 29;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 32;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 33;
  /** RegularExpression Id. */
  int DECIMAL_DOUBLE = 35;
  /** RegularExpression Id. */
  int UNSIGNED_DECIMAL_INTEGER = 36;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 37;
  /** RegularExpression Id. */
  int INTEGER_PART = 38;
  /** RegularExpression Id. */
  int UNSIGNED_HEX_INTEGER = 39;
  /** RegularExpression Id. */
  int UNSIGNED_OCTAL_INTEGER = 40;
  /** RegularExpression Id. */
  int STRING1_OPEN = 41;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 52;
  /** RegularExpression Id. */
  int STRING2_OPEN = 53;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 64;
  /** RegularExpression Id. */
  int ESCAPED_SYMBOLIC_NAME_OPEN = 65;
  /** RegularExpression Id. */
  int ESCAPED_SYMBOLIC_NAME = 68;
  /** RegularExpression Id. */
  int ACCESS = 69;
  /** RegularExpression Id. */
  int ACTIVE = 70;
  /** RegularExpression Id. */
  int ADMIN = 71;
  /** RegularExpression Id. */
  int ADMINISTRATOR = 72;
  /** RegularExpression Id. */
  int ALIAS = 73;
  /** RegularExpression Id. */
  int ALIASES = 74;
  /** RegularExpression Id. */
  int ALL_SHORTEST_PATH = 75;
  /** RegularExpression Id. */
  int ALL = 76;
  /** RegularExpression Id. */
  int ALTER = 77;
  /** RegularExpression Id. */
  int AND = 78;
  /** RegularExpression Id. */
  int ANY = 79;
  /** RegularExpression Id. */
  int ARRAY = 80;
  /** RegularExpression Id. */
  int AS = 81;
  /** RegularExpression Id. */
  int ASC = 82;
  /** RegularExpression Id. */
  int ASCENDING = 83;
  /** RegularExpression Id. */
  int ASSERT = 84;
  /** RegularExpression Id. */
  int ASSIGN = 85;
  /** RegularExpression Id. */
  int AT = 86;
  /** RegularExpression Id. */
  int BAR = 87;
  /** RegularExpression Id. */
  int BINDINGS = 88;
  /** RegularExpression Id. */
  int BOOL = 89;
  /** RegularExpression Id. */
  int BOOLEAN = 90;
  /** RegularExpression Id. */
  int BOOSTED = 91;
  /** RegularExpression Id. */
  int BOTH = 92;
  /** RegularExpression Id. */
  int BREAK = 93;
  /** RegularExpression Id. */
  int BRIEF = 94;
  /** RegularExpression Id. */
  int BTREE = 95;
  /** RegularExpression Id. */
  int BUILT = 96;
  /** RegularExpression Id. */
  int BY = 97;
  /** RegularExpression Id. */
  int CALL = 98;
  /** RegularExpression Id. */
  int CASE = 99;
  /** RegularExpression Id. */
  int CHANGE = 100;
  /** RegularExpression Id. */
  int CIDR = 101;
  /** RegularExpression Id. */
  int COLLECT = 102;
  /** RegularExpression Id. */
  int COLON = 103;
  /** RegularExpression Id. */
  int COLONCOLON = 104;
  /** RegularExpression Id. */
  int COMMA = 105;
  /** RegularExpression Id. */
  int COMMAND = 106;
  /** RegularExpression Id. */
  int COMMANDS = 107;
  /** RegularExpression Id. */
  int COMMIT = 108;
  /** RegularExpression Id. */
  int COMPOSITE = 109;
  /** RegularExpression Id. */
  int CONCURRENT = 110;
  /** RegularExpression Id. */
  int CONSTRAINT = 111;
  /** RegularExpression Id. */
  int CONSTRAINTS = 112;
  /** RegularExpression Id. */
  int CONTAINS = 113;
  /** RegularExpression Id. */
  int COPY = 114;
  /** RegularExpression Id. */
  int CONTINUE = 115;
  /** RegularExpression Id. */
  int COUNT = 116;
  /** RegularExpression Id. */
  int CREATE = 117;
  /** RegularExpression Id. */
  int CSV = 118;
  /** RegularExpression Id. */
  int CURRENT = 119;
  /** RegularExpression Id. */
  int DATA = 120;
  /** RegularExpression Id. */
  int DATABASE = 121;
  /** RegularExpression Id. */
  int DATABASES = 122;
  /** RegularExpression Id. */
  int DATE = 123;
  /** RegularExpression Id. */
  int DATETIME = 124;
  /** RegularExpression Id. */
  int DBMS = 125;
  /** RegularExpression Id. */
  int DEALLOCATE = 126;
  /** RegularExpression Id. */
  int DEFAULT_TOKEN = 127;
  /** RegularExpression Id. */
  int DEFINED = 128;
  /** RegularExpression Id. */
  int DELETE = 129;
  /** RegularExpression Id. */
  int DENY = 130;
  /** RegularExpression Id. */
  int DESC = 131;
  /** RegularExpression Id. */
  int DESCENDING = 132;
  /** RegularExpression Id. */
  int DESTROY = 133;
  /** RegularExpression Id. */
  int DETACH = 134;
  /** RegularExpression Id. */
  int DOLLAR = 135;
  /** RegularExpression Id. */
  int DOUBLEBAR = 136;
  /** RegularExpression Id. */
  int DIFFERENT = 137;
  /** RegularExpression Id. */
  int DISTINCT = 138;
  /** RegularExpression Id. */
  int DIVIDE = 139;
  /** RegularExpression Id. */
  int DOT = 140;
  /** RegularExpression Id. */
  int DOTDOT = 141;
  /** RegularExpression Id. */
  int DRIVER = 142;
  /** RegularExpression Id. */
  int DROP = 143;
  /** RegularExpression Id. */
  int DRYRUN = 144;
  /** RegularExpression Id. */
  int DUMP = 145;
  /** RegularExpression Id. */
  int DURATION = 146;
  /** RegularExpression Id. */
  int EACH = 147;
  /** RegularExpression Id. */
  int EDGE = 148;
  /** RegularExpression Id. */
  int ENABLE = 149;
  /** RegularExpression Id. */
  int ELEMENT = 150;
  /** RegularExpression Id. */
  int ELEMENTS = 151;
  /** RegularExpression Id. */
  int ELSE = 152;
  /** RegularExpression Id. */
  int ENCRYPTED = 153;
  /** RegularExpression Id. */
  int END = 154;
  /** RegularExpression Id. */
  int ENDS = 155;
  /** RegularExpression Id. */
  int EQ = 156;
  /** RegularExpression Id. */
  int EXECUTABLE = 157;
  /** RegularExpression Id. */
  int EXECUTE = 158;
  /** RegularExpression Id. */
  int EXIST = 159;
  /** RegularExpression Id. */
  int EXISTENCE = 160;
  /** RegularExpression Id. */
  int EXISTS = 161;
  /** RegularExpression Id. */
  int ERROR = 162;
  /** RegularExpression Id. */
  int FAIL = 163;
  /** RegularExpression Id. */
  int FALSE = 164;
  /** RegularExpression Id. */
  int FIELDTERMINATOR = 165;
  /** RegularExpression Id. */
  int FINISH = 166;
  /** RegularExpression Id. */
  int FLOAT = 167;
  /** RegularExpression Id. */
  int FOR = 168;
  /** RegularExpression Id. */
  int FOREACH = 169;
  /** RegularExpression Id. */
  int FROM = 170;
  /** RegularExpression Id. */
  int FULLTEXT = 171;
  /** RegularExpression Id. */
  int FUNCTION = 172;
  /** RegularExpression Id. */
  int FUNCTIONS = 173;
  /** RegularExpression Id. */
  int GE = 174;
  /** RegularExpression Id. */
  int GRANT = 175;
  /** RegularExpression Id. */
  int GRAPH = 176;
  /** RegularExpression Id. */
  int GRAPHS = 177;
  /** RegularExpression Id. */
  int GROUP = 178;
  /** RegularExpression Id. */
  int GROUPS = 179;
  /** RegularExpression Id. */
  int GT = 180;
  /** RegularExpression Id. */
  int HEADERS = 181;
  /** RegularExpression Id. */
  int HOME = 182;
  /** RegularExpression Id. */
  int IF = 183;
  /** RegularExpression Id. */
  int IMPERSONATE = 184;
  /** RegularExpression Id. */
  int IMMUTABLE = 185;
  /** RegularExpression Id. */
  int IN = 186;
  /** RegularExpression Id. */
  int INDEX = 187;
  /** RegularExpression Id. */
  int INDEXES = 188;
  /** RegularExpression Id. */
  int INF = 189;
  /** RegularExpression Id. */
  int INFINITY = 190;
  /** RegularExpression Id. */
  int INSERT = 191;
  /** RegularExpression Id. */
  int INT = 192;
  /** RegularExpression Id. */
  int INTEGER = 193;
  /** RegularExpression Id. */
  int IS = 194;
  /** RegularExpression Id. */
  int JOIN = 195;
  /** RegularExpression Id. */
  int KEY = 196;
  /** RegularExpression Id. */
  int LABEL = 197;
  /** RegularExpression Id. */
  int LABELS = 198;
  /** RegularExpression Id. */
  int AMPERSAND = 199;
  /** RegularExpression Id. */
  int EXCLAMATION_MARK = 200;
  /** RegularExpression Id. */
  int LBRACKET = 201;
  /** RegularExpression Id. */
  int LCURLY = 202;
  /** RegularExpression Id. */
  int LE = 203;
  /** RegularExpression Id. */
  int LEADING = 204;
  /** RegularExpression Id. */
  int LIMITROWS = 205;
  /** RegularExpression Id. */
  int LIST = 206;
  /** RegularExpression Id. */
  int LOAD = 207;
  /** RegularExpression Id. */
  int LOCAL = 208;
  /** RegularExpression Id. */
  int LOOKUP = 209;
  /** RegularExpression Id. */
  int LPAREN = 210;
  /** RegularExpression Id. */
  int LT = 211;
  /** RegularExpression Id. */
  int MANAGEMENT = 212;
  /** RegularExpression Id. */
  int MAP = 213;
  /** RegularExpression Id. */
  int MATCH = 214;
  /** RegularExpression Id. */
  int MERGE = 215;
  /** RegularExpression Id. */
  int MINUS = 216;
  /** RegularExpression Id. */
  int PERCENT = 217;
  /** RegularExpression Id. */
  int NEQ = 218;
  /** RegularExpression Id. */
  int NEQ2 = 219;
  /** RegularExpression Id. */
  int NAME = 220;
  /** RegularExpression Id. */
  int NAMES = 221;
  /** RegularExpression Id. */
  int NAN = 222;
  /** RegularExpression Id. */
  int NFC = 223;
  /** RegularExpression Id. */
  int NFD = 224;
  /** RegularExpression Id. */
  int NFKC = 225;
  /** RegularExpression Id. */
  int NFKD = 226;
  /** RegularExpression Id. */
  int NEW = 227;
  /** RegularExpression Id. */
  int NODE = 228;
  /** RegularExpression Id. */
  int NODETACH = 229;
  /** RegularExpression Id. */
  int NODES = 230;
  /** RegularExpression Id. */
  int NONE = 231;
  /** RegularExpression Id. */
  int NORMALIZE = 232;
  /** RegularExpression Id. */
  int NORMALIZED = 233;
  /** RegularExpression Id. */
  int NOT = 234;
  /** RegularExpression Id. */
  int NOTHING = 235;
  /** RegularExpression Id. */
  int NOWAIT = 236;
  /** RegularExpression Id. */
  int NULL = 237;
  /** RegularExpression Id. */
  int OF = 238;
  /** RegularExpression Id. */
  int ON = 239;
  /** RegularExpression Id. */
  int ONLY = 240;
  /** RegularExpression Id. */
  int OPTIONAL = 241;
  /** RegularExpression Id. */
  int OPTIONS = 242;
  /** RegularExpression Id. */
  int OPTION = 243;
  /** RegularExpression Id. */
  int OR = 244;
  /** RegularExpression Id. */
  int ORDER = 245;
  /** RegularExpression Id. */
  int OUTPUT = 246;
  /** RegularExpression Id. */
  int PASSWORD = 247;
  /** RegularExpression Id. */
  int PASSWORDS = 248;
  /** RegularExpression Id. */
  int PATH = 249;
  /** RegularExpression Id. */
  int PATHS = 250;
  /** RegularExpression Id. */
  int PERIODIC = 251;
  /** RegularExpression Id. */
  int PLAINTEXT = 252;
  /** RegularExpression Id. */
  int PLUS = 253;
  /** RegularExpression Id. */
  int PLUSEQUAL = 254;
  /** RegularExpression Id. */
  int POINT = 255;
  /** RegularExpression Id. */
  int POPULATED = 256;
  /** RegularExpression Id. */
  int POW = 257;
  /** RegularExpression Id. */
  int REPEATABLE = 258;
  /** RegularExpression Id. */
  int PRIMARY = 259;
  /** RegularExpression Id. */
  int PRIMARIES = 260;
  /** RegularExpression Id. */
  int PRIVILEGE = 261;
  /** RegularExpression Id. */
  int PRIVILEGES = 262;
  /** RegularExpression Id. */
  int PROCEDURE = 263;
  /** RegularExpression Id. */
  int PROCEDURES = 264;
  /** RegularExpression Id. */
  int PROPERTIES = 265;
  /** RegularExpression Id. */
  int PROPERTY = 266;
  /** RegularExpression Id. */
  int QUESTION = 267;
  /** RegularExpression Id. */
  int RANGE = 268;
  /** RegularExpression Id. */
  int RBRACKET = 269;
  /** RegularExpression Id. */
  int RCURLY = 270;
  /** RegularExpression Id. */
  int READ = 271;
  /** RegularExpression Id. */
  int REALLOCATE = 272;
  /** RegularExpression Id. */
  int REDUCE = 273;
  /** RegularExpression Id. */
  int RENAME = 274;
  /** RegularExpression Id. */
  int REGEQ = 275;
  /** RegularExpression Id. */
  int REL = 276;
  /** RegularExpression Id. */
  int RELATIONSHIP = 277;
  /** RegularExpression Id. */
  int RELATIONSHIPS = 278;
  /** RegularExpression Id. */
  int REMOVE = 279;
  /** RegularExpression Id. */
  int REPLACE = 280;
  /** RegularExpression Id. */
  int REPORT = 281;
  /** RegularExpression Id. */
  int REQUIRE = 282;
  /** RegularExpression Id. */
  int REQUIRED = 283;
  /** RegularExpression Id. */
  int RETURN = 284;
  /** RegularExpression Id. */
  int REVOKE = 285;
  /** RegularExpression Id. */
  int ROLE = 286;
  /** RegularExpression Id. */
  int ROLES = 287;
  /** RegularExpression Id. */
  int ROW = 288;
  /** RegularExpression Id. */
  int ROWS = 289;
  /** RegularExpression Id. */
  int RPAREN = 290;
  /** RegularExpression Id. */
  int SCAN = 291;
  /** RegularExpression Id. */
  int SEC = 292;
  /** RegularExpression Id. */
  int SECOND = 293;
  /** RegularExpression Id. */
  int SECONDARY = 294;
  /** RegularExpression Id. */
  int SECONDARIES = 295;
  /** RegularExpression Id. */
  int SECONDS = 296;
  /** RegularExpression Id. */
  int SEEK = 297;
  /** RegularExpression Id. */
  int SEMICOLON = 298;
  /** RegularExpression Id. */
  int SERVER = 299;
  /** RegularExpression Id. */
  int SERVERS = 300;
  /** RegularExpression Id. */
  int SET = 301;
  /** RegularExpression Id. */
  int SETTING = 302;
  /** RegularExpression Id. */
  int SETTINGS = 303;
  /** RegularExpression Id. */
  int SHORTEST_PATH = 304;
  /** RegularExpression Id. */
  int SHORTEST = 305;
  /** RegularExpression Id. */
  int SHOW = 306;
  /** RegularExpression Id. */
  int SIGNED = 307;
  /** RegularExpression Id. */
  int SINGLE = 308;
  /** RegularExpression Id. */
  int SKIPROWS = 309;
  /** RegularExpression Id. */
  int START = 310;
  /** RegularExpression Id. */
  int STARTS = 311;
  /** RegularExpression Id. */
  int STATUS = 312;
  /** RegularExpression Id. */
  int STOP = 313;
  /** RegularExpression Id. */
  int STRING = 314;
  /** RegularExpression Id. */
  int SUPPORTED = 315;
  /** RegularExpression Id. */
  int SUSPENDED = 316;
  /** RegularExpression Id. */
  int TARGET = 317;
  /** RegularExpression Id. */
  int TERMINATE = 318;
  /** RegularExpression Id. */
  int TEXT = 319;
  /** RegularExpression Id. */
  int THEN = 320;
  /** RegularExpression Id. */
  int TIME = 321;
  /** RegularExpression Id. */
  int TIMES = 322;
  /** RegularExpression Id. */
  int TIMESTAMP = 323;
  /** RegularExpression Id. */
  int TIMEZONE = 324;
  /** RegularExpression Id. */
  int TO = 325;
  /** RegularExpression Id. */
  int TOPOLOGY = 326;
  /** RegularExpression Id. */
  int TRAILING = 327;
  /** RegularExpression Id. */
  int TRANSACTION = 328;
  /** RegularExpression Id. */
  int TRANSACTIONS = 329;
  /** RegularExpression Id. */
  int TRAVERSE = 330;
  /** RegularExpression Id. */
  int TRIM = 331;
  /** RegularExpression Id. */
  int TRUE = 332;
  /** RegularExpression Id. */
  int TYPE = 333;
  /** RegularExpression Id. */
  int TYPED = 334;
  /** RegularExpression Id. */
  int TYPES = 335;
  /** RegularExpression Id. */
  int UNION = 336;
  /** RegularExpression Id. */
  int UNIQUE = 337;
  /** RegularExpression Id. */
  int UNIQUENESS = 338;
  /** RegularExpression Id. */
  int UNWIND = 339;
  /** RegularExpression Id. */
  int URL = 340;
  /** RegularExpression Id. */
  int USE = 341;
  /** RegularExpression Id. */
  int USER = 342;
  /** RegularExpression Id. */
  int USERS = 343;
  /** RegularExpression Id. */
  int USING = 344;
  /** RegularExpression Id. */
  int VALUE = 345;
  /** RegularExpression Id. */
  int VARCHAR = 346;
  /** RegularExpression Id. */
  int VECTOR = 347;
  /** RegularExpression Id. */
  int VERBOSE = 348;
  /** RegularExpression Id. */
  int VERTEX = 349;
  /** RegularExpression Id. */
  int WAIT = 350;
  /** RegularExpression Id. */
  int WHEN = 351;
  /** RegularExpression Id. */
  int WHERE = 352;
  /** RegularExpression Id. */
  int WITH = 353;
  /** RegularExpression Id. */
  int WITHOUT = 354;
  /** RegularExpression Id. */
  int WRITE = 355;
  /** RegularExpression Id. */
  int XOR = 356;
  /** RegularExpression Id. */
  int YIELD = 357;
  /** RegularExpression Id. */
  int ZONED = 358;
  /** RegularExpression Id. */
  int IDENTIFIER = 359;
  /** RegularExpression Id. */
  int LETTER = 360;
  /** RegularExpression Id. */
  int PART_LETTER = 361;
  /** RegularExpression Id. */
  int ARROW_LINE = 362;
  /** RegularExpression Id. */
  int ARROW_LEFT_HEAD = 363;
  /** RegularExpression Id. */
  int ARROW_RIGHT_HEAD = 364;
  /** RegularExpression Id. */
  int UNKNOWN = 365;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 3;
  /** Lexical state. */
  int STRING1 = 4;
  /** Lexical state. */
  int STRING2 = 5;
  /** Lexical state. */
  int ESC_SYMB_NAME = 6;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\u000b\"",
    "\"\\f\"",
    "\"\\r\"",
    "\"\\u001c\"",
    "\"\\u001d\"",
    "\"\\u001e\"",
    "\"\\u001f\"",
    "\" \"",
    "\"\\u00a0\"",
    "\"\\u1680\"",
    "\"\\u2000\"",
    "\"\\u2001\"",
    "\"\\u2002\"",
    "\"\\u2003\"",
    "\"\\u2004\"",
    "\"\\u2005\"",
    "\"\\u2006\"",
    "\"\\u2007\"",
    "\"\\u2008\"",
    "\"\\u2009\"",
    "\"\\u200a\"",
    "\"\\u2028\"",
    "\"\\u2029\"",
    "\"\\u202f\"",
    "\"\\u205f\"",
    "\"\\u3000\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 30>",
    "\"/*\"",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 34>",
    "<DECIMAL_DOUBLE>",
    "<UNSIGNED_DECIMAL_INTEGER>",
    "<DECIMAL_EXPONENT>",
    "<INTEGER_PART>",
    "<UNSIGNED_HEX_INTEGER>",
    "<UNSIGNED_OCTAL_INTEGER>",
    "\"\\\'\"",
    "\"\\\\\\\\\"",
    "\"\\\\\\\'\"",
    "\"\\\\\\\"\"",
    "\"\\\\b\"",
    "\"\\\\f\"",
    "\"\\\\n\"",
    "\"\\\\r\"",
    "\"\\\\t\"",
    "\"\\\\u[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]\"",
    "<token of kind 51>",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"\\\\\\\\\"",
    "\"\\\\\\\'\"",
    "\"\\\\\\\"\"",
    "\"\\\\b\"",
    "\"\\\\f\"",
    "\"\\\\n\"",
    "\"\\\\r\"",
    "\"\\\\t\"",
    "\"\\\\u[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]\"",
    "<token of kind 63>",
    "\"\\\"\"",
    "\"`\"",
    "<token of kind 66>",
    "\"``\"",
    "\"`\"",
    "\"ACCESS\"",
    "\"ACTIVE\"",
    "\"ADMIN\"",
    "\"ADMINISTRATOR\"",
    "\"ALIAS\"",
    "\"ALIASES\"",
    "\"allShortestPaths\"",
    "\"ALL\"",
    "\"ALTER\"",
    "\"AND\"",
    "\"ANY\"",
    "\"ARRAY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"ASCENDING\"",
    "\"ASSERT\"",
    "\"ASSIGN\"",
    "\"AT\"",
    "\"|\"",
    "\"BINDINGS\"",
    "\"BOOL\"",
    "\"BOOLEAN\"",
    "\"BOOSTED\"",
    "\"BOTH\"",
    "\"BREAK\"",
    "\"BRIEF\"",
    "\"BTREE\"",
    "\"BUILT\"",
    "\"BY\"",
    "\"CALL\"",
    "\"CASE\"",
    "\"CHANGE\"",
    "\"CIDR\"",
    "\"COLLECT\"",
    "\":\"",
    "\"::\"",
    "\",\"",
    "\"COMMAND\"",
    "\"COMMANDS\"",
    "\"COMMIT\"",
    "\"COMPOSITE\"",
    "\"CONCURRENT\"",
    "\"CONSTRAINT\"",
    "\"CONSTRAINTS\"",
    "\"CONTAINS\"",
    "\"COPY\"",
    "\"CONTINUE\"",
    "\"COUNT\"",
    "\"CREATE\"",
    "\"CSV\"",
    "\"CURRENT\"",
    "\"DATA\"",
    "\"DATABASE\"",
    "\"DATABASES\"",
    "\"DATE\"",
    "\"DATETIME\"",
    "\"DBMS\"",
    "\"DEALLOCATE\"",
    "\"DEFAULT\"",
    "\"DEFINED\"",
    "\"DELETE\"",
    "\"DENY\"",
    "\"DESC\"",
    "\"DESCENDING\"",
    "\"DESTROY\"",
    "\"DETACH\"",
    "\"$\"",
    "\"||\"",
    "\"DIFFERENT\"",
    "\"DISTINCT\"",
    "\"/\"",
    "\".\"",
    "\"..\"",
    "\"DRIVER\"",
    "\"DROP\"",
    "\"DRYRUN\"",
    "\"DUMP\"",
    "\"DURATION\"",
    "\"EACH\"",
    "\"EDGE\"",
    "\"ENABLE\"",
    "\"ELEMENT\"",
    "\"ELEMENTS\"",
    "\"ELSE\"",
    "\"ENCRYPTED\"",
    "\"END\"",
    "\"ENDS\"",
    "\"=\"",
    "\"EXECUTABLE\"",
    "\"EXECUTE\"",
    "\"EXIST\"",
    "\"EXISTENCE\"",
    "\"EXISTS\"",
    "\"ERROR\"",
    "\"FAIL\"",
    "\"false\"",
    "\"FIELDTERMINATOR\"",
    "\"FINISH\"",
    "\"FLOAT\"",
    "\"FOR\"",
    "\"FOREACH\"",
    "\"FROM\"",
    "\"FULLTEXT\"",
    "\"FUNCTION\"",
    "\"FUNCTIONS\"",
    "\">=\"",
    "\"GRANT\"",
    "\"GRAPH\"",
    "\"GRAPHS\"",
    "\"GROUP\"",
    "\"GROUPS\"",
    "\">\"",
    "\"HEADERS\"",
    "\"HOME\"",
    "\"IF\"",
    "\"IMPERSONATE\"",
    "\"IMMUTABLE\"",
    "\"IN\"",
    "\"INDEX\"",
    "\"INDEXES\"",
    "\"INF\"",
    "\"INFINITY\"",
    "\"INSERT\"",
    "\"INT\"",
    "\"INTEGER\"",
    "\"IS\"",
    "\"JOIN\"",
    "\"KEY\"",
    "\"LABEL\"",
    "\"LABELS\"",
    "\"&\"",
    "\"!\"",
    "\"[\"",
    "\"{\"",
    "\"<=\"",
    "\"LEADING\"",
    "\"LIMIT\"",
    "\"LIST\"",
    "\"LOAD\"",
    "\"LOCAL\"",
    "\"LOOKUP\"",
    "\"(\"",
    "\"<\"",
    "\"MANAGEMENT\"",
    "\"MAP\"",
    "\"MATCH\"",
    "\"MERGE\"",
    "\"-\"",
    "\"%\"",
    "\"!=\"",
    "\"<>\"",
    "\"NAME\"",
    "\"NAMES\"",
    "\"NAN\"",
    "\"NFC\"",
    "\"NFD\"",
    "\"NFKC\"",
    "\"NFKD\"",
    "\"NEW\"",
    "\"NODE\"",
    "\"NODETACH\"",
    "\"NODES\"",
    "\"NONE\"",
    "\"NORMALIZE\"",
    "\"NORMALIZED\"",
    "\"NOT\"",
    "\"NOTHING\"",
    "\"NOWAIT\"",
    "\"null\"",
    "\"OF\"",
    "\"ON\"",
    "\"ONLY\"",
    "\"OPTIONAL\"",
    "\"OPTIONS\"",
    "\"OPTION\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"OUTPUT\"",
    "\"PASSWORD\"",
    "\"PASSWORDS\"",
    "\"PATH\"",
    "\"PATHS\"",
    "\"PERIODIC\"",
    "\"PLAINTEXT\"",
    "\"+\"",
    "\"+=\"",
    "\"POINT\"",
    "\"POPULATED\"",
    "\"^\"",
    "\"REPEATABLE\"",
    "\"PRIMARY\"",
    "\"PRIMARIES\"",
    "\"PRIVILEGE\"",
    "\"PRIVILEGES\"",
    "\"PROCEDURE\"",
    "\"PROCEDURES\"",
    "\"PROPERTIES\"",
    "\"PROPERTY\"",
    "\"?\"",
    "\"RANGE\"",
    "\"]\"",
    "\"}\"",
    "\"READ\"",
    "\"REALLOCATE\"",
    "\"REDUCE\"",
    "\"RENAME\"",
    "\"=~\"",
    "\"REL\"",
    "\"RELATIONSHIP\"",
    "\"RELATIONSHIPS\"",
    "\"REMOVE\"",
    "\"REPLACE\"",
    "\"REPORT\"",
    "\"REQUIRE\"",
    "\"REQUIRED\"",
    "\"RETURN\"",
    "\"REVOKE\"",
    "\"ROLE\"",
    "\"ROLES\"",
    "\"ROW\"",
    "\"ROWS\"",
    "\")\"",
    "\"SCAN\"",
    "\"SEC\"",
    "\"SECOND\"",
    "\"SECONDARY\"",
    "\"SECONDARIES\"",
    "\"SECONDS\"",
    "\"SEEK\"",
    "\";\"",
    "\"SERVER\"",
    "\"SERVERS\"",
    "\"SET\"",
    "\"SETTING\"",
    "\"SETTINGS\"",
    "\"shortestPath\"",
    "\"SHORTEST\"",
    "\"SHOW\"",
    "\"SIGNED\"",
    "\"SINGLE\"",
    "\"SKIP\"",
    "\"START\"",
    "\"STARTS\"",
    "\"STATUS\"",
    "\"STOP\"",
    "\"STRING\"",
    "\"SUPPORTED\"",
    "\"SUSPENDED\"",
    "\"TARGET\"",
    "\"TERMINATE\"",
    "\"TEXT\"",
    "\"THEN\"",
    "\"TIME\"",
    "\"*\"",
    "\"TIMESTAMP\"",
    "\"TIMEZONE\"",
    "\"TO\"",
    "\"TOPOLOGY\"",
    "\"TRAILING\"",
    "\"TRANSACTION\"",
    "\"TRANSACTIONS\"",
    "\"TRAVERSE\"",
    "\"TRIM\"",
    "\"true\"",
    "\"TYPE\"",
    "\"TYPED\"",
    "\"TYPES\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UNIQUENESS\"",
    "\"UNWIND\"",
    "\"URL\"",
    "\"USE\"",
    "\"USER\"",
    "\"USERS\"",
    "\"USING\"",
    "\"VALUE\"",
    "\"VARCHAR\"",
    "\"VECTOR\"",
    "\"VERBOSE\"",
    "\"VERTEX\"",
    "\"WAIT\"",
    "\"WHEN\"",
    "\"WHERE\"",
    "\"WITH\"",
    "\"WITHOUT\"",
    "\"WRITE\"",
    "\"XOR\"",
    "\"YIELD\"",
    "\"ZONED\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "<ARROW_LINE>",
    "<ARROW_LEFT_HEAD>",
    "<ARROW_RIGHT_HEAD>",
    "<UNKNOWN>",
  };

}
