'\" t
.\"     Title: neo4j-import
.\"    Author: The Neo4j Team
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 10/19/2016
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "NEO4J\-IMPORT" "1" "10/19/2016" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------


.SH "NAME"
neo4j-import \- Neo4j Import Tool
.SH "SYNOPSIS"
.sp
\fBneo4j\-import\fR [options]

.SH "DESCRIPTION"

.sp
\fBneo4j\-import\fR is used to create a new Neo4j database from data in CSV files\&. See the chapter "Import Tool" in the Neo4j Manual for details on the CSV file format \(em a special kind of header is required\&.
.sp
For information regarding Windows, see \m[blue]\fBhttps://neo4j\&.com/docs/operations\-manual/current/deployment/single\-instance/windows/\fR\m[]\&.

.SH "OPTIONS"



.PP
\fB\-\-into <store\-dir>\fR
.RS 4



Database directory to import into\&. Must not contain existing database\&.

.RE
.PP
\fB\-\-nodes[:Label1:Label2] "<file1>,<file2>,\&..."\fR
.RS 4



Node CSV header and data\&. Multiple files will be logically seen as one big file from the perspective of the importer\&. The first line must contain the header\&. Multiple data sources like these can be specified in one import, where each data source has its own header\&. Note that file groups must be enclosed in quotation marks\&.

.RE
.PP
\fB\-\-relationships[:RELATIONSHIP_TYPE] "<file1>,<file2>,\&..."\fR
.RS 4



Relationship CSV header and data\&. Multiple files will be logically seen as one big file from the perspective of the importer\&. The first line must contain the header\&. Multiple data sources like these can be specified in one import, where each data source has its own header\&. Note that file groups must be enclosed in quotation marks\&.

.RE
.PP
\fB\-\-delimiter <delimiter\-character>\fR
.RS 4



Delimiter character, or
\fITAB\fR, between values in CSV data\&. The default option is
,\&.

.RE
.PP
\fB\-\-array\-delimiter <array\-delimiter\-character>\fR
.RS 4



Delimiter character, or
\fITAB\fR, between array elements within a value in CSV data\&. The default option is
;\&.

.RE
.PP
\fB\-\-quote <quotation\-character>\fR
.RS 4



Character to treat as quotation character for values in CSV data\&. The default option is
"\&. Quotes inside quotes escaped like
"""Go away"", he said\&."
and
"\e"Go away\e", he said\&."
are supported\&. If you have set "\*(Aq" to be used as the quotation character, you could write the previous example like this instead:
\*(Aq"Go away", he said\&.\*(Aq

.RE
.PP
\fB\-\-multiline\-fields <true/false>\fR
.RS 4



Whether or not fields from input source can span multiple lines, i\&.e\&. contain newline characters\&. Default value: false

.RE
.PP
\fB\-\-input\-encoding <character set>\fR
.RS 4



Character set that input data is encoded in\&. Provided value must be one out of the available character sets in the JVM, as provided by Charset#availableCharsets()\&. If no input encoding is provided, the default character set of the JVM will be used\&.

.RE
.PP
\fB\-\-ignore\-empty\-strings <true/false>\fR
.RS 4



Whether or not empty string fields, i\&.e\&. "" from input source are ignored, i\&.e\&. treated as null\&. Default value: false

.RE
.PP
\fB\-\-id\-type <id\-type>\fR
.RS 4



One out of [STRING, INTEGER, ACTUAL] and specifies how ids in node/relationship input files are treated\&. STRING: arbitrary strings for identifying nodes\&. INTEGER: arbitrary integer values for identifying nodes\&. ACTUAL: (advanced) actual node ids\&. The default option is
STRING\&. Default value: STRING

.RE
.PP
\fB\-\-processors <max processor count>\fR
.RS 4



(advanced) Max number of processors used by the importer\&. Defaults to the number of available processors reported by the JVM\&. There is a certain amount of minimum threads needed so for that reason there is no lower bound for this value\&. For optimal performance this value shouldn\(cqt be greater than the number of available processors\&.

.RE
.PP
\fB\-\-stacktrace <true/false>\fR
.RS 4



Enable printing of error stack traces\&.

.RE
.PP
\fB\-\-bad\-tolerance <max number of bad entries>\fR
.RS 4



Number of bad entries before the import is considered failed\&. This tolerance threshold is about relationships refering to missing nodes\&. Format errors in input data are still treated as errors\&. Default value: 1000

.RE
.PP
\fB\-\-skip\-bad\-relationships <true/false>\fR
.RS 4



Whether or not to skip importing relationships that refers to missing node ids, i\&.e\&. either start or end node id/group referring to node that wasn\(cqt specified by the node input data\&. Skipped nodes will be logged, containing at most number of entites specified by bad\-tolerance\&. Default value: true

.RE
.PP
\fB\-\-skip\-duplicate\-nodes <true/false>\fR
.RS 4



Whether or not to skip importing nodes that have the same id/group\&. In the event of multiple nodes within the same group having the same id, the first encountered will be imported whereas consecutive such nodes will be skipped\&. Skipped nodes will be logged, containing at most number of entities specified by bad\-tolerance\&. Default value: false

.RE
.PP
\fB\-\-ignore\-extra\-columns <true/false>\fR
.RS 4



Whether or not to ignore extra columns in the data not specified by the header\&. Skipped columns will be logged, containing at most number of entities specified by bad\-tolerance\&. Default value: false

.RE
.PP
\fB\-\-db\-config <path/to/neo4j\&.conf>\fR
.RS 4



(advanced) File specifying database\-specific configuration\&. For more information consult manual about available configuration options for a neo4j configuration file\&. Only configuration affecting store at time of creation will be read\&. Examples of supported config are: dbms\&.relationship_grouping_threshold unsupported\&.dbms\&.block_size\&.strings unsupported\&.dbms\&.block_size\&.array_properties

.RE
.PP
\fB\-\-page\-size <page size in bytes\fR
.RS 4



Page size in bytes, or e\&.g\&. 4M or 8k\&. Default value: 4\&.00 MB

.RE

.SH "EXAMPLES"

.sp
Below is a basic example, where we import movies, actors and roles from three files\&.
.PP
\fBmovies.csv\fR. 
.sp
.if n \{\
.RS 4
.\}
.nf
movieId:ID,title,year:int,:LABEL
tt0133093,"The Matrix",1999,Movie
tt0234215,"The Matrix Reloaded",2003,Movie;Sequel
tt0242653,"The Matrix Revolutions",2003,Movie;Sequel
.fi
.if n \{\
.RE
.\}
.sp

.PP
\fBactors.csv\fR. 
.sp
.if n \{\
.RS 4
.\}
.nf
personId:ID,name,:LABEL
keanu,"Keanu Reeves",Actor
laurence,"Laurence Fishburne",Actor
carrieanne,"Carrie\-Anne Moss",Actor
.fi
.if n \{\
.RE
.\}
.sp

.PP
\fBroles.csv\fR. 
.sp
.if n \{\
.RS 4
.\}
.nf
:START_ID,role,:END_ID,:TYPE
keanu,"Neo",tt0133093,ACTED_IN
keanu,"Neo",tt0234215,ACTED_IN
keanu,"Neo",tt0242653,ACTED_IN
laurence,"Morpheus",tt0133093,ACTED_IN
laurence,"Morpheus",tt0234215,ACTED_IN
laurence,"Morpheus",tt0242653,ACTED_IN
carrieanne,"Trinity",tt0133093,ACTED_IN
carrieanne,"Trinity",tt0234215,ACTED_IN
carrieanne,"Trinity",tt0242653,ACTED_IN
.fi
.if n \{\
.RE
.\}
.sp

.sp
The command will look like this:

.sp
.if n \{\
.RS 4
.\}
.nf
neo4j\-import \-\-into path_to_target_directory \-\-nodes movies\&.csv \-\-nodes actors\&.csv \-\-relationships roles\&.csv
.fi
.if n \{\
.RE
.\}
.sp
See the Neo4j Manual for further examples\&.

.SH "AUTHOR"
.PP
\fBThe Neo4j Team\fR
.RS 4
Author.
.RE
