[[deprecations]]
= Deprecations =

This section outlines deprecations in Neo4j 1.9 in order to help you find a smoother transition path to future versions.

Read operations outside of transactions::
In future versions, read operations are only allowed within transactions.
This only affects embedded usage, where you can already start to wrap read operations in transactions to be prepared for the future.

Using parameters for index keys in Cypher::
Use the keys in verbatim instead.
This also makes the execution plan caching more efficient.

The `!` property operator in Cypher::
Expressions like `node.property! = "value"` have been deprecated, please use `has(node.property) AND node.property = "value"` instead.

Cypher CREATE syntax::
The `CREATE a={foo:’bar’}` syntax has been deprecated.
Instead, use `CREATE (a {foo:’bar’})`.

Graph Matching::
The graph-matching component will be removed in future versions.

Plugins::
Plugins will no longer be distributed with Neo4j.
Please see individual maintainers about availability.
For instance, the source for the Gremlin plugin will be available at: https://github.com/neo4j-contrib/gremlin-plugin

The Reference Node::
With the introduction of Labels in Neo4j 2.0 the Reference Node becomes obsolete and will be removed.
Instead, labelled nodes become the well-known starting points in your graph.

