[[rest-api-cypher]]
== Legacy HTTP endpoint for Cypher ==

The Neo4j REST API allows querying with Cypher, see <<cypher-query-lang>>.
The results are returned as a list of string headers (+columns+), and a +data+ part,
consisting of a list of all rows, every row consisting of a list of REST representations
of the field value -- +Node+, +Relationship+, +Path+ or any simple value like +String+.

[NOTE]
This endpoint is deprecated.
Please transition to using the new <<rest-api-transactional>> which among other things, allows you to run multiple Cypher statements in the same transaction.

[TIP]
In order to speed up queries in repeated scenarios, try not to use literals but replace them with parameters wherever possible in order to let the server cache query plans, see <<rest-api-use-parameters>> for details.
Also see <<cypher-parameters>> for where parameters can be used.

include::use-parameters.asciidoc[]

include::create-a-node.asciidoc[]

include::create-a-node-with-multiple-properties.asciidoc[]

include::create-multiple-nodes-with-properties.asciidoc[]

include::set-all-properties-on-a-node-using-cypher.asciidoc[]

include::send-a-query.asciidoc[]

include::return-paths.asciidoc[]

include::nested-results.asciidoc[]

include::retrieve-query-metadata.asciidoc[]

//include::profile-a-query.asciidoc[]

include::errors.asciidoc[]

// not included

//include::array-property.asciidoc[]

//include::nodes-are-represented-as-nodes.asciidoc[]

//include::send-queries-with-errors.asciidoc[]

//include::syntax-errors.asciidoc[]


