[[rest-api-security]]
== Authentication and Authorization ==

NOTE: This is a new feature, your feedback is encouraged.

In order to prevent unauthorized access to Neo4j, the REST API supports authorization and authentication.
When enabled, requests to the REST API must be authorized by an _authorization token_.
The token is acquired by authenticating, and can then be used to gain access to Neo4j.
Authorization is enabled by default, see <<security-server-auth>> for how to disable it.

In general, it is recommended that you give the authorization token, rather than your username and password, to your Neo4j Driver.
This way the driver can access Neo4j, but is not allowed to change your password or invalidate the token.

When Neo4j is first installed you can authenticate with the default user `neo4j` and the default password `neo4j`.
However, the default password must be changed (see <<rest-api-required-password-changes>>) before an authorization token is granted.
This can easily be done via the Neo4j Browser, or via direct HTTP calls.

The authorization token is local to each Neo4j instance.
If you wish to have multiple instances, such as a set of cluster members, accept the same authorization token see <<rest-api-setting-authorization-token>>.
For automated deployments, you may also copy security configuration from another Neo4j instance (see <<rest-api-security-copy-config>>).

To determine if authorization is enabled and to check if an authorization token is valid, see <<rest-api-get-current-authorization-status>>.

[[rest-api-security-getting-started]]
=== Getting Started with Authentication and Authorization

First, make sure authorization is enabled (it's enabled by default, see <<security-server-auth>>).

:leveloffset: 2

include::changing-your-password-for-the-first-time.asciidoc[]

include::using-the-authorization-token.asciidoc[]

:leveloffset: 1

[[rest-api-security-authorization-tokens]]
=== Authorization Tokens

:leveloffset: 2

include::authenticate-to-obtain-an-authorization-token.asciidoc[]

include::invalidating-the-authorization-token.asciidoc[]

include::setting-authorization-token.asciidoc[]

include::attempting-to-get-authorization-status-while-unauthorized.asciidoc[]

:leveloffset: 1

[[rest-api-security-password]]
=== Password Management

:leveloffset: 2

include::required-password-changes.asciidoc[]

include::changing-your-password.asciidoc[]

:leveloffset: 1

[[rest-api-security-status]]
=== Authorization Status

:leveloffset: 2

include::get-current-authorization-status.asciidoc[]

include::get-authorization-status-when-authorization-is-disabled.asciidoc[]

:leveloffset: 1

include::incorrect-username-or-password.asciidoc[]

[[rest-api-security-copy-config]]
=== Copying security configuration from one instance to another ===

In many cases, such as automated deployments, you may want to start a Neo4j instance with pre-configured authentication and authorization.
This is possible by copying the authentication database file from a pre-existing Neo4j instance to your new instance.

By default, this file is located at _data/dbms/auth.db_, and simply copying that file into a new Neo4j instance will transfer your password and authorization token.

