[[rest-api-transactional]]
== Transactional Cypher HTTP endpoint ==

The default way to interact with Neo4j is by using this endpoint.

The Neo4j transactional HTTP endpoint allows you to execute a series of Cypher statements within the scope of a transaction.
The transaction may be kept open across multiple HTTP requests, until the client chooses to commit or roll back.
Each HTTP request can include a list of statements, and for convenience you can include statements along with a request to begin or commit a transaction.

The server guards against orphaned transactions by using a timeout.
If there are no requests for a given transaction within the timeout period, the server will roll it back.
You can configure the timeout in the server configuration, by setting `org.neo4j.server.transaction.timeout` to the number of seconds before timeout.
The default timeout is 60 seconds.

The key difference between the transactional HTTP endpoint for Cypher and the Cypher endpoint (see <<rest-api-cypher>>) is the ability to use the same transaction across multiple HTTP requests.
The Cypher endpoint always attempts to commit a transaction at the end of each HTTP request.
There has also been improvements to the serialization format.

[NOTE]
--
* Literal line breaks are not allowed inside Cypher statements.
* Open transactions are not shared among members of an HA cluster.
  Therefore, if you use this endpoint in an HA cluster, you must ensure that all requests for a given transaction are sent to the same Neo4j instance.
* Cypher queries with +USING PERIODIC COMMIT+  (see <<query-periodic-commit>>) may only be executed when creating a new transaction and immediately committing it with a single HTTP request (see <<rest-api-begin-and-commit-a-transaction-in-one-request>> for how to do that).
* The serialization format for Cypher results is mostly the same as the <<rest-api-cypher,Cypher endpoint>>.
However, the format for raw entities is slightly less verbose and does not include hypermedia links.
--

[TIP]
In order to speed up queries in repeated scenarios, try not to use literals but replace them with parameters wherever possible.
This will let the server cache query plans.
See <<cypher-parameters>> for more information.

include::begin-and-commit-a-transaction-in-one-request.asciidoc[]

include::execute-multiple-statements.asciidoc[]

include::begin-a-transaction.asciidoc[]

include::execute-statements-in-an-open-transaction.asciidoc[]

include::execute-statements-in-an-open-transaction-in-rest-format-for-the-return.asciidoc[]

include::reset-transaction-timeout-of-an-open-transaction.asciidoc[]

include::commit-an-open-transaction.asciidoc[]

include::rollback-an-open-transaction.asciidoc[]

include::include-query-statistics.asciidoc[]

include::return-results-in-graph-format.asciidoc[]

include::handling-errors.asciidoc[]

include::transactional-status-codes.asciidoc[]

