module remote_neo4j
{
    interface RemoteConnection
    {
    	// TODO: implement this...
    	// Can we generate this from the original Java interface?
    	// - Perhaps with annotation processing?
    };
    
    interface RemoteSite
    {
    	RemoteConnection connect ();
    	RemoteConnection connectAuth (in string username, in string password);
    };
};