#!/bin/sh

USAGE="Usage: $0 -p <pidfile>"
NEO4J_HOME="`dirname $0`/.."

die() {
  echo $1
  exit 1
}

while getopts “hp:” OPTION; do
     case $OPTION in
         h)
             echo $USAGE
             exit 1
             ;;
          p)
             PID_FILE=$OPTARG
             ;;

        esac
done

[ -n "$PID_FILE" ] || die "$USAGE"

cd $NEO4J_HOME

CLASSPATH=`find $NEO4J_HOME -name '*.jar' | xargs echo | tr ' ' ':'`

java -cp "${CLASSPATH}" \
        -Dfile.encoding=UTF-8 \
        -Dorg.neo4j.config.file=conf/neo4j.conf \
        #{neo4j.mainClass} > /var/log/neo4j/console.log 2>&1 &

echo $! > $PID_FILE

