[preface]
[[preface]]
Preface
=======

This is the reference manual for Neo4j version {neo4j-version}, written by the Neo4j Team.

The main parts of the manual are:

* <<introduction>> -- introducing graph database concepts and Neo4j.
* <<tutorials>> -- learn how to use Neo4j.
* <<reference-documentation>> -- detailed information on Neo4j.
* <<operations>> -- how to install and maintain Neo4j.
* <<tools>> -- guides on tools.
* <<community>> -- getting help from, contributing to.
* <<manpages>> -- command line documentation.
* <<questions>> -- common questions.

The material is practical, technical, and focused on answering specific questions. 
It addresses how things work, what to do and what to avoid to successfully run Neo4j in a production environment.
 
The goal is to be thumb-through and rule-of-thumb friendly.

Each section should stand on its own, so you can hop right to whatever interests you.
When possible, the sections distill "rules of thumb" which you can keep in mind whenever you wander out of the house without this manual in your back pocket.

The included code examples are executed when Neo4j is built and tested.
Also, the REST API request and response examples are captured from real interaction with a Neo4j server.
Thus, the examples are always in sync with Neo4j.


_Who should read this?_

The topics should be relevant to architects, administrators, developers and operations personnel.

