package org.neo4j.impl.persistence;

public enum Operation
{
	LOAD_LIGHT_NODE,
	LOAD_NODE_PROPERTIES,
	LOAD_REL_PROPERTIES,
	LOAD_RELATIONSHIPS,
	LOAD_PROPERTY_VALUE,
	LOAD_PROPERTY_INDEX,
	LOAD_PROPERTY_INDEXES,
	LOAD_LIGHT_REL,
	LOAD_ALL_RELATIONSHIP_TYPES
}
