[[cypher-parameters]]
= Parameters =

Cypher supports querying with parameters.
This means developers don't have to resort to string building to create a query.
In addition to that, it also makes caching of execution plans much easier for Cypher.

Parameters can be used for literals and expressions in the +WHERE+ clause, for the index value in the +START+ clause, index queries, and finally for node/relationship ids.
Parameters can not be used as for property names, relationship types and labels, since these patterns are part of the query structure that is compiled into a query plan.

Accepted names for parameter are letters and number, and any combination of these.

For details on parameters when using the Neo4j embedded Java API, see <<tutorials-cypher-parameters-java>>.
For details on using parameters via the Neo4j REST API, see <<rest-api-cypher,Cypher queries via REST>>.

Below follows a comprehensive set of examples of parameter usage.
The parameters are given as JSON here.
Exactly how to submit them depends on the driver in use.

== Parameter for node id == 

include::includes/exampleWithParameterForNodeId.asciidoc[]

== Parameter for multiple node ids ==

include::includes/exampleWithParameterForMultipleNodeIds.asciidoc[]

== Parameter for string literal ==

include::includes/exampleWithStringLiteralAsParameter.asciidoc[]

== Parameter for index value ==

include::includes/exampleWithParameterForIndexValue.asciidoc[]

== Parameter for index query ==

include::includes/exampleWithParametersForQuery.asciidoc[]

== Numeric parameters for SKIP and LIMIT ==

include::includes/exampleWithParameterForSkipLimit.asciidoc[]

== Parameter for regular expression ==

include::includes/exampleWithParameterRegularExpression.asciidoc[]

== Parameter setting properties on node ==

include::includes/set_properties_on_a_node_from_a_map.asciidoc[]


