= Neo4j Browser =

*Explore the graph, one query at a time.*

Neo4j Browser is http://github.com/neo4j/neo4j/[Neo4j's] built-in client application, a mashup of a REPL, data visualization and lightweight IDE.

== Goals ==

* developer focused
* every interaction is a demonstration
* uses only public APIs
* for modern browsers, with reasonable fallbacks

== Development ==

Set up your environment::

  * Install https://nodejs.org/[node.js]
  * `cd community/browser && npm install`
+
This installs npm modules needed to build the browser code.
  * `npm install -g grunt-cli`
+
This puts the `grunt` command on your path.

Run in development mode::

  * Run Neo4j server (from a downloaded distribution of Neo4j, or from your IDE)
  * `cd community/browser` (this directory in the source tree)
  * `grunt server`
+
This listens on port 9000, serving up static documents, and forwarding other requests to Neo4j on port 7474. 
Any local changes to the browser code will be applied immediatley by reloading the page.

== Feedback ==

* mailto:andreas@neotechnology.com[Andreas Kollegger] - questions or comments? send an email to me

== Adding a new Cypher keyword ==

Look at:

* Detecting Cypher: app/scripts/init/commandInterpreters.coffee
* app/components/cypher/index.js
* app/scripts/codemirror-cypher.coffee
