= Utilizing Data Structures

Cypher can create and consume more complex data structures out of the box.
As already mentioned you can create literal lists (`[1,2,3]`) and maps (`{name: value}`) within a statement.

There is a number of functions that work with lists, from simple ones like `length(list)` that returns the size of a list to 

// missing content here

[source,cypher]
----
MATCH (m:Movie)<-[:ACTED_IN]-(a:Person)
RETURN m.title as movie, collect(a.name)[0..5] as five_of_cast
----

//table

You can also access individual elements or slices of a list quickly with `list[1]` or `list[5..-5]`.
Other functions to access parts of a list are `head(list)`, `tail(list)` and `last(list)`.

== List Predicates

When using lists and arrays in comparisons you can use predicates like `value IN list` or `any(x IN list WHERE x = value)`.
There are list predicates to satisfy conditions for `all`, `any`, `none` and `single` elements.

[source,cypher]
----
MATCH path = (:Person)-->(:Movie)<--(:Person)
WHERE all(r in rels(path) WHERE type(r) = 'ACTED_IN')
AND any(n in nodes(path) WHERE n.name = 'Clint Eastwood')
RETURN path
----

//table

== List Processing

Oftentimes you want to process lists to `filter`, aggregate (`reduce`) or transform (`extract`) their values.
Those transformations can be done within Cypher or in the calling code.
This kind of list-processing can reduce the amount of data handled and returned, so it might make sense to do it within the Cypher statement.

A simple, non-graph example would be:

[source,cypher]
----
WITH range(1,10) as numbers
WITH extract(n in numbers | n*n) as squares
WITH filter(n in squares WHERE n > 25) as large_squares
RETURN reduce( a = 0, n in large_squares | a + n ) as sum_large_squares
----

//table

In a graph-query you can filter or aggregate collected values instead or work on array properties.
// need to be rephrased somehow

[source,cypher]
----
MATCH (m:Movie)<-[r:ACTED_IN]-(a:Person)
WITH m.title as movie, collect({name: a.name, roles: r.roles}) as cast
RETURN movie, extract(c2 IN filter(c1 IN cast WHERE c1.name =~ "T.*") | c2.roles )
----

//table

Cypher offers to create and consume more complex data structures out of the box. 
As already mentioned you can create literal lists (`[1,2,3]`) and maps (`{name: value}`) within your statement.

There is a number of functions to work with lists, from simple ones like `length(list)` that returns the size of a list to 

[source,cypher]
----
MATCH (m:Movie)<-[:ACTED_IN]-(a:Person)
RETURN m.title as movie, collect(a.name)[0..5] as five_of_cast
----

//table

You can also access individual elements or slices of a list quickly with `list[1]` or `list[5..-5]`.
Other functions to access parts of a list are `head(list)`, `tail(list)` and `last(list)`.

== Unwind Lists

Sometimes you have collected information into a list, but want to use each element individually as a row.
For instance, you might want to further match patterns in the graph.
Or you passed in a collection of values but now want to create or match a node or relationship for each element.
Then you can use the `UNWIND` clause to unroll a list into a sequence of rows again.

For instance, a query to find the top 5-co-actors and then follow their movies and again list the cast for each of those movies:

[source,cypher]
----
MATCH (a:Person)-[:ACTED_IN]->(m:Movie)<-[:ACTED_IN]-(colleague:Person)
WITH colleague, count(*) as frequency, collect(distinct m) as movies
ORDER BY frequency DESC
LIMIT 5
UNWIND movies as m
MATCH (m)<-[:ACTED_IN]-(a)
RETURN m.title as movie, collect(a.name) as cast
----

//table


