#!/usr/bin/env bash

NEO4J_BIN=/usr/share/neo4j/bin
SCRIPT_NAME="$(basename "$0")"
SCRIPT_PATH=""${NEO4J_BIN}"/"${SCRIPT_NAME}""

[ -r /etc/default/neo4j ] && . /etc/default/neo4j

NEO4J_HOME="${NEO4J_HOME:-/usr/share/neo4j}" NEO4J_CONF="${NEO4J_CONF:-/etc/neo4j}" exec "${SCRIPT_PATH}" "$@"
