/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [https://neo4j.com]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.neo4j.cypher.internal.parser.v6.ast.factory

import org.neo4j.cypher.internal.ast.factory.neo4j.completion.CodeCompletionCore.CandidatesCollection
import org.neo4j.cypher.internal.parser.CypherErrorVocabulary
import org.neo4j.cypher.internal.parser.v6.Cypher6Parser
import org.neo4j.cypher.internal.util.test_helpers.CypherFunSuite

class Cypher6VocabularyTest extends CypherFunSuite {
  val conf = new Cypher6ErrorStrategyConf
  val vocab = new CypherErrorVocabulary(conf)

  test("user facing token names are human readable") {
    Range.inclusive(1, vocab.getMaxTokenType).foreach { token =>
      val displayName = vocab.getDisplayName(token)
      val symbolicName = vocab.getSymbolicName(token)
      val literalName = vocab.getLiteralName(token)
      withClue(s"displayName=$displayName, symbolicName=$symbolicName, literalName=$literalName\n") {
        expectedDisplayNames.get(token) match {
          case Some(expected) =>
            if (displayName != expected) println(token)
            displayName shouldBe expected
          case _ => fail(
              s"""Hello! I can see that you have added a new token type ($symbolicName)
                 |You need to add an expected display name in ${getClass.getName}.
                 |The reason why we fail for every new token here is that these names
                 |are user facing and we want to make sure all have a readable name.
                 |""".stripMargin
            )
        }
      }
    }
  }

  test("rules of interest have a display name") {
    conf.preferredRules.foreach { r =>
      withClue(Cypher6Parser.ruleNames(r))(ruleDisplayName(r) should not be empty)
    }
    Range(0, Cypher6Parser.ruleNames.length).foreach { r =>
      withClue(Cypher6Parser.ruleNames(r))(ruleDisplayName(r) shouldBe expectedRuleDisplayNames.get(r).toSeq)
    }
  }

  private def ruleDisplayName(r: Int): Seq[String] = {
    val candidates = new CandidatesCollection()
    candidates.rules.put(java.lang.Integer.valueOf(r), java.util.List.of[java.lang.Integer]())
    vocab.expected(candidates)
  }

  private val expectedDisplayNames: Map[Int, String] = Map(
    Cypher6Parser.SPACE -> "' '",
    Cypher6Parser.SINGLE_LINE_COMMENT -> "'//'",
    Cypher6Parser.DECIMAL_DOUBLE -> "a float value",
    Cypher6Parser.UNSIGNED_DECIMAL_INTEGER -> "an integer value",
    Cypher6Parser.UNSIGNED_HEX_INTEGER -> "a hexadecimal integer value",
    Cypher6Parser.UNSIGNED_OCTAL_INTEGER -> "an octal integer value",
    Cypher6Parser.ACCESS -> "'ACCESS'",
    Cypher6Parser.ACTIVE -> "'ACTIVE'",
    Cypher6Parser.ADMIN -> "'ADMIN'",
    Cypher6Parser.ADMINISTRATOR -> "'ADMINISTRATOR'",
    Cypher6Parser.ALIAS -> "'ALIAS'",
    Cypher6Parser.ALIASES -> "'ALIASES'",
    Cypher6Parser.ALL_SHORTEST_PATHS -> "'allShortestPaths'",
    Cypher6Parser.ALL -> "'ALL'",
    Cypher6Parser.ALTER -> "'ALTER'",
    Cypher6Parser.AND -> "'AND'",
    Cypher6Parser.ANY -> "'ANY'",
    Cypher6Parser.ARRAY -> "'ARRAY'",
    Cypher6Parser.AS -> "'AS'",
    Cypher6Parser.ASC -> "'ASC'",
    Cypher6Parser.ASCENDING -> "'ASCENDING'",
    Cypher6Parser.ASSIGN -> "'ASSIGN'",
    Cypher6Parser.AT -> "'AT'",
    Cypher6Parser.AUTH -> "'AUTH'",
    Cypher6Parser.BAR -> "'|'",
    Cypher6Parser.BINDINGS -> "'BINDINGS'",
    Cypher6Parser.BOOL -> "'BOOL'",
    Cypher6Parser.BOOLEAN -> "'BOOLEAN'",
    Cypher6Parser.BOOSTED -> "'BOOSTED'",
    Cypher6Parser.BOTH -> "'BOTH'",
    Cypher6Parser.BREAK -> "'BREAK'",
    Cypher6Parser.BTREE -> "'BTREE'",
    Cypher6Parser.BUILT -> "'BUILT'",
    Cypher6Parser.BY -> "'BY'",
    Cypher6Parser.CALL -> "'CALL'",
    Cypher6Parser.CASCADE -> "'CASCADE'",
    Cypher6Parser.CASE -> "'CASE'",
    Cypher6Parser.CHANGE -> "'CHANGE'",
    Cypher6Parser.CIDR -> "'CIDR'",
    Cypher6Parser.COLLECT -> "'COLLECT'",
    Cypher6Parser.COLON -> "':'",
    Cypher6Parser.COLONCOLON -> "'::'",
    Cypher6Parser.COMMA -> "','",
    Cypher6Parser.COMMAND -> "'COMMAND'",
    Cypher6Parser.COMMANDS -> "'COMMANDS'",
    Cypher6Parser.COMPOSITE -> "'COMPOSITE'",
    Cypher6Parser.CONCURRENT -> "'CONCURRENT'",
    Cypher6Parser.CONSTRAINT -> "'CONSTRAINT'",
    Cypher6Parser.CONSTRAINTS -> "'CONSTRAINTS'",
    Cypher6Parser.CONTAINS -> "'CONTAINS'",
    Cypher6Parser.COPY -> "'COPY'",
    Cypher6Parser.CONTINUE -> "'CONTINUE'",
    Cypher6Parser.COUNT -> "'COUNT'",
    Cypher6Parser.CREATE -> "'CREATE'",
    Cypher6Parser.CSV -> "'CSV'",
    Cypher6Parser.CURRENT -> "'CURRENT'",
    Cypher6Parser.DATA -> "'DATA'",
    Cypher6Parser.DATABASE -> "'DATABASE'",
    Cypher6Parser.DATABASES -> "'DATABASES'",
    Cypher6Parser.DATE -> "'DATE'",
    Cypher6Parser.DATETIME -> "'DATETIME'",
    Cypher6Parser.DBMS -> "'DBMS'",
    Cypher6Parser.DEALLOCATE -> "'DEALLOCATE'",
    Cypher6Parser.DEFAULT -> "'DEFAULT'",
    Cypher6Parser.DEFINED -> "'DEFINED'",
    Cypher6Parser.DELETE -> "'DELETE'",
    Cypher6Parser.DENY -> "'DENY'",
    Cypher6Parser.DESC -> "'DESC'",
    Cypher6Parser.DESCENDING -> "'DESCENDING'",
    Cypher6Parser.DESTROY -> "'DESTROY'",
    Cypher6Parser.DETACH -> "'DETACH'",
    Cypher6Parser.DIFFERENT -> "'DIFFERENT'",
    Cypher6Parser.DOLLAR -> "'$'",
    Cypher6Parser.DISTINCT -> "'DISTINCT'",
    Cypher6Parser.DIVIDE -> "'/'",
    Cypher6Parser.DOT -> "'.'",
    Cypher6Parser.DOTDOT -> "'..'",
    Cypher6Parser.DOUBLEBAR -> "'||'",
    Cypher6Parser.DRIVER -> "'DRIVER'",
    Cypher6Parser.DROP -> "'DROP'",
    Cypher6Parser.DRYRUN -> "'DRYRUN'",
    Cypher6Parser.DUMP -> "'DUMP'",
    Cypher6Parser.DURATION -> "'DURATION'",
    Cypher6Parser.EACH -> "'EACH'",
    Cypher6Parser.EDGE -> "'EDGE'",
    Cypher6Parser.ENABLE -> "'ENABLE'",
    Cypher6Parser.ELEMENT -> "'ELEMENT'",
    Cypher6Parser.ELEMENTS -> "'ELEMENTS'",
    Cypher6Parser.ELSE -> "'ELSE'",
    Cypher6Parser.ENCRYPTED -> "'ENCRYPTED'",
    Cypher6Parser.END -> "'END'",
    Cypher6Parser.ENDS -> "'ENDS'",
    Cypher6Parser.EQ -> "'='",
    Cypher6Parser.ErrorChar -> "'ErrorChar'",
    Cypher6Parser.EXECUTABLE -> "'EXECUTABLE'",
    Cypher6Parser.EXECUTE -> "'EXECUTE'",
    Cypher6Parser.EXIST -> "'EXIST'",
    Cypher6Parser.EXISTENCE -> "'EXISTENCE'",
    Cypher6Parser.EXISTS -> "'EXISTS'",
    Cypher6Parser.ERROR -> "'ERROR'",
    Cypher6Parser.FAIL -> "'FAIL'",
    Cypher6Parser.FALSE -> "'FALSE'",
    Cypher6Parser.FIELDTERMINATOR -> "'FIELDTERMINATOR'",
    Cypher6Parser.FINISH -> "'FINISH'",
    Cypher6Parser.FLOAT -> "'FLOAT'",
    Cypher6Parser.FOR -> "'FOR'",
    Cypher6Parser.FOREACH -> "'FOREACH'",
    Cypher6Parser.FROM -> "'FROM'",
    Cypher6Parser.FULLTEXT -> "'FULLTEXT'",
    Cypher6Parser.FUNCTION -> "'FUNCTION'",
    Cypher6Parser.FUNCTIONS -> "'FUNCTIONS'",
    Cypher6Parser.GE -> "'>='",
    Cypher6Parser.GRANT -> "'GRANT'",
    Cypher6Parser.GRAPH -> "'GRAPH'",
    Cypher6Parser.GRAPHS -> "'GRAPHS'",
    Cypher6Parser.GROUP -> "'GROUP'",
    Cypher6Parser.GROUPS -> "'GROUPS'",
    Cypher6Parser.GT -> "'>'",
    Cypher6Parser.HEADERS -> "'HEADERS'",
    Cypher6Parser.HOME -> "'HOME'",
    Cypher6Parser.ID -> "'ID'",
    Cypher6Parser.IF -> "'IF'",
    Cypher6Parser.IMPERSONATE -> "'IMPERSONATE'",
    Cypher6Parser.IMMUTABLE -> "'IMMUTABLE'",
    Cypher6Parser.IN -> "'IN'",
    Cypher6Parser.INDEX -> "'INDEX'",
    Cypher6Parser.INDEXES -> "'INDEXES'",
    Cypher6Parser.INF -> "'INF'",
    Cypher6Parser.INFINITY -> "'INFINITY'",
    Cypher6Parser.INSERT -> "'INSERT'",
    Cypher6Parser.INT -> "'INT'",
    Cypher6Parser.INTEGER -> "'INTEGER'",
    Cypher6Parser.IS -> "'IS'",
    Cypher6Parser.JOIN -> "'JOIN'",
    Cypher6Parser.KEY -> "'KEY'",
    Cypher6Parser.LABEL -> "'LABEL'",
    Cypher6Parser.LABELS -> "'LABELS'",
    Cypher6Parser.AMPERSAND -> "'&'",
    Cypher6Parser.EXCLAMATION_MARK -> "'!'",
    Cypher6Parser.LBRACKET -> "'['",
    Cypher6Parser.LCURLY -> "'{'",
    Cypher6Parser.LE -> "'<='",
    Cypher6Parser.LEADING -> "'LEADING'",
    Cypher6Parser.LIMITROWS -> "'LIMIT'",
    Cypher6Parser.LIST -> "'LIST'",
    Cypher6Parser.LOAD -> "'LOAD'",
    Cypher6Parser.LOCAL -> "'LOCAL'",
    Cypher6Parser.LOOKUP -> "'LOOKUP'",
    Cypher6Parser.LPAREN -> "'('",
    Cypher6Parser.LT -> "'<'",
    Cypher6Parser.MANAGEMENT -> "'MANAGEMENT'",
    Cypher6Parser.MAP -> "'MAP'",
    Cypher6Parser.MATCH -> "'MATCH'",
    Cypher6Parser.MERGE -> "'MERGE'",
    Cypher6Parser.MINUS -> "'-'",
    Cypher6Parser.PERCENT -> "'%'",
    Cypher6Parser.INVALID_NEQ -> "'!='",
    Cypher6Parser.NEQ -> "'<>'",
    Cypher6Parser.NAME -> "'NAME'",
    Cypher6Parser.NAMES -> "'NAMES'",
    Cypher6Parser.NAN -> "'NAN'",
    Cypher6Parser.NFC -> "'NFC'",
    Cypher6Parser.NFD -> "'NFD'",
    Cypher6Parser.NFKC -> "'NFKC'",
    Cypher6Parser.NFKD -> "'NFKD'",
    Cypher6Parser.NEW -> "'NEW'",
    Cypher6Parser.NODE -> "'NODE'",
    Cypher6Parser.NODETACH -> "'NODETACH'",
    Cypher6Parser.NODES -> "'NODES'",
    Cypher6Parser.NONE -> "'NONE'",
    Cypher6Parser.NORMALIZE -> "'NORMALIZE'",
    Cypher6Parser.NORMALIZED -> "'NORMALIZED'",
    Cypher6Parser.NOT -> "'NOT'",
    Cypher6Parser.NOTHING -> "'NOTHING'",
    Cypher6Parser.NOWAIT -> "'NOWAIT'",
    Cypher6Parser.NULL -> "'NULL'",
    Cypher6Parser.OF -> "'OF'",
    Cypher6Parser.OFFSET -> "'OFFSET'",
    Cypher6Parser.ON -> "'ON'",
    Cypher6Parser.ONLY -> "'ONLY'",
    Cypher6Parser.OPTIONAL -> "'OPTIONAL'",
    Cypher6Parser.OPTIONS -> "'OPTIONS'",
    Cypher6Parser.OPTION -> "'OPTION'",
    Cypher6Parser.OR -> "'OR'",
    Cypher6Parser.ORDER -> "'ORDER'",
    Cypher6Parser.PASSWORD -> "'PASSWORD'",
    Cypher6Parser.PASSWORDS -> "'PASSWORDS'",
    Cypher6Parser.PATH -> "'PATH'",
    Cypher6Parser.PATHS -> "'PATHS'",
    Cypher6Parser.PLAINTEXT -> "'PLAINTEXT'",
    Cypher6Parser.PLUS -> "'+'",
    Cypher6Parser.PLUSEQUAL -> "'+='",
    Cypher6Parser.POINT -> "'POINT'",
    Cypher6Parser.POPULATED -> "'POPULATED'",
    Cypher6Parser.POW -> "'^'",
    Cypher6Parser.PRIMARY -> "'PRIMARY'",
    Cypher6Parser.PRIMARIES -> "'PRIMARIES'",
    Cypher6Parser.PRIVILEGE -> "'PRIVILEGE'",
    Cypher6Parser.PRIVILEGES -> "'PRIVILEGES'",
    Cypher6Parser.PROCEDURE -> "'PROCEDURE'",
    Cypher6Parser.PROCEDURES -> "'PROCEDURES'",
    Cypher6Parser.PROPERTIES -> "'PROPERTIES'",
    Cypher6Parser.PROPERTY -> "'PROPERTY'",
    Cypher6Parser.PROVIDER -> "'PROVIDER'",
    Cypher6Parser.PROVIDERS -> "'PROVIDERS'",
    Cypher6Parser.QUESTION -> "'?'",
    Cypher6Parser.RANGE -> "'RANGE'",
    Cypher6Parser.RBRACKET -> "']'",
    Cypher6Parser.RCURLY -> "'}'",
    Cypher6Parser.READ -> "'READ'",
    Cypher6Parser.REALLOCATE -> "'REALLOCATE'",
    Cypher6Parser.REDUCE -> "'REDUCE'",
    Cypher6Parser.RENAME -> "'RENAME'",
    Cypher6Parser.REGEQ -> "'=~'",
    Cypher6Parser.REL -> "'REL'",
    Cypher6Parser.RELATIONSHIP -> "'RELATIONSHIP'",
    Cypher6Parser.RELATIONSHIPS -> "'RELATIONSHIPS'",
    Cypher6Parser.REMOVE -> "'REMOVE'",
    Cypher6Parser.REPEATABLE -> "'REPEATABLE'",
    Cypher6Parser.REPLACE -> "'REPLACE'",
    Cypher6Parser.REPORT -> "'REPORT'",
    Cypher6Parser.REQUIRE -> "'REQUIRE'",
    Cypher6Parser.REQUIRED -> "'REQUIRED'",
    Cypher6Parser.RESTRICT -> "'RESTRICT'",
    Cypher6Parser.RETURN -> "'RETURN'",
    Cypher6Parser.REVOKE -> "'REVOKE'",
    Cypher6Parser.ROLE -> "'ROLE'",
    Cypher6Parser.ROLES -> "'ROLES'",
    Cypher6Parser.ROW -> "'ROW'",
    Cypher6Parser.ROWS -> "'ROWS'",
    Cypher6Parser.RPAREN -> "')'",
    Cypher6Parser.SCAN -> "'SCAN'",
    Cypher6Parser.SECONDARY -> "'SECONDARY'",
    Cypher6Parser.SECONDARIES -> "'SECONDARIES'",
    Cypher6Parser.SEC -> "'SEC'",
    Cypher6Parser.SECOND -> "'SECOND'",
    Cypher6Parser.SECONDS -> "'SECONDS'",
    Cypher6Parser.SEEK -> "'SEEK'",
    Cypher6Parser.SEMICOLON -> "';'",
    Cypher6Parser.SERVER -> "'SERVER'",
    Cypher6Parser.SERVERS -> "'SERVERS'",
    Cypher6Parser.SET -> "'SET'",
    Cypher6Parser.SETTING -> "'SETTING'",
    Cypher6Parser.SETTINGS -> "'SETTINGS'",
    Cypher6Parser.SHORTEST_PATH -> "'shortestPath'",
    Cypher6Parser.SHORTEST -> "'SHORTEST'",
    Cypher6Parser.SHOW -> "'SHOW'",
    Cypher6Parser.SIGNED -> "'SIGNED'",
    Cypher6Parser.SINGLE -> "'SINGLE'",
    Cypher6Parser.SKIPROWS -> "'SKIP'",
    Cypher6Parser.START -> "'START'",
    Cypher6Parser.STARTS -> "'STARTS'",
    Cypher6Parser.STATUS -> "'STATUS'",
    Cypher6Parser.STOP -> "'STOP'",
    Cypher6Parser.STRING -> "'STRING'",
    Cypher6Parser.SUPPORTED -> "'SUPPORTED'",
    Cypher6Parser.SUSPENDED -> "'SUSPENDED'",
    Cypher6Parser.TARGET -> "'TARGET'",
    Cypher6Parser.TERMINATE -> "'TERMINATE'",
    Cypher6Parser.TEXT -> "'TEXT'",
    Cypher6Parser.THEN -> "'THEN'",
    Cypher6Parser.TIME -> "'TIME'",
    Cypher6Parser.TIMES -> "'*'",
    Cypher6Parser.TIMESTAMP -> "'TIMESTAMP'",
    Cypher6Parser.TIMEZONE -> "'TIMEZONE'",
    Cypher6Parser.TO -> "'TO'",
    Cypher6Parser.TOPOLOGY -> "'TOPOLOGY'",
    Cypher6Parser.TRAILING -> "'TRAILING'",
    Cypher6Parser.TRANSACTION -> "'TRANSACTION'",
    Cypher6Parser.TRANSACTIONS -> "'TRANSACTIONS'",
    Cypher6Parser.TRAVERSE -> "'TRAVERSE'",
    Cypher6Parser.TRIM -> "'TRIM'",
    Cypher6Parser.TRUE -> "'TRUE'",
    Cypher6Parser.TYPE -> "'TYPE'",
    Cypher6Parser.TYPED -> "'TYPED'",
    Cypher6Parser.TYPES -> "'TYPES'",
    Cypher6Parser.UNION -> "'UNION'",
    Cypher6Parser.UNIQUE -> "'UNIQUE'",
    Cypher6Parser.UNIQUENESS -> "'UNIQUENESS'",
    Cypher6Parser.UNWIND -> "'UNWIND'",
    Cypher6Parser.URL -> "'URL'",
    Cypher6Parser.USE -> "'USE'",
    Cypher6Parser.USER -> "'USER'",
    Cypher6Parser.USERS -> "'USERS'",
    Cypher6Parser.USING -> "'USING'",
    Cypher6Parser.VALUE -> "'VALUE'",
    Cypher6Parser.VARCHAR -> "'VARCHAR'",
    Cypher6Parser.VECTOR -> "'VECTOR'",
    Cypher6Parser.VERTEX -> "'VERTEX'",
    Cypher6Parser.WAIT -> "'WAIT'",
    Cypher6Parser.WHEN -> "'WHEN'",
    Cypher6Parser.WHERE -> "'WHERE'",
    Cypher6Parser.WITH -> "'WITH'",
    Cypher6Parser.WITHOUT -> "'WITHOUT'",
    Cypher6Parser.WRITE -> "'WRITE'",
    Cypher6Parser.XOR -> "'XOR'",
    Cypher6Parser.YIELD -> "'YIELD'",
    Cypher6Parser.ZONE -> "'ZONE'",
    Cypher6Parser.ZONED -> "'ZONED'",
    Cypher6Parser.EXTENDED_IDENTIFIER -> "an identifier",
    Cypher6Parser.IDENTIFIER -> "an identifier",
    Cypher6Parser.ARROW_LINE -> "'-'",
    Cypher6Parser.ARROW_LEFT_HEAD -> "'<'",
    Cypher6Parser.ARROW_RIGHT_HEAD -> "'>'",
    Cypher6Parser.STRING_LITERAL1 -> "a string value",
    Cypher6Parser.STRING_LITERAL2 -> "a string value",
    Cypher6Parser.MULTI_LINE_COMMENT -> "'/*'",
    Cypher6Parser.ESCAPED_SYMBOLIC_NAME -> "an identifier"
  )

  private val expectedRuleDisplayNames: Map[Int, String] = Map(
    Cypher6Parser.RULE_expression -> "an expression",
    Cypher6Parser.RULE_expression1 -> "an expression",
    Cypher6Parser.RULE_expression2 -> "an expression",
    Cypher6Parser.RULE_expression3 -> "an expression",
    Cypher6Parser.RULE_expression4 -> "an expression",
    Cypher6Parser.RULE_expression5 -> "an expression",
    Cypher6Parser.RULE_expression6 -> "an expression",
    Cypher6Parser.RULE_expression7 -> "an expression",
    Cypher6Parser.RULE_expression8 -> "an expression",
    Cypher6Parser.RULE_expression9 -> "an expression",
    Cypher6Parser.RULE_expression10 -> "an expression",
    Cypher6Parser.RULE_expression11 -> "an expression",
    Cypher6Parser.RULE_pattern -> "a graph pattern",
    Cypher6Parser.RULE_numberLiteral -> "a number",
    Cypher6Parser.RULE_parameter -> "a parameter",
    Cypher6Parser.RULE_variable -> "a variable name",
    Cypher6Parser.RULE_symbolicAliasName -> "a database name",
    Cypher6Parser.RULE_stringLiteral -> "a string",
    Cypher6Parser.RULE_symbolicNameString -> "an identifier",
    Cypher6Parser.RULE_symbolicLabelNameString -> "an identifier",
    Cypher6Parser.RULE_escapedSymbolicNameString -> "an identifier",
    Cypher6Parser.RULE_unescapedSymbolicNameString -> "an identifier",
    Cypher6Parser.RULE_unescapedLabelSymbolicNameString -> "an identifier"
  )
}
