# Makefile for the Neo4j Manual.
#

# Project Configuration
project_name               = neo4j-manual
language                   = en

# Minimal setup
target                     = target
build_dir                  = $(CURDIR)/$(target)
config_dir                 = $(CURDIR)/conf
tools_dir                  = $(build_dir)/tools
make_dir                   = $(tools_dir)/make

include $(make_dir)/context-manual.make


