About Neo4j Manual
==================

The documents use the asciidoc format, see:

* http://www.methods.co.nz/asciidoc/
* http://powerman.name/doc/asciidoc

== Building the documentation ==

Asciidoc version 8.6.3 is a requirement
together with whatever dependencies it needs
and specifically docbook, w3m, fop and graphviz.

http://maven.apache.org/[Apache Maven] together with http://www.gnu.org/software/make/[Make] are used to unpack the pieces of the manual and to execute asciidoc on them.
Note that running parallel jobs with Make (-j option) is not supported.

To build the documentation, use: +
`mvn clean install`

To perform a faster check of the document structure and to see if snippets and images are correctly resolved, use:
`mvn clean compile -Dcheck`
which will only produce html for offline use and text outputs (including the manpages).
Note that this profile can't be used together with the `package` goal.

=== With brew on OSX ===

  brew install docbook asciidoc w3m fop graphviz

  sudo docbook-register

=== With apt-get on Ubuntu ===

  sudo apt-get install asciidoc docbook fop graphviz w3m maven libxml2-utils



