= About Neo4j Manual =

The documents use the asciidoc format, see:

* http://www.methods.co.nz/asciidoc/
* http://powerman.name/doc/asciidoc

== Building the documentation ==

Asciidoc version 8.6.8 is a requirement
together with whatever dependencies it needs
and specifically docbook, w3m, fop and graphviz.

http://maven.apache.org/[Apache Maven] together with http://www.gnu.org/software/make/[Make] are used to unpack the pieces of the manual and to execute asciidoc on them.
Note that running parallel jobs with Make (-j option) is not supported.

To build the documentation, use: +
`mvn clean install` +
This will produce a single html5 page (in 'target/html5').
Note that this won't suffice in order to build the download packages of Neo4j.
However, the build requirements are limited to Python and Graphviz (and Maven, Java).
This build checks for missing include files and AsciiDoc syntax errors.

To build all artifacts, use: +
`mvn clean install -DfullBuild`
or +
`mvn clean install -DfullManualBuild`

To build all dependencies of the manual, use the following at the top level of the repository: +
`mvn clean install -DdocsBuild` +
In order to build all the artifacts of the manual too, add `-DfullManualBuild`

=== With brew on OSX ===

Install libraries

  brew install docbook asciidoc w3m fop graphviz libtool

Register the docbook xml DTD

  sudo ./osx-docbook-register

=== With apt-get on Ubuntu ===

  sudo apt-get install asciidoc docbook fop graphviz w3m maven libxml2-utils xsltproc



