[[match-unbound-nodes-exceptions]]

== Exceptional behaviors around unbound nodes ==

If you look at <<match-optional-relationship>>, some of the nodes of the matched patterns may be unbound nodes.
More technically, any node that is only reachable from a start point via optional relationships is called an unbound node.

Generally unbound nodes are treated as +null+ when they are not matched, but treating them differently in a few situations helps keeping queries short and concise:

* Two unbound nodes are never equal, but unbound nodes are equal to +null+.
  This is convenient for checking if a node is bound.
* Getting properties from an unbound node returns +null+.
* Any write clauses that use unbound nodes will have no effect.
  This means that if you use optional relationships, only matches where all nodes are bound will update the graph.

Additionally, expressions that take unbound nodes as an argument behave as if called with +null+, except:

* Checking if a label is present on an unbound node is always true.
* Calling +labels+ on an unbound node returns +null+.
* Calling +str+ on an unbound node returns +"UNBOUND_VALUE"+.


