[[deployment-requirements]]
System Requirements
===================

Memory constrains graph size, disk I/O constrains read/write performance, as always. 

== CPU ==

Performance is generally memory or I/O bound for large graphs, and compute bound for graphs which fit in memory.

Minimum::      Intel Core i3
Recommended::  Intel Core i7


== Memory ==

More memory allows even larger graphs, but runs the risk of inducing larger Garbage Collection operations.

Minimum::     2GB
Recommended:: 16--32GB or more

== Disk ==

Aside from capacity, the performance characteristics of the disk are the most important when selecting storage.

Minimum::     10GB SATA
Recommended:: SSD w/ SATA

== Filesystem ==

For proper ACID behavior, the filesystem must support flush (fsync, fdatasync).

Minimum::      ext4 (or similar)
Recommended::  ext4, ZFS

== Software ==

Neo4j is Java-based.

Java:: http://openjdk.java.net/[OpenJDK 7 or 8] or http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java 7 or 8]
Operating Systems::  Linux, HP UX, Windows 2012 for production; additionally Windows XP, Mac OS X for development.


