[[query-constraints]]
= Constraints

[abstract]
Neo4j helps enforce data integrity with the use of constraints.
There are two types of constraints, unique property constraints and mandatory property constraints.

You can use unique property constraints to ensure that property values are unique for all nodes with a specific label.
Unique constraints do not mean that all nodes have to have a unique value for the properties -- nodes without the property are not subject to this rule.

You can use mandatory property constraints to ensure that a property exists for all nodes with a specific label.
All queries that try to create new nodes without the property, or queries that try to remove the mandatory property will now fail.


You can have multiple constraints for a given label and you can also combine unique and mandatory property constraints on the same property.

Remember that adding constraints is an atomic operation that can take a while -- all existing data has to be scanned before Neo4j can turn the constraint ``on''.

Note that adding a unique property constraint on a property will also add an index on that property, so you cannot add such an index separately.
Cypher will use that index for lookups just like other indexes.
If you drop a unique property constraint and still want an index on the property, you will have to create the index.

include::create-uniqueness-constraint.asciidoc[]

include::drop-uniqueness-constraint.asciidoc[]

include::create-a-node-that-complies-with-unique-property-constraints.asciidoc[]

include::create-a-node-that-breaks-a-unique-property-constraint.asciidoc[]

include::failure-to-create-a-unique-property-constraint-due-to-conflicting-nodes.asciidoc[]

include::create-mandatory-property-constraint.asciidoc[]

include::drop-mandatory-property-constraint.asciidoc[]

include::create-a-node-that-complies-with-mandatory-property-constraints.asciidoc[]

include::create-a-node-that-breaks-a-mandatory-property-constraint.asciidoc[]

include::removing-a-mandatory-property.asciidoc[]

include::failure-to-create-a-mandatory-property-constraint-due-to-existing-node.asciidoc[]


