[[server-installation]]
Server Installation
===================

== Deployment Scenarios ==

As a developer, you may wish to download Neo4j and run it locally on your desktop computer.
We recommend this as an easy way to discover Neo4j.

* For Windows, see <<windows-install>>.
* For Unix/Linux, see <<linux-install>>.
* For OSX, see <<osx-install>>.

As a systems administrator, you may wish to install Neo4j using a packaging system so you can ensure that a cluster of machines have identical installs.
See <<linux-packages>> for more information on this.

For information on High Availability, please refer to <<ha>>.

== Prerequisites ==

With the exception of our Windows Installer, you'll need a Java Virtual Machine installed on your computer.
We recommend that you install http://openjdk.java.net/[OpenJDK 7] or http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java 7].

[[windows-install]]
== Windows ==

[[windows-installer]]
=== Windows Installer ===

1. Download the version that you want from http://neo4j.com/download/.
   * Select the appropriate version and architecture for your platform.
2. Double-click the downloaded installer file.
3. Follow the prompts.

[NOTE]
The installer will prompt to be granted Administrator privileges.
Newer versions of Windows come with a SmartScreen feature that may prevent the installer from running -- you can make it run anyway by clicking "More info" on the "Windows protected your PC" screen.

[TIP]
If you install Neo4j using the windows installer and you already have an existing Neo4j installed it will ask if you want to upgrade.
This should proceed without issue although some users have reported a `JRE is damaged` exception.
If you see this error simply install Neo4j into a different location.

[[windows-console]]
=== Windows Console Application ===
1. Download the latest release from http://neo4j.com/download/.
   * Select the appropriate Zip distribution.
2. Right-click the downloaded file, click Extract All.
   * Refer to the top-level extracted directory as: +NEO4J_HOME+
3. Double-click on '%NEO4J_HOME%\bin\Neo4j.bat'
4. Stop the server by typing Ctrl-C in the console that got opened.

[NOTE]
Some users have reported problems on Windows when using the ZoneAlarm firewall.
If you are having problems getting large responses from the server, or if the web interface does not work, try disabling ZoneAlarm.
Contact ZoneAlarm support to get information on how to resolve this.

[[linux-install]]
== Linux ==

[[linux-packages]]
=== Linux Packages ===

* For Debian packages, see the instructions at  http://debian.neo4j.org.

After installation you may have to do some platform specific configuration and performance tuning.
For that, refer to <<linux-performance-guide>>.

[[unix-console]]
=== Unix Console Application ===

1. Download the latest release from http://neo4j.com/download/.
   * Select the appropriate tar.gz distribution for your platform.
2. Extract the contents of the archive, using: `tar -xf <filename>`
   * Refer to the top-level extracted directory as: +NEO4J_HOME+
3. Change directory to: `$NEO4J_HOME`
   * Run: `./bin/neo4j console`
4. Stop the server by typing Ctrl-C in the console.

=== Linux Service ===

The `neo4j` command can also be used with `start`, `stop`, `restart` or `status` instead of `console`.
By using these actions, you can create a Neo4j service.
See the <<neo4j-manpage,neo4j man page>> for further details.

[CAUTION]
This approach to running Neo4j as a server is deprecated.
We strongly advise you to run Neo4j from a package where feasible.

You can build your own `init.d` script.
See for instance the Linux Standard Base specification on http://refspecs.linuxfoundation.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/tocsysinit.html[system initialization], or one of the many https://gist.github.com/chrisvest/7673244[samples] and http://www.linux.com/learn/tutorials/442412-managing-linux-daemons-with-init-scripts[tutorials].

[[osx-install]]
== Mac OSX ==

=== Running Neo4j from the Terminal ===

The server can be started in the background from the terminal with the command `neo4j start`, and then stopped again with `neo4j stop`.
The server can also be started in the foreground with `neo4j console` -- then it's log output will be printed to the terminal.

The `neo4j-shell` command can be used to interact with Neo4j from the command line using Cypher. It will automatically connect to any
server that is running on localhost with the default port, otherwise it will show a help message. You can alternatively start the
shell with an embedded Neo4j instance, by using the `-path path/to/data` argument -- note that only a single instance of Neo4j
can access the database files at a time.

=== OSX Service ===

Use the standard OSX system tools to create a service based on the `neo4j` command.

=== A note on Java on OS X Mavericks ===

Unlike previous versions, OS X Mavericks does not come with Java pre-installed. You might encounter that the first time you run Neo4j, where OS X will trigger a popup offering you to install Java SE 6.

Java SE 6 is incompatible with Neo4j {neo4j-version}, so we strongly advise you to skip installing Java SE 6 if you have no other uses for it. Instead, for Neo4j {neo4j-version} we recommend you install Java SE 7 from Oracle (http://www.oracle.com/technetwork/java/javase/downloads/index.html) as that is what we support for production use.

== Multiple Server instances on one machine ==

Neo4j can be set up to run as several instances on one machine, providing for instance several databases for development.

For how to set this up, see <<ha-local-cluster>>.
Just use the Neo4j edition of your choice, follow the guide and remember to not set the servers to run in HA mode.
