begin
  require 'rspec'
rescue LoadError
  puts "RSpec is not available. In order to run features, you must: sudo gem install rspec"
end

begin
    require 'cucumber/rake/task'
      Cucumber::Rake::Task.new(:features)
rescue LoadError
    puts "Cucumber is not available. In order to run features, you must: sudo gem install cucumber"
end

