/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [https://neo4j.com]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.neo4j.cypher.internal.parser.v6;

import org.antlr.v4.runtime.ParserRuleContext;

/**
 * Optimised implementation of Cypher6ParserListener.
 * Generated by org.neo4j.cypher.internal.parser.GenerateListenerMavenPlugin
 */
public abstract class AbstractCypher6AstBuilder implements Cypher6ParserListener {
    /**
     *
     * Optimised exit method.
     *
     * This compiles into a blazingly fast tableswitch (jump table)
     * and has been shown to be faster than the generated listeners that antlr provides.
     */
    @Override
    public final void exitEveryRule(ParserRuleContext ctx) {
        switch (ctx.getRuleIndex()) {
            case Cypher6Parser.RULE_statements -> exitStatements((Cypher6Parser.StatementsContext) ctx);
            case Cypher6Parser.RULE_statement -> exitStatement((Cypher6Parser.StatementContext) ctx);
            case Cypher6Parser.RULE_regularQuery -> exitRegularQuery((Cypher6Parser.RegularQueryContext) ctx);
            case Cypher6Parser.RULE_singleQuery -> exitSingleQuery((Cypher6Parser.SingleQueryContext) ctx);
            case Cypher6Parser.RULE_clause -> exitClause((Cypher6Parser.ClauseContext) ctx);
            case Cypher6Parser.RULE_useClause -> exitUseClause((Cypher6Parser.UseClauseContext) ctx);
            case Cypher6Parser.RULE_graphReference -> exitGraphReference((Cypher6Parser.GraphReferenceContext) ctx);
            case Cypher6Parser.RULE_finishClause -> exitFinishClause((Cypher6Parser.FinishClauseContext) ctx);
            case Cypher6Parser.RULE_returnClause -> exitReturnClause((Cypher6Parser.ReturnClauseContext) ctx);
            case Cypher6Parser.RULE_returnBody -> exitReturnBody((Cypher6Parser.ReturnBodyContext) ctx);
            case Cypher6Parser.RULE_returnItem -> exitReturnItem((Cypher6Parser.ReturnItemContext) ctx);
            case Cypher6Parser.RULE_returnItems -> exitReturnItems((Cypher6Parser.ReturnItemsContext) ctx);
            case Cypher6Parser.RULE_orderItem -> exitOrderItem((Cypher6Parser.OrderItemContext) ctx);
            case Cypher6Parser.RULE_ascToken -> exitAscToken((Cypher6Parser.AscTokenContext) ctx);
            case Cypher6Parser.RULE_descToken -> exitDescToken((Cypher6Parser.DescTokenContext) ctx);
            case Cypher6Parser.RULE_orderBy -> exitOrderBy((Cypher6Parser.OrderByContext) ctx);
            case Cypher6Parser.RULE_skip -> exitSkip((Cypher6Parser.SkipContext) ctx);
            case Cypher6Parser.RULE_limit -> exitLimit((Cypher6Parser.LimitContext) ctx);
            case Cypher6Parser.RULE_whereClause -> exitWhereClause((Cypher6Parser.WhereClauseContext) ctx);
            case Cypher6Parser.RULE_withClause -> exitWithClause((Cypher6Parser.WithClauseContext) ctx);
            case Cypher6Parser.RULE_createClause -> exitCreateClause((Cypher6Parser.CreateClauseContext) ctx);
            case Cypher6Parser.RULE_insertClause -> exitInsertClause((Cypher6Parser.InsertClauseContext) ctx);
            case Cypher6Parser.RULE_setClause -> exitSetClause((Cypher6Parser.SetClauseContext) ctx);
            case Cypher6Parser.RULE_setItem -> exitSetItem((Cypher6Parser.SetItemContext) ctx);
            case Cypher6Parser.RULE_removeClause -> exitRemoveClause((Cypher6Parser.RemoveClauseContext) ctx);
            case Cypher6Parser.RULE_removeItem -> exitRemoveItem((Cypher6Parser.RemoveItemContext) ctx);
            case Cypher6Parser.RULE_deleteClause -> exitDeleteClause((Cypher6Parser.DeleteClauseContext) ctx);
            case Cypher6Parser.RULE_matchClause -> exitMatchClause((Cypher6Parser.MatchClauseContext) ctx);
            case Cypher6Parser.RULE_matchMode -> exitMatchMode((Cypher6Parser.MatchModeContext) ctx);
            case Cypher6Parser.RULE_hint -> exitHint((Cypher6Parser.HintContext) ctx);
            case Cypher6Parser.RULE_mergeClause -> exitMergeClause((Cypher6Parser.MergeClauseContext) ctx);
            case Cypher6Parser.RULE_mergeAction -> exitMergeAction((Cypher6Parser.MergeActionContext) ctx);
            case Cypher6Parser.RULE_unwindClause -> exitUnwindClause((Cypher6Parser.UnwindClauseContext) ctx);
            case Cypher6Parser.RULE_callClause -> exitCallClause((Cypher6Parser.CallClauseContext) ctx);
            case Cypher6Parser.RULE_procedureName -> exitProcedureName((Cypher6Parser.ProcedureNameContext) ctx);
            case Cypher6Parser.RULE_procedureArgument -> exitProcedureArgument(
                    (Cypher6Parser.ProcedureArgumentContext) ctx);
            case Cypher6Parser.RULE_procedureResultItem -> exitProcedureResultItem(
                    (Cypher6Parser.ProcedureResultItemContext) ctx);
            case Cypher6Parser.RULE_loadCSVClause -> exitLoadCSVClause((Cypher6Parser.LoadCSVClauseContext) ctx);
            case Cypher6Parser.RULE_foreachClause -> exitForeachClause((Cypher6Parser.ForeachClauseContext) ctx);
            case Cypher6Parser.RULE_subqueryClause -> exitSubqueryClause((Cypher6Parser.SubqueryClauseContext) ctx);
            case Cypher6Parser.RULE_subqueryScope -> exitSubqueryScope((Cypher6Parser.SubqueryScopeContext) ctx);
            case Cypher6Parser.RULE_subqueryInTransactionsParameters -> exitSubqueryInTransactionsParameters(
                    (Cypher6Parser.SubqueryInTransactionsParametersContext) ctx);
            case Cypher6Parser.RULE_subqueryInTransactionsBatchParameters -> exitSubqueryInTransactionsBatchParameters(
                    (Cypher6Parser.SubqueryInTransactionsBatchParametersContext) ctx);
            case Cypher6Parser.RULE_subqueryInTransactionsErrorParameters -> exitSubqueryInTransactionsErrorParameters(
                    (Cypher6Parser.SubqueryInTransactionsErrorParametersContext) ctx);
            case Cypher6Parser
                    .RULE_subqueryInTransactionsReportParameters -> exitSubqueryInTransactionsReportParameters(
                    (Cypher6Parser.SubqueryInTransactionsReportParametersContext) ctx);
            case Cypher6Parser.RULE_orderBySkipLimitClause -> exitOrderBySkipLimitClause(
                    (Cypher6Parser.OrderBySkipLimitClauseContext) ctx);
            case Cypher6Parser.RULE_patternList -> exitPatternList((Cypher6Parser.PatternListContext) ctx);
            case Cypher6Parser.RULE_insertPatternList -> exitInsertPatternList(
                    (Cypher6Parser.InsertPatternListContext) ctx);
            case Cypher6Parser.RULE_pattern -> exitPattern((Cypher6Parser.PatternContext) ctx);
            case Cypher6Parser.RULE_insertPattern -> exitInsertPattern((Cypher6Parser.InsertPatternContext) ctx);
            case Cypher6Parser.RULE_quantifier -> exitQuantifier((Cypher6Parser.QuantifierContext) ctx);
            case Cypher6Parser.RULE_anonymousPattern -> exitAnonymousPattern(
                    (Cypher6Parser.AnonymousPatternContext) ctx);
            case Cypher6Parser.RULE_shortestPathPattern -> exitShortestPathPattern(
                    (Cypher6Parser.ShortestPathPatternContext) ctx);
            case Cypher6Parser.RULE_patternElement -> exitPatternElement((Cypher6Parser.PatternElementContext) ctx);
            case Cypher6Parser.RULE_selector -> exitSelector((Cypher6Parser.SelectorContext) ctx);
            case Cypher6Parser.RULE_groupToken -> exitGroupToken((Cypher6Parser.GroupTokenContext) ctx);
            case Cypher6Parser.RULE_pathToken -> exitPathToken((Cypher6Parser.PathTokenContext) ctx);
            case Cypher6Parser.RULE_pathPatternNonEmpty -> exitPathPatternNonEmpty(
                    (Cypher6Parser.PathPatternNonEmptyContext) ctx);
            case Cypher6Parser.RULE_nodePattern -> exitNodePattern((Cypher6Parser.NodePatternContext) ctx);
            case Cypher6Parser.RULE_insertNodePattern -> exitInsertNodePattern(
                    (Cypher6Parser.InsertNodePatternContext) ctx);
            case Cypher6Parser.RULE_parenthesizedPath -> exitParenthesizedPath(
                    (Cypher6Parser.ParenthesizedPathContext) ctx);
            case Cypher6Parser.RULE_nodeLabels -> exitNodeLabels((Cypher6Parser.NodeLabelsContext) ctx);
            case Cypher6Parser.RULE_nodeLabelsIs -> exitNodeLabelsIs((Cypher6Parser.NodeLabelsIsContext) ctx);
            case Cypher6Parser.RULE_dynamicExpression -> exitDynamicExpression(
                    (Cypher6Parser.DynamicExpressionContext) ctx);
            case Cypher6Parser.RULE_dynamicLabelType -> exitDynamicLabelType(
                    (Cypher6Parser.DynamicLabelTypeContext) ctx);
            case Cypher6Parser.RULE_labelType -> exitLabelType((Cypher6Parser.LabelTypeContext) ctx);
            case Cypher6Parser.RULE_relType -> exitRelType((Cypher6Parser.RelTypeContext) ctx);
            case Cypher6Parser.RULE_labelOrRelType -> exitLabelOrRelType((Cypher6Parser.LabelOrRelTypeContext) ctx);
            case Cypher6Parser.RULE_properties -> exitProperties((Cypher6Parser.PropertiesContext) ctx);
            case Cypher6Parser.RULE_relationshipPattern -> exitRelationshipPattern(
                    (Cypher6Parser.RelationshipPatternContext) ctx);
            case Cypher6Parser.RULE_insertRelationshipPattern -> exitInsertRelationshipPattern(
                    (Cypher6Parser.InsertRelationshipPatternContext) ctx);
            case Cypher6Parser.RULE_leftArrow -> exitLeftArrow((Cypher6Parser.LeftArrowContext) ctx);
            case Cypher6Parser.RULE_arrowLine -> exitArrowLine((Cypher6Parser.ArrowLineContext) ctx);
            case Cypher6Parser.RULE_rightArrow -> exitRightArrow((Cypher6Parser.RightArrowContext) ctx);
            case Cypher6Parser.RULE_pathLength -> exitPathLength((Cypher6Parser.PathLengthContext) ctx);
            case Cypher6Parser.RULE_labelExpression -> exitLabelExpression((Cypher6Parser.LabelExpressionContext) ctx);
            case Cypher6Parser.RULE_labelExpression4 -> exitLabelExpression4(
                    (Cypher6Parser.LabelExpression4Context) ctx);
            case Cypher6Parser.RULE_labelExpression4Is -> exitLabelExpression4Is(
                    (Cypher6Parser.LabelExpression4IsContext) ctx);
            case Cypher6Parser.RULE_labelExpression3 -> exitLabelExpression3(
                    (Cypher6Parser.LabelExpression3Context) ctx);
            case Cypher6Parser.RULE_labelExpression3Is -> exitLabelExpression3Is(
                    (Cypher6Parser.LabelExpression3IsContext) ctx);
            case Cypher6Parser.RULE_labelExpression2 -> exitLabelExpression2(
                    (Cypher6Parser.LabelExpression2Context) ctx);
            case Cypher6Parser.RULE_labelExpression2Is -> exitLabelExpression2Is(
                    (Cypher6Parser.LabelExpression2IsContext) ctx);
            case Cypher6Parser.RULE_labelExpression1 -> exitLabelExpression1(
                    (Cypher6Parser.LabelExpression1Context) ctx);
            case Cypher6Parser.RULE_labelExpression1Is -> exitLabelExpression1Is(
                    (Cypher6Parser.LabelExpression1IsContext) ctx);
            case Cypher6Parser.RULE_insertNodeLabelExpression -> exitInsertNodeLabelExpression(
                    (Cypher6Parser.InsertNodeLabelExpressionContext) ctx);
            case Cypher6Parser.RULE_insertRelationshipLabelExpression -> exitInsertRelationshipLabelExpression(
                    (Cypher6Parser.InsertRelationshipLabelExpressionContext) ctx);
            case Cypher6Parser.RULE_expression -> exitExpression((Cypher6Parser.ExpressionContext) ctx);
            case Cypher6Parser.RULE_expression11 -> exitExpression11((Cypher6Parser.Expression11Context) ctx);
            case Cypher6Parser.RULE_expression10 -> exitExpression10((Cypher6Parser.Expression10Context) ctx);
            case Cypher6Parser.RULE_expression9 -> exitExpression9((Cypher6Parser.Expression9Context) ctx);
            case Cypher6Parser.RULE_expression8 -> exitExpression8((Cypher6Parser.Expression8Context) ctx);
            case Cypher6Parser.RULE_expression7 -> exitExpression7((Cypher6Parser.Expression7Context) ctx);
            case Cypher6Parser.RULE_comparisonExpression6 -> exitComparisonExpression6(
                    (Cypher6Parser.ComparisonExpression6Context) ctx);
            case Cypher6Parser.RULE_normalForm -> exitNormalForm((Cypher6Parser.NormalFormContext) ctx);
            case Cypher6Parser.RULE_expression6 -> exitExpression6((Cypher6Parser.Expression6Context) ctx);
            case Cypher6Parser.RULE_expression5 -> exitExpression5((Cypher6Parser.Expression5Context) ctx);
            case Cypher6Parser.RULE_expression4 -> exitExpression4((Cypher6Parser.Expression4Context) ctx);
            case Cypher6Parser.RULE_expression3 -> exitExpression3((Cypher6Parser.Expression3Context) ctx);
            case Cypher6Parser.RULE_expression2 -> exitExpression2((Cypher6Parser.Expression2Context) ctx);
            case Cypher6Parser.RULE_postFix -> exitPostFix((Cypher6Parser.PostFixContext) ctx);
            case Cypher6Parser.RULE_property -> exitProperty((Cypher6Parser.PropertyContext) ctx);
            case Cypher6Parser.RULE_dynamicProperty -> exitDynamicProperty((Cypher6Parser.DynamicPropertyContext) ctx);
            case Cypher6Parser.RULE_propertyExpression -> exitPropertyExpression(
                    (Cypher6Parser.PropertyExpressionContext) ctx);
            case Cypher6Parser.RULE_dynamicPropertyExpression -> exitDynamicPropertyExpression(
                    (Cypher6Parser.DynamicPropertyExpressionContext) ctx);
            case Cypher6Parser.RULE_expression1 -> exitExpression1((Cypher6Parser.Expression1Context) ctx);
            case Cypher6Parser.RULE_literal -> exitLiteral((Cypher6Parser.LiteralContext) ctx);
            case Cypher6Parser.RULE_caseExpression -> exitCaseExpression((Cypher6Parser.CaseExpressionContext) ctx);
            case Cypher6Parser.RULE_caseAlternative -> exitCaseAlternative((Cypher6Parser.CaseAlternativeContext) ctx);
            case Cypher6Parser.RULE_extendedCaseExpression -> exitExtendedCaseExpression(
                    (Cypher6Parser.ExtendedCaseExpressionContext) ctx);
            case Cypher6Parser.RULE_extendedCaseAlternative -> exitExtendedCaseAlternative(
                    (Cypher6Parser.ExtendedCaseAlternativeContext) ctx);
            case Cypher6Parser.RULE_extendedWhen -> exitExtendedWhen((Cypher6Parser.ExtendedWhenContext) ctx);
            case Cypher6Parser.RULE_listComprehension -> exitListComprehension(
                    (Cypher6Parser.ListComprehensionContext) ctx);
            case Cypher6Parser.RULE_patternComprehension -> exitPatternComprehension(
                    (Cypher6Parser.PatternComprehensionContext) ctx);
            case Cypher6Parser.RULE_reduceExpression -> exitReduceExpression(
                    (Cypher6Parser.ReduceExpressionContext) ctx);
            case Cypher6Parser.RULE_listItemsPredicate -> exitListItemsPredicate(
                    (Cypher6Parser.ListItemsPredicateContext) ctx);
            case Cypher6Parser.RULE_normalizeFunction -> exitNormalizeFunction(
                    (Cypher6Parser.NormalizeFunctionContext) ctx);
            case Cypher6Parser.RULE_trimFunction -> exitTrimFunction((Cypher6Parser.TrimFunctionContext) ctx);
            case Cypher6Parser.RULE_patternExpression -> exitPatternExpression(
                    (Cypher6Parser.PatternExpressionContext) ctx);
            case Cypher6Parser.RULE_shortestPathExpression -> exitShortestPathExpression(
                    (Cypher6Parser.ShortestPathExpressionContext) ctx);
            case Cypher6Parser.RULE_parenthesizedExpression -> exitParenthesizedExpression(
                    (Cypher6Parser.ParenthesizedExpressionContext) ctx);
            case Cypher6Parser.RULE_mapProjection -> exitMapProjection((Cypher6Parser.MapProjectionContext) ctx);
            case Cypher6Parser.RULE_mapProjectionElement -> exitMapProjectionElement(
                    (Cypher6Parser.MapProjectionElementContext) ctx);
            case Cypher6Parser.RULE_countStar -> exitCountStar((Cypher6Parser.CountStarContext) ctx);
            case Cypher6Parser.RULE_existsExpression -> exitExistsExpression(
                    (Cypher6Parser.ExistsExpressionContext) ctx);
            case Cypher6Parser.RULE_countExpression -> exitCountExpression((Cypher6Parser.CountExpressionContext) ctx);
            case Cypher6Parser.RULE_collectExpression -> exitCollectExpression(
                    (Cypher6Parser.CollectExpressionContext) ctx);
            case Cypher6Parser.RULE_numberLiteral -> exitNumberLiteral((Cypher6Parser.NumberLiteralContext) ctx);
            case Cypher6Parser.RULE_signedIntegerLiteral -> exitSignedIntegerLiteral(
                    (Cypher6Parser.SignedIntegerLiteralContext) ctx);
            case Cypher6Parser.RULE_listLiteral -> exitListLiteral((Cypher6Parser.ListLiteralContext) ctx);
            case Cypher6Parser.RULE_propertyKeyName -> exitPropertyKeyName((Cypher6Parser.PropertyKeyNameContext) ctx);
            case Cypher6Parser.RULE_parameter -> exitParameter((Cypher6Parser.ParameterContext) ctx);
            case Cypher6Parser.RULE_parameterName -> exitParameterName((Cypher6Parser.ParameterNameContext) ctx);
            case Cypher6Parser.RULE_functionInvocation -> exitFunctionInvocation(
                    (Cypher6Parser.FunctionInvocationContext) ctx);
            case Cypher6Parser.RULE_functionArgument -> exitFunctionArgument(
                    (Cypher6Parser.FunctionArgumentContext) ctx);
            case Cypher6Parser.RULE_functionName -> exitFunctionName((Cypher6Parser.FunctionNameContext) ctx);
            case Cypher6Parser.RULE_namespace -> exitNamespace((Cypher6Parser.NamespaceContext) ctx);
            case Cypher6Parser.RULE_variable -> exitVariable((Cypher6Parser.VariableContext) ctx);
            case Cypher6Parser.RULE_nonEmptyNameList -> exitNonEmptyNameList(
                    (Cypher6Parser.NonEmptyNameListContext) ctx);
            case Cypher6Parser.RULE_type -> exitType((Cypher6Parser.TypeContext) ctx);
            case Cypher6Parser.RULE_typePart -> exitTypePart((Cypher6Parser.TypePartContext) ctx);
            case Cypher6Parser.RULE_typeName -> exitTypeName((Cypher6Parser.TypeNameContext) ctx);
            case Cypher6Parser.RULE_typeNullability -> exitTypeNullability((Cypher6Parser.TypeNullabilityContext) ctx);
            case Cypher6Parser.RULE_typeListSuffix -> exitTypeListSuffix((Cypher6Parser.TypeListSuffixContext) ctx);
            case Cypher6Parser.RULE_command -> exitCommand((Cypher6Parser.CommandContext) ctx);
            case Cypher6Parser.RULE_createCommand -> exitCreateCommand((Cypher6Parser.CreateCommandContext) ctx);
            case Cypher6Parser.RULE_dropCommand -> exitDropCommand((Cypher6Parser.DropCommandContext) ctx);
            case Cypher6Parser.RULE_showCommand -> exitShowCommand((Cypher6Parser.ShowCommandContext) ctx);
            case Cypher6Parser.RULE_showCommandYield -> exitShowCommandYield(
                    (Cypher6Parser.ShowCommandYieldContext) ctx);
            case Cypher6Parser.RULE_yieldItem -> exitYieldItem((Cypher6Parser.YieldItemContext) ctx);
            case Cypher6Parser.RULE_yieldSkip -> exitYieldSkip((Cypher6Parser.YieldSkipContext) ctx);
            case Cypher6Parser.RULE_yieldLimit -> exitYieldLimit((Cypher6Parser.YieldLimitContext) ctx);
            case Cypher6Parser.RULE_yieldClause -> exitYieldClause((Cypher6Parser.YieldClauseContext) ctx);
            case Cypher6Parser.RULE_commandOptions -> exitCommandOptions((Cypher6Parser.CommandOptionsContext) ctx);
            case Cypher6Parser.RULE_terminateCommand -> exitTerminateCommand(
                    (Cypher6Parser.TerminateCommandContext) ctx);
            case Cypher6Parser.RULE_composableCommandClauses -> exitComposableCommandClauses(
                    (Cypher6Parser.ComposableCommandClausesContext) ctx);
            case Cypher6Parser.RULE_composableShowCommandClauses -> exitComposableShowCommandClauses(
                    (Cypher6Parser.ComposableShowCommandClausesContext) ctx);
            case Cypher6Parser.RULE_showIndexCommand -> exitShowIndexCommand(
                    (Cypher6Parser.ShowIndexCommandContext) ctx);
            case Cypher6Parser.RULE_showIndexType -> exitShowIndexType((Cypher6Parser.ShowIndexTypeContext) ctx);
            case Cypher6Parser.RULE_showIndexesEnd -> exitShowIndexesEnd((Cypher6Parser.ShowIndexesEndContext) ctx);
            case Cypher6Parser.RULE_showConstraintCommand -> exitShowConstraintCommand(
                    (Cypher6Parser.ShowConstraintCommandContext) ctx);
            case Cypher6Parser.RULE_showConstraintEntity -> exitShowConstraintEntity(
                    (Cypher6Parser.ShowConstraintEntityContext) ctx);
            case Cypher6Parser.RULE_constraintExistType -> exitConstraintExistType(
                    (Cypher6Parser.ConstraintExistTypeContext) ctx);
            case Cypher6Parser.RULE_showConstraintsEnd -> exitShowConstraintsEnd(
                    (Cypher6Parser.ShowConstraintsEndContext) ctx);
            case Cypher6Parser.RULE_showProcedures -> exitShowProcedures((Cypher6Parser.ShowProceduresContext) ctx);
            case Cypher6Parser.RULE_showFunctions -> exitShowFunctions((Cypher6Parser.ShowFunctionsContext) ctx);
            case Cypher6Parser.RULE_functionToken -> exitFunctionToken((Cypher6Parser.FunctionTokenContext) ctx);
            case Cypher6Parser.RULE_executableBy -> exitExecutableBy((Cypher6Parser.ExecutableByContext) ctx);
            case Cypher6Parser.RULE_showFunctionsType -> exitShowFunctionsType(
                    (Cypher6Parser.ShowFunctionsTypeContext) ctx);
            case Cypher6Parser.RULE_showTransactions -> exitShowTransactions(
                    (Cypher6Parser.ShowTransactionsContext) ctx);
            case Cypher6Parser.RULE_terminateTransactions -> exitTerminateTransactions(
                    (Cypher6Parser.TerminateTransactionsContext) ctx);
            case Cypher6Parser.RULE_showSettings -> exitShowSettings((Cypher6Parser.ShowSettingsContext) ctx);
            case Cypher6Parser.RULE_settingToken -> exitSettingToken((Cypher6Parser.SettingTokenContext) ctx);
            case Cypher6Parser.RULE_namesAndClauses -> exitNamesAndClauses((Cypher6Parser.NamesAndClausesContext) ctx);
            case Cypher6Parser.RULE_stringsOrExpression -> exitStringsOrExpression(
                    (Cypher6Parser.StringsOrExpressionContext) ctx);
            case Cypher6Parser.RULE_commandNodePattern -> exitCommandNodePattern(
                    (Cypher6Parser.CommandNodePatternContext) ctx);
            case Cypher6Parser.RULE_commandRelPattern -> exitCommandRelPattern(
                    (Cypher6Parser.CommandRelPatternContext) ctx);
            case Cypher6Parser.RULE_createConstraint -> exitCreateConstraint(
                    (Cypher6Parser.CreateConstraintContext) ctx);
            case Cypher6Parser.RULE_constraintType -> exitConstraintType((Cypher6Parser.ConstraintTypeContext) ctx);
            case Cypher6Parser.RULE_dropConstraint -> exitDropConstraint((Cypher6Parser.DropConstraintContext) ctx);
            case Cypher6Parser.RULE_createIndex -> exitCreateIndex((Cypher6Parser.CreateIndexContext) ctx);
            case Cypher6Parser.RULE_createIndex_ -> exitCreateIndex_((Cypher6Parser.CreateIndex_Context) ctx);
            case Cypher6Parser.RULE_createFulltextIndex -> exitCreateFulltextIndex(
                    (Cypher6Parser.CreateFulltextIndexContext) ctx);
            case Cypher6Parser.RULE_fulltextNodePattern -> exitFulltextNodePattern(
                    (Cypher6Parser.FulltextNodePatternContext) ctx);
            case Cypher6Parser.RULE_fulltextRelPattern -> exitFulltextRelPattern(
                    (Cypher6Parser.FulltextRelPatternContext) ctx);
            case Cypher6Parser.RULE_createLookupIndex -> exitCreateLookupIndex(
                    (Cypher6Parser.CreateLookupIndexContext) ctx);
            case Cypher6Parser.RULE_lookupIndexNodePattern -> exitLookupIndexNodePattern(
                    (Cypher6Parser.LookupIndexNodePatternContext) ctx);
            case Cypher6Parser.RULE_lookupIndexRelPattern -> exitLookupIndexRelPattern(
                    (Cypher6Parser.LookupIndexRelPatternContext) ctx);
            case Cypher6Parser.RULE_dropIndex -> exitDropIndex((Cypher6Parser.DropIndexContext) ctx);
            case Cypher6Parser.RULE_propertyList -> exitPropertyList((Cypher6Parser.PropertyListContext) ctx);
            case Cypher6Parser.RULE_enclosedPropertyList -> exitEnclosedPropertyList(
                    (Cypher6Parser.EnclosedPropertyListContext) ctx);
            case Cypher6Parser.RULE_alterCommand -> exitAlterCommand((Cypher6Parser.AlterCommandContext) ctx);
            case Cypher6Parser.RULE_renameCommand -> exitRenameCommand((Cypher6Parser.RenameCommandContext) ctx);
            case Cypher6Parser.RULE_grantCommand -> exitGrantCommand((Cypher6Parser.GrantCommandContext) ctx);
            case Cypher6Parser.RULE_denyCommand -> exitDenyCommand((Cypher6Parser.DenyCommandContext) ctx);
            case Cypher6Parser.RULE_revokeCommand -> exitRevokeCommand((Cypher6Parser.RevokeCommandContext) ctx);
            case Cypher6Parser.RULE_userNames -> exitUserNames((Cypher6Parser.UserNamesContext) ctx);
            case Cypher6Parser.RULE_roleNames -> exitRoleNames((Cypher6Parser.RoleNamesContext) ctx);
            case Cypher6Parser.RULE_roleToken -> exitRoleToken((Cypher6Parser.RoleTokenContext) ctx);
            case Cypher6Parser.RULE_enableServerCommand -> exitEnableServerCommand(
                    (Cypher6Parser.EnableServerCommandContext) ctx);
            case Cypher6Parser.RULE_alterServer -> exitAlterServer((Cypher6Parser.AlterServerContext) ctx);
            case Cypher6Parser.RULE_renameServer -> exitRenameServer((Cypher6Parser.RenameServerContext) ctx);
            case Cypher6Parser.RULE_dropServer -> exitDropServer((Cypher6Parser.DropServerContext) ctx);
            case Cypher6Parser.RULE_showServers -> exitShowServers((Cypher6Parser.ShowServersContext) ctx);
            case Cypher6Parser.RULE_allocationCommand -> exitAllocationCommand(
                    (Cypher6Parser.AllocationCommandContext) ctx);
            case Cypher6Parser.RULE_deallocateDatabaseFromServers -> exitDeallocateDatabaseFromServers(
                    (Cypher6Parser.DeallocateDatabaseFromServersContext) ctx);
            case Cypher6Parser.RULE_reallocateDatabases -> exitReallocateDatabases(
                    (Cypher6Parser.ReallocateDatabasesContext) ctx);
            case Cypher6Parser.RULE_createRole -> exitCreateRole((Cypher6Parser.CreateRoleContext) ctx);
            case Cypher6Parser.RULE_dropRole -> exitDropRole((Cypher6Parser.DropRoleContext) ctx);
            case Cypher6Parser.RULE_renameRole -> exitRenameRole((Cypher6Parser.RenameRoleContext) ctx);
            case Cypher6Parser.RULE_showRoles -> exitShowRoles((Cypher6Parser.ShowRolesContext) ctx);
            case Cypher6Parser.RULE_grantRole -> exitGrantRole((Cypher6Parser.GrantRoleContext) ctx);
            case Cypher6Parser.RULE_revokeRole -> exitRevokeRole((Cypher6Parser.RevokeRoleContext) ctx);
            case Cypher6Parser.RULE_createUser -> exitCreateUser((Cypher6Parser.CreateUserContext) ctx);
            case Cypher6Parser.RULE_dropUser -> exitDropUser((Cypher6Parser.DropUserContext) ctx);
            case Cypher6Parser.RULE_renameUser -> exitRenameUser((Cypher6Parser.RenameUserContext) ctx);
            case Cypher6Parser.RULE_alterCurrentUser -> exitAlterCurrentUser(
                    (Cypher6Parser.AlterCurrentUserContext) ctx);
            case Cypher6Parser.RULE_alterUser -> exitAlterUser((Cypher6Parser.AlterUserContext) ctx);
            case Cypher6Parser.RULE_removeNamedProvider -> exitRemoveNamedProvider(
                    (Cypher6Parser.RemoveNamedProviderContext) ctx);
            case Cypher6Parser.RULE_password -> exitPassword((Cypher6Parser.PasswordContext) ctx);
            case Cypher6Parser.RULE_passwordOnly -> exitPasswordOnly((Cypher6Parser.PasswordOnlyContext) ctx);
            case Cypher6Parser.RULE_passwordExpression -> exitPasswordExpression(
                    (Cypher6Parser.PasswordExpressionContext) ctx);
            case Cypher6Parser.RULE_passwordChangeRequired -> exitPasswordChangeRequired(
                    (Cypher6Parser.PasswordChangeRequiredContext) ctx);
            case Cypher6Parser.RULE_userStatus -> exitUserStatus((Cypher6Parser.UserStatusContext) ctx);
            case Cypher6Parser.RULE_homeDatabase -> exitHomeDatabase((Cypher6Parser.HomeDatabaseContext) ctx);
            case Cypher6Parser.RULE_setAuthClause -> exitSetAuthClause((Cypher6Parser.SetAuthClauseContext) ctx);
            case Cypher6Parser.RULE_userAuthAttribute -> exitUserAuthAttribute(
                    (Cypher6Parser.UserAuthAttributeContext) ctx);
            case Cypher6Parser.RULE_showUsers -> exitShowUsers((Cypher6Parser.ShowUsersContext) ctx);
            case Cypher6Parser.RULE_showCurrentUser -> exitShowCurrentUser((Cypher6Parser.ShowCurrentUserContext) ctx);
            case Cypher6Parser.RULE_showSupportedPrivileges -> exitShowSupportedPrivileges(
                    (Cypher6Parser.ShowSupportedPrivilegesContext) ctx);
            case Cypher6Parser.RULE_showPrivileges -> exitShowPrivileges((Cypher6Parser.ShowPrivilegesContext) ctx);
            case Cypher6Parser.RULE_showRolePrivileges -> exitShowRolePrivileges(
                    (Cypher6Parser.ShowRolePrivilegesContext) ctx);
            case Cypher6Parser.RULE_showUserPrivileges -> exitShowUserPrivileges(
                    (Cypher6Parser.ShowUserPrivilegesContext) ctx);
            case Cypher6Parser.RULE_privilegeAsCommand -> exitPrivilegeAsCommand(
                    (Cypher6Parser.PrivilegeAsCommandContext) ctx);
            case Cypher6Parser.RULE_privilegeToken -> exitPrivilegeToken((Cypher6Parser.PrivilegeTokenContext) ctx);
            case Cypher6Parser.RULE_privilege -> exitPrivilege((Cypher6Parser.PrivilegeContext) ctx);
            case Cypher6Parser.RULE_allPrivilege -> exitAllPrivilege((Cypher6Parser.AllPrivilegeContext) ctx);
            case Cypher6Parser.RULE_allPrivilegeType -> exitAllPrivilegeType(
                    (Cypher6Parser.AllPrivilegeTypeContext) ctx);
            case Cypher6Parser.RULE_allPrivilegeTarget -> exitAllPrivilegeTarget(
                    (Cypher6Parser.AllPrivilegeTargetContext) ctx);
            case Cypher6Parser.RULE_createPrivilege -> exitCreatePrivilege((Cypher6Parser.CreatePrivilegeContext) ctx);
            case Cypher6Parser.RULE_createPrivilegeForDatabase -> exitCreatePrivilegeForDatabase(
                    (Cypher6Parser.CreatePrivilegeForDatabaseContext) ctx);
            case Cypher6Parser.RULE_createNodePrivilegeToken -> exitCreateNodePrivilegeToken(
                    (Cypher6Parser.CreateNodePrivilegeTokenContext) ctx);
            case Cypher6Parser.RULE_createRelPrivilegeToken -> exitCreateRelPrivilegeToken(
                    (Cypher6Parser.CreateRelPrivilegeTokenContext) ctx);
            case Cypher6Parser.RULE_createPropertyPrivilegeToken -> exitCreatePropertyPrivilegeToken(
                    (Cypher6Parser.CreatePropertyPrivilegeTokenContext) ctx);
            case Cypher6Parser.RULE_actionForDBMS -> exitActionForDBMS((Cypher6Parser.ActionForDBMSContext) ctx);
            case Cypher6Parser.RULE_dropPrivilege -> exitDropPrivilege((Cypher6Parser.DropPrivilegeContext) ctx);
            case Cypher6Parser.RULE_loadPrivilege -> exitLoadPrivilege((Cypher6Parser.LoadPrivilegeContext) ctx);
            case Cypher6Parser.RULE_showPrivilege -> exitShowPrivilege((Cypher6Parser.ShowPrivilegeContext) ctx);
            case Cypher6Parser.RULE_setPrivilege -> exitSetPrivilege((Cypher6Parser.SetPrivilegeContext) ctx);
            case Cypher6Parser.RULE_passwordToken -> exitPasswordToken((Cypher6Parser.PasswordTokenContext) ctx);
            case Cypher6Parser.RULE_removePrivilege -> exitRemovePrivilege((Cypher6Parser.RemovePrivilegeContext) ctx);
            case Cypher6Parser.RULE_writePrivilege -> exitWritePrivilege((Cypher6Parser.WritePrivilegeContext) ctx);
            case Cypher6Parser.RULE_databasePrivilege -> exitDatabasePrivilege(
                    (Cypher6Parser.DatabasePrivilegeContext) ctx);
            case Cypher6Parser.RULE_dbmsPrivilege -> exitDbmsPrivilege((Cypher6Parser.DbmsPrivilegeContext) ctx);
            case Cypher6Parser.RULE_dbmsPrivilegeExecute -> exitDbmsPrivilegeExecute(
                    (Cypher6Parser.DbmsPrivilegeExecuteContext) ctx);
            case Cypher6Parser.RULE_adminToken -> exitAdminToken((Cypher6Parser.AdminTokenContext) ctx);
            case Cypher6Parser.RULE_procedureToken -> exitProcedureToken((Cypher6Parser.ProcedureTokenContext) ctx);
            case Cypher6Parser.RULE_indexToken -> exitIndexToken((Cypher6Parser.IndexTokenContext) ctx);
            case Cypher6Parser.RULE_constraintToken -> exitConstraintToken((Cypher6Parser.ConstraintTokenContext) ctx);
            case Cypher6Parser.RULE_transactionToken -> exitTransactionToken(
                    (Cypher6Parser.TransactionTokenContext) ctx);
            case Cypher6Parser.RULE_userQualifier -> exitUserQualifier((Cypher6Parser.UserQualifierContext) ctx);
            case Cypher6Parser.RULE_executeFunctionQualifier -> exitExecuteFunctionQualifier(
                    (Cypher6Parser.ExecuteFunctionQualifierContext) ctx);
            case Cypher6Parser.RULE_executeProcedureQualifier -> exitExecuteProcedureQualifier(
                    (Cypher6Parser.ExecuteProcedureQualifierContext) ctx);
            case Cypher6Parser.RULE_settingQualifier -> exitSettingQualifier(
                    (Cypher6Parser.SettingQualifierContext) ctx);
            case Cypher6Parser.RULE_globs -> exitGlobs((Cypher6Parser.GlobsContext) ctx);
            case Cypher6Parser.RULE_glob -> exitGlob((Cypher6Parser.GlobContext) ctx);
            case Cypher6Parser.RULE_globRecursive -> exitGlobRecursive((Cypher6Parser.GlobRecursiveContext) ctx);
            case Cypher6Parser.RULE_globPart -> exitGlobPart((Cypher6Parser.GlobPartContext) ctx);
            case Cypher6Parser.RULE_qualifiedGraphPrivilegesWithProperty -> exitQualifiedGraphPrivilegesWithProperty(
                    (Cypher6Parser.QualifiedGraphPrivilegesWithPropertyContext) ctx);
            case Cypher6Parser.RULE_qualifiedGraphPrivileges -> exitQualifiedGraphPrivileges(
                    (Cypher6Parser.QualifiedGraphPrivilegesContext) ctx);
            case Cypher6Parser.RULE_labelsResource -> exitLabelsResource((Cypher6Parser.LabelsResourceContext) ctx);
            case Cypher6Parser.RULE_propertiesResource -> exitPropertiesResource(
                    (Cypher6Parser.PropertiesResourceContext) ctx);
            case Cypher6Parser.RULE_nonEmptyStringList -> exitNonEmptyStringList(
                    (Cypher6Parser.NonEmptyStringListContext) ctx);
            case Cypher6Parser.RULE_graphQualifier -> exitGraphQualifier((Cypher6Parser.GraphQualifierContext) ctx);
            case Cypher6Parser.RULE_graphQualifierToken -> exitGraphQualifierToken(
                    (Cypher6Parser.GraphQualifierTokenContext) ctx);
            case Cypher6Parser.RULE_relToken -> exitRelToken((Cypher6Parser.RelTokenContext) ctx);
            case Cypher6Parser.RULE_elementToken -> exitElementToken((Cypher6Parser.ElementTokenContext) ctx);
            case Cypher6Parser.RULE_nodeToken -> exitNodeToken((Cypher6Parser.NodeTokenContext) ctx);
            case Cypher6Parser.RULE_databaseScope -> exitDatabaseScope((Cypher6Parser.DatabaseScopeContext) ctx);
            case Cypher6Parser.RULE_graphScope -> exitGraphScope((Cypher6Parser.GraphScopeContext) ctx);
            case Cypher6Parser.RULE_createCompositeDatabase -> exitCreateCompositeDatabase(
                    (Cypher6Parser.CreateCompositeDatabaseContext) ctx);
            case Cypher6Parser.RULE_createDatabase -> exitCreateDatabase((Cypher6Parser.CreateDatabaseContext) ctx);
            case Cypher6Parser.RULE_primaryTopology -> exitPrimaryTopology((Cypher6Parser.PrimaryTopologyContext) ctx);
            case Cypher6Parser.RULE_primaryToken -> exitPrimaryToken((Cypher6Parser.PrimaryTokenContext) ctx);
            case Cypher6Parser.RULE_secondaryTopology -> exitSecondaryTopology(
                    (Cypher6Parser.SecondaryTopologyContext) ctx);
            case Cypher6Parser.RULE_secondaryToken -> exitSecondaryToken((Cypher6Parser.SecondaryTokenContext) ctx);
            case Cypher6Parser.RULE_dropDatabase -> exitDropDatabase((Cypher6Parser.DropDatabaseContext) ctx);
            case Cypher6Parser.RULE_alterDatabase -> exitAlterDatabase((Cypher6Parser.AlterDatabaseContext) ctx);
            case Cypher6Parser.RULE_alterDatabaseAccess -> exitAlterDatabaseAccess(
                    (Cypher6Parser.AlterDatabaseAccessContext) ctx);
            case Cypher6Parser.RULE_alterDatabaseTopology -> exitAlterDatabaseTopology(
                    (Cypher6Parser.AlterDatabaseTopologyContext) ctx);
            case Cypher6Parser.RULE_alterDatabaseOption -> exitAlterDatabaseOption(
                    (Cypher6Parser.AlterDatabaseOptionContext) ctx);
            case Cypher6Parser.RULE_startDatabase -> exitStartDatabase((Cypher6Parser.StartDatabaseContext) ctx);
            case Cypher6Parser.RULE_stopDatabase -> exitStopDatabase((Cypher6Parser.StopDatabaseContext) ctx);
            case Cypher6Parser.RULE_waitClause -> exitWaitClause((Cypher6Parser.WaitClauseContext) ctx);
            case Cypher6Parser.RULE_secondsToken -> exitSecondsToken((Cypher6Parser.SecondsTokenContext) ctx);
            case Cypher6Parser.RULE_showDatabase -> exitShowDatabase((Cypher6Parser.ShowDatabaseContext) ctx);
            case Cypher6Parser.RULE_createAlias -> exitCreateAlias((Cypher6Parser.CreateAliasContext) ctx);
            case Cypher6Parser.RULE_dropAlias -> exitDropAlias((Cypher6Parser.DropAliasContext) ctx);
            case Cypher6Parser.RULE_alterAlias -> exitAlterAlias((Cypher6Parser.AlterAliasContext) ctx);
            case Cypher6Parser.RULE_alterAliasTarget -> exitAlterAliasTarget(
                    (Cypher6Parser.AlterAliasTargetContext) ctx);
            case Cypher6Parser.RULE_alterAliasUser -> exitAlterAliasUser((Cypher6Parser.AlterAliasUserContext) ctx);
            case Cypher6Parser.RULE_alterAliasPassword -> exitAlterAliasPassword(
                    (Cypher6Parser.AlterAliasPasswordContext) ctx);
            case Cypher6Parser.RULE_alterAliasDriver -> exitAlterAliasDriver(
                    (Cypher6Parser.AlterAliasDriverContext) ctx);
            case Cypher6Parser.RULE_alterAliasProperties -> exitAlterAliasProperties(
                    (Cypher6Parser.AlterAliasPropertiesContext) ctx);
            case Cypher6Parser.RULE_showAliases -> exitShowAliases((Cypher6Parser.ShowAliasesContext) ctx);
            case Cypher6Parser.RULE_symbolicNameOrStringParameter -> exitSymbolicNameOrStringParameter(
                    (Cypher6Parser.SymbolicNameOrStringParameterContext) ctx);
            case Cypher6Parser.RULE_commandNameExpression -> exitCommandNameExpression(
                    (Cypher6Parser.CommandNameExpressionContext) ctx);
            case Cypher6Parser.RULE_symbolicNameOrStringParameterList -> exitSymbolicNameOrStringParameterList(
                    (Cypher6Parser.SymbolicNameOrStringParameterListContext) ctx);
            case Cypher6Parser.RULE_symbolicAliasNameList -> exitSymbolicAliasNameList(
                    (Cypher6Parser.SymbolicAliasNameListContext) ctx);
            case Cypher6Parser.RULE_symbolicAliasNameOrParameter -> exitSymbolicAliasNameOrParameter(
                    (Cypher6Parser.SymbolicAliasNameOrParameterContext) ctx);
            case Cypher6Parser.RULE_symbolicAliasName -> exitSymbolicAliasName(
                    (Cypher6Parser.SymbolicAliasNameContext) ctx);
            case Cypher6Parser.RULE_stringListLiteral -> exitStringListLiteral(
                    (Cypher6Parser.StringListLiteralContext) ctx);
            case Cypher6Parser.RULE_stringList -> exitStringList((Cypher6Parser.StringListContext) ctx);
            case Cypher6Parser.RULE_stringLiteral -> exitStringLiteral((Cypher6Parser.StringLiteralContext) ctx);
            case Cypher6Parser.RULE_stringOrParameterExpression -> exitStringOrParameterExpression(
                    (Cypher6Parser.StringOrParameterExpressionContext) ctx);
            case Cypher6Parser.RULE_stringOrParameter -> exitStringOrParameter(
                    (Cypher6Parser.StringOrParameterContext) ctx);
            case Cypher6Parser.RULE_mapOrParameter -> exitMapOrParameter((Cypher6Parser.MapOrParameterContext) ctx);
            case Cypher6Parser.RULE_map -> exitMap((Cypher6Parser.MapContext) ctx);
            case Cypher6Parser.RULE_symbolicNameString -> exitSymbolicNameString(
                    (Cypher6Parser.SymbolicNameStringContext) ctx);
            case Cypher6Parser.RULE_escapedSymbolicNameString -> exitEscapedSymbolicNameString(
                    (Cypher6Parser.EscapedSymbolicNameStringContext) ctx);
            case Cypher6Parser.RULE_unescapedSymbolicNameString -> exitUnescapedSymbolicNameString(
                    (Cypher6Parser.UnescapedSymbolicNameStringContext) ctx);
            case Cypher6Parser.RULE_symbolicLabelNameString -> exitSymbolicLabelNameString(
                    (Cypher6Parser.SymbolicLabelNameStringContext) ctx);
            case Cypher6Parser.RULE_unescapedLabelSymbolicNameString -> exitUnescapedLabelSymbolicNameString(
                    (Cypher6Parser.UnescapedLabelSymbolicNameStringContext) ctx);
            case Cypher6Parser.RULE_endOfFile -> exitEndOfFile((Cypher6Parser.EndOfFileContext) ctx);
            default -> throw new IllegalStateException("Unknown rule index " + ctx.getRuleIndex());
        }
    }
}
