
begin
    require 'cucumber/rake/task'
      Cucumber::Rake::Task.new(:features)
rescue LoadError
    puts "Cucumber is not available. In order to run features, you must: sudo gem install cucumber"
end

