[[tutorials-java-embedded-bolt]]
= Accessing Neo4j Embedded via the Bolt Protocol

:javadoc-graphdatabasefactory: javadocs/org/neo4j/graphdb/factory/GraphDatabaseFactory.html

[abstract]
--
Open a Bolt connector to your embedded instance to get GUI administration and other benefits.
--

The Neo4j Browser and the official Neo4j Drivers use the Bolt database protocol to communicate with Neo4j.
By default, Neo4j Embedded does not expose a Bolt connector, but you can enable one.
Doing so allows you to connect the services Neo4j Browser to your embedded instance.

It also gives you a way to incrementally transfer an existing Embedded application to use Neo4j Drivers instead.
Migrating to Neo4j Drivers means you become free to choose to run Neo4j Embedded or Neo4j Server, without changing your application code.

[[enable-embedded-bolt]]
To add a Bolt Connector to your embedded database, you need to add the Bolt extension to your class path.
This is done by adding an additional dependency to your project.

["source","xml","unnumbered","2",presubs="attributes"]
--------------------------------------------
<project>
...
 <dependencies>

  <dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-bolt</artifactId>
    <version>{neo4j-version}</version>
  </dependency>
  ...
 </dependencies>
...
</project>
--------------------------------------------

With this dependency in place, you can configure Neo4j to enable a Bolt connector.

[snippet,java]
----
component=neo4j-examples
source=org/neo4j/examples/EmbeddedNeo4jWithBolt.java
classifier=sources
tag=startDb
----
