= How to Compose Large Statements

== Combine statements with UNION

A Cypher statement is usually quite compact.
Expressing references between nodes as visual patterns makes them easy to understand.

If you want to combine the results of two statements that have the same result structure, you can use `UNION [ALL]`.

For instance if you want to list both actors and directors without using the alternative relationship-type syntax `()-[:ACTED_IN|:DIRECTED]->()` you can do this:

[source,cypher]
----
MATCH (p:Person)-[r:ACTED_IN]->(m:Movie)
RETURN p,type(r) as rel,m
UNION
MATCH (p:Person)-[r:DIRECTED]->(m:Movie)
RETURN p,type(r) as rel,m
----

//table

// maybe use a better example - we don't want users to to use it in this case or?

== Use WITH to Chain Statements

In Cypher it's possible to chain fragments of statements together, much like you would do within a data-flow pipeline.
Each fragment works on the output from the previous one and its results can feed into the next one.

You use the `WITH` clause to combine the individual parts and declare which data flows from one to the other.
`WITH` is very much like `RETURN` with the difference that it doesn't finish a query but prepares the input for the next part.
You can use the same expressions, aggregations, ordering and pagination as in the `RETURN` clause.

The only difference is that you _have to_ alias all columns as they would otherwise not be accessible with an identifier.
Every column that you don't declare in your `WITH` clause is not available in subsequent query parts.

[TIP]
If you want to filter by an aggregated value in SQL or simlilar languages you would have to use `HAVING`.
That's a single purpose clause for filtering aggregated information.
In Cypher, `WHERE` can be used in both cases.

// example to go here


