[[graph-algo]]
Graph Algorithms
================

Neo4j graph algorithms is a component that contains Neo4j implementations of some common algorithms for graphs.
It includes algorithms like:

* Shortest paths,
* all paths,
* all simple paths,
* Dijkstra and
* A*.

[[graph-algo-introduction]]
== Introduction ==

The graph algorithms are found in the +neo4j-graph-algo+ component, which is included in the standard Neo4j download.

* link:javadocs/org/neo4j/graphalgo/package-summary.html[Javadocs]
* http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.neo4j%22%20AND%20a%3A%22neo4j-graph-algo%22[Download]
* https://github.com/neo4j/neo4j/tree/{neo4j-git-tag}/community/graph-algo[Source code]

For examples, see <<rest-api-graph-algos>> (REST API) and <<tutorials-java-embedded-graph-algo>> (embedded database).

For information on how to use neo4j-graph-algo as a dependency with Maven and other dependency management tools, see +http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.neo4j%22%20AND%20a%3A%22neo4j-graph-algo%22[org.neo4j:neo4j-graph-algo]+
Note that it should be used with the same version of +http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.neo4j%22%20AND%20a%3A%22neo4j-kernel%22[org.neo4j:neo4j-kernel]+.
Different versions of the graph-algo and kernel components are not compatible in the general case.
Both components are included transitively by the +http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.neo4j%22%20AND%20a%3A%22neo4j%22[org.neo4j:neo4j]+ artifact which makes it simple to keep the versions in sync.

The starting point to find and use graph algorithms is +link:javadocs/org/neo4j/graphalgo/GraphAlgoFactory.html[GraphAlgoFactory]+ when using the Java Core API.


