[[configuration-settings]]
= Configuration Settings Reference

On this page you'll find the main configuration settings you can use with Neo4j.
They can be set in <<file-locations, _neo4j.conf_>> (for configuring the embedded database see <<tutorials-java-embedded-setup-config>>).

For additional configuration settings, see:

* <<config-org.neo4j.shell.ShellSettings>>
* <<config-org.neo4j.kernel.ha.HaSettings>>
* <<config-org.neo4j.cluster.ClusterSettings>>
* <<config-org.neo4j.backup.OnlineBackupSettings>>
* <<config-org.neo4j.consistency.ConsistencyCheckSettings>>
* <<config-org.neo4j.ext.udc.UdcSettings>>
* <<config-org.neo4j.metrics.MetricsSettings>>

include::configuration-attributes.asciidoc[]

include::{importdir}/neo4j-server-docs-jar/ops/configuration-attributes.asciidoc[]

include::{importdir}/neo4j-dbms-docs-jar/ops/configuration-attributes.asciidoc[]

== Configuring Bolt Connectors

Bolt Connectors are ports that accept connections via the Bolt Database Protocol, which is the protocol used by official Neo4j Driver Libraries.
You can configure Neo4j with one or more connectors.
This allows you, for instance, to have separate connectors for remote and local connections, with different encryption requirements.

If you are using Neo4j Embedded, you need to include the Bolt extension on your class path to enable Bolt.
See <<tutorials-java-embedded-bolt>> for details on how to open a Bolt connector from Neo4j Embedded.

Each connector has a unique key to identify it, denoted `{key}` in the listing below.

include::configuration-attributes-bolt-connector.asciidoc[]
