[[community-contribution-areas]]
Areas for contribution
======================

Neo4j is a project with a vast ecosystem and a lot of space for contributions. Where you can and want to pitch in depends of course on your time, skill set and interests. Below are some of the areas that might interest you:

== Neo4j Distribution ==

* https://github.com/neo4j/community/issues[The Neo4j Community open issues] for some starting points for contribution 
* See the https://github.com/neo4j/[GitHub Neo4j area] for a list of projects

== Maintaining Neo4j Documentation ==

Some parts of the documentation need extra care from the community to stay up to date.
They typically refer to different kinds of community contributions. 
Below is a list of such places, feel free to look into them and check for outdated or missing content!
The easiest way to contribute fixes is to comment at the http://docs.neo4j.org/chunked/snapshot/[online HTML version].

* <<tutorials-rest>>

== Drivers and bindings to Neo4j ==

* REST: see <<tutorials-rest>> for a list of active projects

